#
#      Copyright (c) 1996-1999 Malcolm Beattie
#
#      You may distribute under the terms of either the GNU General Public
#      License or the Artistic License, as specified in the README file.
#
#
#
# This file is autogenerated from bytecode.pl. Changes made here will be lost.
#
package B::Asmdata;

our $VERSION = '1.00';

use Exporter;
@ISA = qw(Exporter);
@EXPORT_OK = qw(%insn_data @insn_name @optype @specialsv_name);
our(%insn_data, @insn_name, @optype, @specialsv_name);

@optype = qw(OP UNOP BINOP LOGOP LISTOP PMOP SVOP PADOP PVOP LOOP COP);
@specialsv_name = qw(Nullsv &PL_sv_undef &PL_sv_yes &PL_sv_no pWARN_ALL pWARN_NONE);

# XXX insn_data is initialised this way because with a large
# %insn_data = (foo => [...], bar => [...], ...) initialiser
# I get a hard-to-track-down stack underflow and segfault.
$insn_data{comment} = [35, \&PUT_comment_t, "GET_comment_t"];
$insn_data{nop} = [10, \&PUT_none, "GET_none"];
$insn_data{ret} = [0, \&PUT_none, "GET_none"];
$insn_data{ldsv} = [1, \&PUT_svindex, "GET_svindex"];
$insn_data{ldop} = [2, \&PUT_opindex, "GET_opindex"];
$insn_data{stsv} = [3, \&PUT_U32, "GET_U32"];
$insn_data{stop} = [4, \&PUT_U32, "GET_U32"];
$insn_data{stpv} = [5, \&PUT_U32, "GET_U32"];
$insn_data{ldspecsv} = [6, \&PUT_U8, "GET_U8"];
$insn_data{newsv} = [7, \&PUT_U8, "GET_U8"];
$insn_data{newop} = [8, \&PUT_U8, "GET_U8"];
$insn_data{newopn} = [9, \&PUT_U8, "GET_U8"];
$insn_data{newpv} = [11, \&PUT_PV, "GET_PV"];
$insn_data{pv_cur} = [12, \&PUT_U32, "GET_U32"];
$insn_data{pv_free} = [13, \&PUT_none, "GET_none"];
$insn_data{sv_upgrade} = [14, \&PUT_U8, "GET_U8"];
$insn_data{sv_refcnt} = [15, \&PUT_U32, "GET_U32"];
$insn_data{sv_refcnt_add} = [16, \&PUT_I32, "GET_I32"];
$insn_data{sv_flags} = [17, \&PUT_U32, "GET_U32"];
$insn_data{xrv} = [18, \&PUT_svindex, "GET_svindex"];
$insn_data{xpv} = [19, \&PUT_none, "GET_none"];
$insn_data{xpv_cur} = [20, \&PUT_U32, "GET_U32"];
$insn_data{xpv_len} = [21, \&PUT_U32, "GET_U32"];
$insn_data{xiv} = [22, \&PUT_IV, "GET_IV"];
$insn_data{xnv} = [23, \&PUT_NV, "GET_NV"];
$insn_data{xlv_targoff} = [24, \&PUT_U32, "GET_U32"];
$insn_data{xlv_targlen} = [25, \&PUT_U32, "GET_U32"];
$insn_data{xlv_targ} = [26, \&PUT_svindex, "GET_svindex"];
$insn_data{xlv_type} = [27, \&PUT_U8, "GET_U8"];
$insn_data{xbm_useful} = [28, \&PUT_I32, "GET_I32"];
$insn_data{xbm_previous} = [29, \&PUT_U16, "GET_U16"];
$insn_data{xbm_rare} = [30, \&PUT_U8, "GET_U8"];
$insn_data{xfm_lines} = [31, \&PUT_IV, "GET_IV"];
$insn_data{xio_lines} = [32, \&PUT_IV, "GET_IV"];
$insn_data{xio_page} = [33, \&PUT_IV, "GET_IV"];
$insn_data{xio_page_len} = [34, \&PUT_IV, "GET_IV"];
$insn_data{xio_lines_left} = [36, \&PUT_IV, "GET_IV"];
$insn_data{xio_top_name} = [37, \&PUT_pvindex, "GET_pvindex"];
$insn_data{xio_top_gv} = [38, \&PUT_svindex, "GET_svindex"];
$insn_data{xio_fmt_name} = [39, \&PUT_pvindex, "GET_pvindex"];
$insn_data{xio_fmt_gv} = [40, \&PUT_svindex, "GET_svindex"];
$insn_data{xio_bottom_name} = [41, \&PUT_pvindex, "GET_pvindex"];
$insn_data{xio_bottom_gv} = [42, \&PUT_svindex, "GET_svindex"];
$insn_data{xio_subprocess} = [43, \&PUT_U16, "GET_U16"];
$insn_data{xio_type} = [44, \&PUT_U8, "GET_U8"];
$insn_data{xio_flags} = [45, \&PUT_U8, "GET_U8"];
$insn_data{xcv_xsubany} = [46, \&PUT_svindex, "GET_svindex"];
$insn_data{xcv_stash} = [47, \&PUT_svindex, "GET_svindex"];
$insn_data{xcv_start} = [48, \&PUT_opindex, "GET_opindex"];
$insn_data{xcv_root} = [49, \&PUT_opindex, "GET_opindex"];
$insn_data{xcv_gv} = [50, \&PUT_svindex, "GET_svindex"];
$insn_data{xcv_file} = [51, \&PUT_pvindex, "GET_pvindex"];
$insn_data{xcv_depth} = [52, \&PUT_I32, "GET_I32"];
$insn_data{xcv_padlist} = [53, \&PUT_svindex, "GET_svindex"];
$insn_data{xcv_outside} = [54, \&PUT_svindex, "GET_svindex"];
$insn_data{xcv_outside_seq} = [55, \&PUT_U32, "GET_U32"];
$insn_data{xcv_flags} = [56, \&PUT_U16, "GET_U16"];
$insn_data{av_extend} = [57, \&PUT_I32, "GET_I32"];
$insn_data{av_pushx} = [58, \&PUT_svindex, "GET_svindex"];
$insn_data{av_push} = [59, \&PUT_svindex, "GET_svindex"];
$insn_data{xav_fill} = [60, \&PUT_I32, "GET_I32"];
$insn_data{xav_max} = [61, \&PUT_I32, "GET_I32"];
$insn_data{xav_flags} = [62, \&PUT_U8, "GET_U8"];
$insn_data{xhv_riter} = [63, \&PUT_I32, "GET_I32"];
$insn_data{xhv_name} = [64, \&PUT_pvindex, "GET_pvindex"];
$insn_data{xhv_pmroot} = [65, \&PUT_opindex, "GET_opindex"];
$insn_data{hv_store} = [66, \&PUT_svindex, "GET_svindex"];
$insn_data{sv_magic} = [67, \&PUT_U8, "GET_U8"];
$insn_data{mg_obj} = [68, \&PUT_svindex, "GET_svindex"];
$insn_data{mg_private} = [69, \&PUT_U16, "GET_U16"];
$insn_data{mg_flags} = [70, \&PUT_U8, "GET_U8"];
$insn_data{mg_name} = [71, \&PUT_pvcontents, "GET_pvcontents"];
$insn_data{mg_namex} = [72, \&PUT_svindex, "GET_svindex"];
$insn_data{xmg_stash} = [73, \&PUT_svindex, "GET_svindex"];
$insn_data{gv_fetchpv} = [74, \&PUT_strconst, "GET_strconst"];
$insn_data{gv_stashpv} = [75, \&PUT_strconst, "GET_strconst"];
$insn_data{gp_sv} = [76, \&PUT_svindex, "GET_svindex"];
$insn_data{gp_refcnt} = [77, \&PUT_U32, "GET_U32"];
$insn_data{gp_refcnt_add} = [78, \&PUT_I32, "GET_I32"];
$insn_data{gp_av} = [79, \&PUT_svindex, "GET_svindex"];
$insn_data{gp_hv} = [80, \&PUT_svindex, "GET_svindex"];
$insn_data{gp_cv} = [81, \&PUT_svindex, "GET_svindex"];
$insn_data{gp_file} = [82, \&PUT_pvindex, "GET_pvindex"];
$insn_data{gp_io} = [83, \&PUT_svindex, "GET_svindex"];
$insn_data{gp_form} = [84, \&PUT_svindex, "GET_svindex"];
$insn_data{gp_cvgen} = [85, \&PUT_U32, "GET_U32"];
$insn_data{gp_line} = [86, \&PUT_U32, "GET_U32"];
$insn_data{gp_share} = [87, \&PUT_svindex, "GET_svindex"];
$insn_data{xgv_flags} = [88, \&PUT_U8, "GET_U8"];
$insn_data{op_next} = [89, \&PUT_opindex, "GET_opindex"];
$insn_data{op_sibling} = [90, \&PUT_opindex, "GET_opindex"];
$insn_data{op_ppaddr} = [91, \&PUT_strconst, "GET_strconst"];
$insn_data{op_targ} = [92, \&PUT_U32, "GET_U32"];
$insn_data{op_type} = [93, \&PUT_U16, "GET_U16"];
$insn_data{op_seq} = [94, \&PUT_U16, "GET_U16"];
$insn_data{op_flags} = [95, \&PUT_U8, "GET_U8"];
$insn_data{op_private} = [96, \&PUT_U8, "GET_U8"];
$insn_data{op_first} = [97, \&PUT_opindex, "GET_opindex"];
$insn_data{op_last} = [98, \&PUT_opindex, "GET_opindex"];
$insn_data{op_other} = [99, \&PUT_opindex, "GET_opindex"];
$insn_data{op_pmreplroot} = [100, \&PUT_opindex, "GET_opindex"];
$insn_data{op_pmreplstart} = [101, \&PUT_opindex, "GET_opindex"];
$insn_data{op_pmnext} = [102, \&PUT_opindex, "GET_opindex"];
$insn_data{op_pmstashpv} = [103, \&PUT_pvindex, "GET_pvindex"];
$insn_data{op_pmreplrootpo} = [104, \&PUT_U32, "GET_U32"];
$insn_data{op_pmstash} = [105, \&PUT_svindex, "GET_svindex"];
$insn_data{op_pmreplrootgv} = [106, \&PUT_svindex, "GET_svindex"];
$insn_data{pregcomp} = [107, \&PUT_pvcontents, "GET_pvcontents"];
$insn_data{op_pmflags} = [108, \&PUT_U16, "GET_U16"];
$insn_data{op_pmpermflags} = [109, \&PUT_U16, "GET_U16"];
$insn_data{op_pmdynflags} = [110, \&PUT_U8, "GET_U8"];
$insn_data{op_sv} = [111, \&PUT_svindex, "GET_svindex"];
$insn_data{op_padix} = [112, \&PUT_U32, "GET_U32"];
$insn_data{op_pv} = [113, \&PUT_pvcontents, "GET_pvcontents"];
$insn_data{op_pv_tr} = [114, \&PUT_op_tr_array, "GET_op_tr_array"];
$insn_data{op_redoop} = [115, \&PUT_opindex, "GET_opindex"];
$insn_data{op_nextop} = [116, \&PUT_opindex, "GET_opindex"];
$insn_data{op_lastop} = [117, \&PUT_opindex, "GET_opindex"];
$insn_data{cop_label} = [118, \&PUT_pvindex, "GET_pvindex"];
$insn_data{cop_stashpv} = [119, \&PUT_pvindex, "GET_pvindex"];
$insn_data{cop_file} = [120, \&PUT_pvindex, "GET_pvindex"];
$insn_data{cop_stash} = [121, \&PUT_svindex, "GET_svindex"];
$insn_data{cop_filegv} = [122, \&PUT_svindex, "GET_svindex"];
$insn_data{cop_seq} = [123, \&PUT_U32, "GET_U32"];
$insn_data{cop_arybase} = [124, \&PUT_I32, "GET_I32"];
$insn_data{cop_line} = [125, \&PUT_U32, "GET_U32"];
$insn_data{cop_io} = [126, \&PUT_svindex, "GET_svindex"];
$insn_data{cop_warnings} = [127, \&PUT_svindex, "GET_svindex"];
$insn_data{main_start} = [128, \&PUT_opindex, "GET_opindex"];
$insn_data{main_root} = [129, \&PUT_opindex, "GET_opindex"];
$insn_data{main_cv} = [130, \&PUT_svindex, "GET_svindex"];
$insn_data{curpad} = [131, \&PUT_svindex, "GET_svindex"];
$insn_data{push_begin} = [132, \&PUT_svindex, "GET_svindex"];
$insn_data{push_init} = [133, \&PUT_svindex, "GET_svindex"];
$insn_data{push_end} = [134, \&PUT_svindex, "GET_svindex"];
$insn_data{curstash} = [135, \&PUT_svindex, "GET_svindex"];
$insn_data{defstash} = [136, \&PUT_svindex, "GET_svindex"];
$insn_data{data} = [137, \&PUT_U8, "GET_U8"];
$insn_data{incav} = [138, \&PUT_svindex, "GET_svindex"];
$insn_data{load_glob} = [139, \&PUT_svindex, "GET_svindex"];
$insn_data{regex_padav} = [140, \&PUT_svindex, "GET_svindex"];
$insn_data{dowarn} = [141, \&PUT_U8, "GET_U8"];
$insn_data{comppad_name} = [142, \&PUT_svindex, "GET_svindex"];
$insn_data{xgv_stash} = [143, \&PUT_svindex, "GET_svindex"];
$insn_data{signal} = [144, \&PUT_strconst, "GET_strconst"];
$insn_data{formfeed} = [145, \&PUT_svindex, "GET_svindex"];

my ($insn_name, $insn_data);
while (($insn_name, $insn_data) = each %insn_data) {
    $insn_name[$insn_data->[0]] = $insn_name;
}
# Fill in any gaps
@insn_name = map($_ || "unused", @insn_name);

1;

__END__

=head1 NAME

B::Asmdata - Autogenerated data about Perl ops, used to generate bytecode

=head1 SYNOPSIS

	use B::Asmdata qw(%insn_data @insn_name @optype @specialsv_name);

=head1 DESCRIPTION

Provides information about Perl ops in order to generate bytecode via
a bunch of exported variables.  Its mostly used by B::Assembler and
B::Disassembler.

=over 4

=item %insn_data

  my($bytecode_num, $put_sub, $get_meth) = @$insn_data{$op_name};

For a given $op_name (for example, 'cop_label', 'sv_flags', etc...) 
you get an array ref containing the bytecode number of the op, a
reference to the subroutine used to 'PUT', and the name of the method
used to 'GET'.

=for _private
Add more detail about what $put_sub and $get_meth are and how to use them.

=item @insn_name

  my $op_name = $insn_name[$bytecode_num];

A simple mapping of the bytecode number to the name of the op.
Suitable for using with %insn_data like so:

  my $op_info = $insn_data{$insn_name[$bytecode_num]};

=item @optype

  my $op_type = $optype[$op_type_num];

A simple mapping of the op type number to its type (like 'COP' or 'BINOP').

=item @specialsv_name

  my $sv_name = $specialsv_name[$sv_index];

Certain SV types are considered 'special'.  They're represented by
B::SPECIAL and are refered to by a number from the specialsv_list.
This array maps that number back to the name of the SV (like 'Nullsv'
or '&PL_sv_undef').

=back

=head1 AUTHOR

Malcolm Beattie, C<mbeattie@sable.ox.ac.uk>

=cut
