=encoding utf8

=head1 NAME

perl54310delta - what is new for perl v5.43.10

=head1 DESCRIPTION

This document describes differences between the 5.43.9 release and the 5.43.10
release.

If you are upgrading from an earlier release such as 5.43.8, first read
L<perl5439delta>, which describes differences between 5.43.8 and 5.43.9.

=head1 Modules and Pragmata

=head2 Updated Modules and Pragmata

=over 4

=item *

L<B::Concise> has been upgraded from version 1.011 to 1.012.

=item *

L<File::Glob> has been upgraded from version 1.43 to 1.44.

=item *

L<Module::CoreList> has been upgraded from version 5.20260320 to 5.20260420.

=item *

L<Module::Metadata> has been upgraded from version 1.000038 to 1.000039.

=item *

L<Pod::Simple> has been upgraded from version 3.47 to 3.48.

=item *

L<version> has been upgraded from version 0.9933 to 0.9934.

=back

=head1 Internal Changes

=over 4

=item *

When a UTF-8 constant string was used as the hash key in an insert
operation, such as C<$hash{'über maus'} = 1;>, and the string could
be converted into a single byte representation, the flag noting the
original encoding (C<HVhek_WASUTF8>) was not always retained.

When this occurred, the relevant scalars returned by C<keys %hash>
would not be in the original, expected UTF-8 encoding.

The original encoding is now captured and propagated.
[L<GH #24266|https://github.com/Perl/perl5/issues/24266>]

=item *

When a constant IV or NV was used as a hash key, such as in
C<< my %hash = ( 42 => 0 ); >>, and was preemptively stringified
into a hash key, the fact that the numerical value came first
was lost. This unintentionally modified deparse output for
such keys.

The numerical values are now carried across, and flags on the
key variable reflect the original data type.

Note: This now preserves the form of constant keys supplied
to tied hashes in list assignments.
[L<GH #24302|https://github.com/Perl/perl5/issues/24302>]

=item *

L<perlapi/defer_error>, formerly known as C<qerror>, and
L<perlapi/op_clear> are now part of the API.

Perl 5.43.2 hid Perl non-API function declarations unless you defined
C<PERL_EXT> or C<PERL_CORE>, so these non-API functions no longer had
visible declarations.

A small number of CPAN modules used these APIs and a stricter GCC 15
started enforcing C99 disallowing implicit function declarations,
producing build failures.

Added qerror() as a deprecated public alias for defer_error() to allow
existing users of that name to build successfully.

[L<GH #23676|https://github.com/Perl/perl5/issues/23676>]

=back

=head1 Acknowledgements

Perl 5.43.10 represents approximately 4 weeks of development since Perl
5.43.9 and contains approximately 21,000 lines of changes across 240 files
from 20 authors.

Excluding auto-generated files, documentation and release tools, there were
approximately 17,000 lines of changes to 120 .pm, .t, .c and .h files.

Perl continues to flourish into its fourth decade thanks to a vibrant
community of users and developers. The following people are known to have
contributed the improvements that became Perl 5.43.10:

Christian Hansen, Craig A. Berry, Daniel Tang, Dmitrii Kuvaiskii, E.
Choroba, Eric Herman, James Cook, James E Keenan, Karen Etheridge, Karl
Williamson, Leon Timmermans, Lukas Mai, Nicolas R, Paul Evans, Philippe
Bruhat (BooK), Richard Leach, Robert Rothenberg, Shirakata Kentaro, Steve
Hay, Tony Cook.

The list above is almost certainly incomplete as it is automatically
generated from version control history. In particular, it does not include
the names of the (very much appreciated) contributors who reported issues to
the Perl bug tracker.

Many of the changes included in this version originated in the CPAN modules
included in Perl's core. We're grateful to the entire CPAN community for
helping Perl to flourish.

For a more complete list of all of Perl's historical contributors, please
see the F<AUTHORS> file in the Perl source distribution.

=head1 Reporting Bugs

If you find what you think is a bug, you might check the perl bug database
at L<https://github.com/Perl/perl5/issues>. There may also be information at
L<https://www.perl.org/>, the Perl Home Page.

If you believe you have an unreported bug, please open an issue at
L<https://github.com/Perl/perl5/issues>. Be sure to trim your bug down to a
tiny but sufficient test case.

If the bug you are reporting has security implications which make it
inappropriate to send to a public issue tracker, then see
L<perlsec/SECURITY VULNERABILITY CONTACT INFORMATION>
for details of how to report the issue.

=head1 Give Thanks

If you wish to thank the Perl 5 Porters for the work we had done in Perl 5,
you can do so by running the C<perlthanks> program:

    perlthanks

This will send an email to the Perl 5 Porters list with your show of thanks.

=head1 SEE ALSO

The F<Changes> file for an explanation of how to view exhaustive details on
what changed.

The F<INSTALL> file for how to build Perl.

The F<README> file for general stuff.

The F<Artistic> and F<Copying> files for copyright information.

=cut
