=encoding utf8

=head1 NAME

perl5399delta - what is new for perl v5.39.9

=head1 Modules and Pragmata

=head2 Updated Modules and Pragmata

=over 4

=item *

L<bytes> has been upgraded from version 1.08 to 1.09.

=item *

L<Compress::Raw::Bzip2> has been upgraded from version 2.206 to 2.210.

=item *

L<Compress::Raw::Zlib> has been upgraded from version 2.206 to 2.209.

=item *

L<DynaLoader> has been upgraded from version 1.55 to 1.56.

=item *

L<Encode> has been upgraded from version 3.20 to 3.21.

=item *

L<Fcntl> has been upgraded from version 1.16 to 1.17.

=item *

L<IO::Compress> has been upgraded from version 2.206 to 2.207.

=item *

L<IO::Zlib> has been upgraded from version 1.14 to 1.15.

=item *

L<Module::CoreList> has been upgraded from version 5.20240223 to 5.20240320.

=item *

L<re> has been upgraded from version 0.45 to 0.47.

=item *

L<Text::Tabs> has been upgraded from version 2023.0511 to 2024.001.

=item *

L<Text::Wrap> has been upgraded from version 2023.0511 to 2024.001.

=item *

L<Tie::File> has been upgraded from version 1.08 to 1.09.

Old compatibility code for perl 5.005 that was no longer functional has been
removed.

=item *

L<Time::HiRes> has been upgraded from version 1.9776 to 1.9777.

=back
