=encoding utf8

=head1 NAME

perl5395delta - what is new for perl v5.39.5

=head1 Modules and Pragmata

=head2 Updated Modules and Pragmata

=over 4

=item *

L<Benchmark> has been upgraded from version 1.24 to 1.25.

=item *

L<builtin> has been upgraded from version 0.011 to 0.012.

Added the C<load_module()> builtin function as per L<PPC 0006|https://github.com/Perl/PPCs/blob/main/ppcs/ppc0006-load-module.md>.

=item *

L<Encode> has been upgraded from version 3.19 to 3.20.

=item *

L<Getopt::Long> has been upgraded from version 2.54 to 2.57.

=item *

L<IO> has been upgraded from version 1.53 to 1.54.

Fixed C<IO::Handle/blocking> on Windows, which has been non-functional
since IO 1.32.  [L<GH #17455|https://github.com/Perl/perl5/issues/17455>]

=item *

L<locale> has been upgraded from version 1.10 to 1.11.

=item *

L<Math::BigInt> has been upgraded from version 1.999842 to 2.001000.

=item *

L<Module::CoreList> has been upgraded from version 5.20231025 to 5.20231120.

=item *

L<POSIX> has been upgraded from version 2.16 to 2.17.

Adjusted the signbit() on NaN test to handle the unusual bit pattern
returned for NaN by Oracle Developer Studio's compiler.  [L<GH #21533|https://github.com/Perl/perl5/issues/21533>]

=item *

L<Term::Table> has been upgraded from version 0.017 to 0.018.

=item *

L<Test2::Suite> has been upgraded from version 0.000156 to 0.000159.

=back
