=encoding utf8

=head1 NAME

perl5393delta - what is new for perl v5.39.3

=head1 Modules and Pragmata

=head2 Updated Modules and Pragmata

=over 4

=item *

L<B> has been upgraded from version 1.88 to 1.89.

=item *

L<builtin> has been upgraded to version 0.010.  It now has an C<unimport>
method, allowing you to remove lexically-imported functions by the
C<no builtin ...> syntax.

=item *

L<Data::Dumper> has been upgraded from version 2.188 to 2.189.

=item *

L<DB_File> has been upgraded from version 1.858 to 1.859.

=item *

L<Devel::PPPort> has been upgraded from version 3.71 to 3.72.

=item *

L<ExtUtils::CBuilder> has been upgraded from version 0.280239 to 0.280240.

=item *

L<fields> has been upgraded from version 2.24 to 2.25.

=item *

L<File::Compare> has been upgraded from version 1.1007 to 1.1008.

=item *

L<FindBin> has been upgraded from version 1.53 to 1.54.

=item *

L<Getopt::Std> has been upgraded from version 1.13 to 1.14.  Documentation and test improvements only; no change in functionality.

=item *

L<IO> has been upgraded from version 1.52 to 1.53.

=item *

L<Module::CoreList> has been upgraded from version 5.20230820 to 5.20230920.

=item *

L<threads> has been upgraded from version 2.38 to 2.39.

=item *

L<threads::shared> has been upgraded from version 1.68 to 1.69.

=back
