=encoding utf8

=head1 NAME

perl5392delta - what is new for perl v5.39.2

=head1 Modules and Pragmata

=head2 Updated Modules and Pragmata

=over 4

=item *

L<Compress::Raw::Bzip2> has been upgraded from version 2.205 to 2.206.

=item *

L<Compress::Raw::Zlib> has been upgraded from version 2.205 to 2.206.

=item *

L<Devel::Peek> has been upgraded from version 1.33 to 1.34.

=item *

L<ExtUtils::Miniperl> has been upgraded from version 1.13 to 1.14.

=item *

L<feature> has been upgraded from version 1.83 to 1.84.

=item *

L<File::Spec> has been upgraded from version 3.89 to 3.90.

=item *

L<HTTP::Tiny> has been upgraded from version 0.086 to 0.088.

=item *

L<IO::Compress> has been upgraded from version 2.205 to 2.206.

=item *

L<IO::Socket::IP> has been upgraded from version 0.41_01 to 0.42.

=item *

L<Module::CoreList> has been upgraded from version 5.20230720 to 5.20230820.

=item *

L<NDBM_File> has been upgraded from version 1.16 to 1.17.

=item *

L<Opcode> has been upgraded from version 1.64 to 1.65.

=item *

L<perlfaq> has been upgraded from version 5.20230701 to 5.20230812.

=item *

L<PerlIO::scalar> has been upgraded from version 0.31 to 0.32.

=item *

L<PerlIO::via> has been upgraded from version 0.18 to 0.19.

=item *

L<Pod::Html> has been upgraded from version 1.34 to 1.35.

=item *

L<Pod::Simple> has been upgraded from version 3.43 to 3.45.

=item *

L<POSIX> has been upgraded from version 2.14 to 2.15.

=item *

L<Safe> has been upgraded from version 2.44 to 2.45.

=item *

L<strict> has been upgraded from version 1.12 to 1.13.

=item *

L<Test::Harness> has been upgraded from version 3.44 to 3.47.

=item *

L<threads> has been upgraded from version 2.37 to 2.38.

=item *

L<warnings> has been upgraded from version 1.66 to 1.67.

=item *

L<XS::APItest> has been upgraded from version 1.32 to 1.33.

=back
