=encoding utf8

=head1 NAME

perldelta - what is new for perl v5.17.11

=head1 DESCRIPTION

This document describes differences between the 5.17.10 release and the 5.17.11
release.

If you are upgrading from an earlier release such as 5.17.9, first read
L<perl51710delta>, which describes differences between 5.17.9 and 5.17.10.

=head1 Incompatible Changes

Although no major incompatibilities have been introduced, the "switch" family
of features have been marked experimental and will now emit warnings.  These
are:  the C<~~> operator, C<given>, and C<when>.

=head1 Modules and Pragmata

=head2 Updated Modules and Pragmata

=over 4

=item *

Fixed the merge of ExtUtils-MakeMaker 6.65_01 to remove an excluded
file.  This was causing a test failure on Win32 [perl #117477]

=item *

B::Deparse has been upgraded from version 1.19 to 1.20, adding stub deparsing
for lexical subroutines.

=item *

bigint has been upgraded from version 0.33 to 0.34.

=item *

CPAN has been upgraded from its trial 2.00 release to its final 2.00 release.

=item *

Exporter has been upgraded from version 5.67 to 5.68.

=item *

ExtUtils::CBuilder has been upgraded from version 0.280209 to 0.280210.

=item *

ExtUtils::MakeMaker has been upgraded from version 6.65_01 to 6.66.

=item *

IO has been upgraded from version 1.27 to 1.28.

=item *

overload has been upgraded from version 1.21 to 1.22.

=item *

Storable has been upgraded from version 2.40 to 2.41.

=item *

warnings has been upgraded from version 1.17 to 1.18.

=back

=head2 Changes to Existing Documentation

=head3 Asian-language documentation

The Asian-language documentation, previously stored in a few different
encodings, have been transcoded to UTF-8.

=head1 Diagnostics

The following additions or changes have been made to diagnostic output,
including warnings and fatal error messages.  For the complete list of
diagnostic messages, see L<perldiag>.

=head3 New Warnings

=over 4

=item *

L<Smartmatch is experimental|perldiag/"Smartmatch is experimental">

=item *

L<given is experimental|perldiag/"given is experimental">

=item *

L<when is experimental|perldiag/"when is experimental">

=back

=head1 Platform Support

=head2 Platform-Specific Notes

=over 4

=item VMS

As of 5.18.0, Perl on VMS can (at last) be built in and installed from a
directory having dots in the name, so it is no longer necessary to rename the
top-level source directory before building.

The pertinent instructions have been removed from README.vms, so we also no
longer need to update the version number that was embedded in those
instructions.

=back

=head1 Selected Bug Fixes

=over 4

=item Make vms.c's Perl_flex_fstat preserve errno on success

=item split's first argument is more consistently interpreted

After some changes earlier in 5.17, C<split>'s behavior has been simplified: if
the PATTERN argument evaluates to a literal string containing one space, it is
treated the way that a I<literal> string containing one space once was.

=item Handle overloading properly in compile-time regex

C<(?{…})> and C<qr> constant overloading did not play nicely together, and when
C<qr> constant overloading was in effect, C<qr> constructs inside a C<(?{…})>
construct were incorrectly interpreted. [perl #116823]

=back

=head1 Acknowledgements

Perl 5.17.11 represents approximately 4 weeks of development since Perl 5.17.10
and contains approximately 3,800 lines of changes across 130 files from 17
authors.

Perl continues to flourish into its third decade thanks to a vibrant community
of users and developers. The following people are known to have contributed the
improvements that became Perl 5.17.11:

Aaron Crane, Andy Dougherty, Brian Fraser, Chris 'BinGOs' Williams, Craig A.
Berry, David Mitchell, François Perrad, James E Keenan, Jan Dubois, Karl
Williamson, Leon Timmermans, Max Maischein, Moritz Lenz, Nicholas Clark,
Ricardo Signes, Tony Cook, Yves Orton.

The list above is almost certainly incomplete as it is automatically generated
from version control history. In particular, it does not include the names of
the (very much appreciated) contributors who reported issues to the Perl bug
tracker.

Many of the changes included in this version originated in the CPAN modules
included in Perl's core. We're grateful to the entire CPAN community for
helping Perl to flourish.

For a more complete list of all of Perl's historical contributors, please see
the F<AUTHORS> file in the Perl source distribution.

=head1 Reporting Bugs

If you find what you think is a bug, you might check the articles recently
posted to the comp.lang.perl.misc newsgroup and the perl bug database at
http://rt.perl.org/perlbug/ .  There may also be information at
http://www.perl.org/ , the Perl Home Page.

If you believe you have an unreported bug, please run the L<perlbug> program
included with your release.  Be sure to trim your bug down to a tiny but
sufficient test case.  Your bug report, along with the output of C<perl -V>,
will be sent off to perlbug@perl.org to be analysed by the Perl porting team.

If the bug you are reporting has security implications, which make it
inappropriate to send to a publicly archived mailing list, then please send it
to perl5-security-report@perl.org.  This points to a closed subscription
unarchived mailing list, which includes all the core committers, who will be
able to help assess the impact of issues, figure out a resolution, and help
co-ordinate the release of patches to mitigate or fix the problem across all
platforms on which Perl is supported.  Please only use this address for
security issues in the Perl core, not for modules independently distributed on
CPAN.

=head1 SEE ALSO

The F<Changes> file for an explanation of how to view exhaustive details on
what changed.

The F<INSTALL> file for how to build Perl.

The F<README> file for general stuff.

The F<Artistic> and F<Copying> files for copyright information.

=cut
