=encoding utf8

=head1 NAME

perl5396delta - what is new for perl v5.39.6

=head2 Updated Modules and Pragmata

=over 4

=item *

L<Archive::Tar> has been upgraded from version 2.40 to 3.02_001.

=item *

L<Fcntl> has been upgraded from version 1.15 to 1.16.

This version adds support for the C<O_TMPFILE> flag on Linux.

=item *

L<feature> has been upgraded from version 1.85 to 1.86.

=item *

L<IO> has been upgraded from version 1.54 to 1.55.

=item *

L<Math::BigInt> has been upgraded from version 2.001000 to 2.003001.

=item *

L<Module::CoreList> has been upgraded from version 5.20231120 to 5.20231230.

=item *

L<re> has been upgraded from version 0.44 to 0.45.

=item *

L<Test::Simple> has been upgraded from version 1.302195 to 1.302198.

=item *

L<threads> has been upgraded from version 2.39 to 2.40.

An internal error has been made slightly more verbose
(C<Out of memory in perl:threads:ithread_create>).

=back

