=encoding utf8

=head1 NAME

perl5394delta - what is new for perl v5.39.4

=head1 Modules and Pragmata

=head2 New Modules and Pragmata

=over 4

=item *

L<Term::Table> 0.017 has been added to the Perl core.

This module is a dependency of L<Test2::Suite>.

=item *

L<Test2::Suite> 0.000156 has been added to the Perl core.

This distribution contains a comprehensive set of test tools for writing unit
tests.  It is the successor to L<Test::More> and similar modules.  Its
inclusion in the Perl core means that CPAN module tests can be written using
this suite of tools without extra dependencies.

=back

=head2 Updated Modules and Pragmata

=over 4

=item *

L<builtin> has been upgraded from version 0.010 to 0.011.

L<builtin> now accepts a version bundle as an input argument, requesting it to
import all of the functions that are considered a stable part of the module at
the given Perl version. For example:

    use builtin ':5.40';

=item *

L<feature> has been upgraded from version 1.84 to 1.85.

It now documents the C<:all> feature bundle, and suggests a reason why you may
not wish to use it.

=item *

L<File::Find> has been upgraded from version 1.43 to 1.44.

=item *

L<File::stat> has been upgraded from version 1.13 to 1.14.

=item *

L<Math::BigInt> has been upgraded from version 1.999839 to 1.999842.

=item *

L<Math::BigInt::FastCalc> has been upgraded from version 0.5014 to 0.5015.

=item *

L<Module::CoreList> has been upgraded from version 5.20230920 to 5.20231025.

=item *

L<perl5db.pl> has been upgraded from version 1.77 to 1.78.

Made parsing of the C<l> command arguments saner.
[L<GH #21350|https://github.com/Perl/perl5/issues/21350>]

=item *

L<POSIX> has been upgraded from version 2.15 to 2.16.

The C<mktime> function now works correctly on 32-bit platforms even if the
platform's C<time_t> type is larger than 32 bits. [L<GH #21551|https://github.com/Perl/perl5/issues/21551>]

The C<T_SIGNO> and C<T_FD> typemap entries have been fixed so they work with
any variable name, rather than just the hardcoded C<sig> and C<fd>.

The mappings for C<Mode_t>, C<pid_t>, C<Uid_t>, C<Gid_t> and C<Time_t> have
been updated to be integer types; previously they were C<NV> floating-point.

=item *

L<Test::Harness> has been upgraded from version 3.47 to 3.48.

=item *

L<Time::gmtime> has been upgraded from version 1.04 to 1.05.

=item *

L<Time::localtime> has been upgraded from version 1.03 to 1.04.

=item *

L<Time::tm> has been upgraded from version 1.00 to 1.01.

=item *

L<User::grent> has been upgraded from version 1.04 to 1.05.

=item *

L<User::pwent> has been upgraded from version 1.02 to 1.03.

=item *

L<version> has been upgraded from version 0.9929 to 0.9930.

=item *

L<XS::APItest> has been upgraded from version 1.33 to 1.34.

=item *

L<XS::Typemap> has been upgraded from version 0.19 to 0.20.

=back
