=encoding utf8

=head1 NAME

perl5353delta - what is new for perl v5.35.3

=head1 DESCRIPTION

This document describes differences between the 5.35.2 release and the 5.35.3
release.

If you are upgrading from an earlier release such as 5.35.1, first read
L<perl5352delta>, which describes differences between 5.35.1 and 5.35.2.

=head1 Notice

With this release, the experimental C<switch> feature, present in every feature
bundle since they were introduced in v5.10, has been removed from the v5.36
bundle.  If you want to live dangerously and use it, you'll have to enable it
explicitly.

=head1 Core Enhancements

All warnings are enabled automatically within the scope of
a C<L<use v5.35|perlfunc/use VERSION>> (or higher) declaration.

=head1 Modules and Pragmata

=head2 Updated Modules and Pragmata

=over 4

=item *

L<Archive::Tar> has been upgraded from version 2.38 to 2.40.

=item *

L<diagnostics> has been upgraded from version 1.37 to 1.38.

=item *

L<Encode> has been upgraded from version 3.10 to 3.12.

=item *

L<feature> has been upgraded from version 1.66 to 1.67.

Added a simple API to check which features or feature bundles are
enabled.  (github L<#18968|https://github.com/Perl/perl5/pull/18968>)

=item *

L<Module::CoreList> has been upgraded from version 5.20210723 to 5.20210820.

=item *

L<Opcode> has been upgraded from version 1.52 to 1.53.

=item *

L<Pod::Html> has been upgraded from version 1.31 to 1.32.

=item *

L<POSIX> has been upgraded from version 1.98 to 1.99.

=item *

L<sort> has been upgraded from version 2.04 to 2.05.

The C<sort> pragma is now a no-op, and its use is discouraged.
C<sort::current> now issues a deprecation warning and always returns I<stable>.

=item *

L<Storable> has been upgraded from version 3.23 to 3.24.

=item *

L<Text::Tabs> has been upgraded from version 2021.0717 to 2021.0804.

=item *

L<Text::Wrap> has been upgraded from version 2021.0717 to 2021.0804.

=item *

L<threads::shared> has been upgraded from version 1.62 to 1.63.

=item *

L<Time::HiRes> has been upgraded from version 1.9768 to 1.9769.

Makefile.PL now correct handles configuration set in perl hints.
(github L<#18953|https://github.com/Perl/perl5/issues/18953>)

=item *

L<Unicode::Normalize> has been upgraded from version 1.28 to 1.30.

=item *

L<warnings> has been upgraded from version 1.52 to 1.53.

=item *

L<XS::APItest> has been upgraded from version 1.17 to 1.18.

=back

=head1 Documentation

=head2 New Documentation

=head3 F<Porting/vote_admin_guide.pod>

This document provides the process for administering an election or vote
within the Perl Core Team.

=head2 Changes to Existing Documentation

We have attempted to update the documentation to reflect the changes
listed in this document.  If you find any we have missed, open an issue
at L<https://github.com/Perl/perl5/issues>.

Additionally, the following selected changes have been made:

=head3 L<perlop>

=over 4

=item *

now notes that an invocant only needs to be an object or class name
for method calls, not for subroutine references.

=back

=head3 L<perlexperiment>

=over 4

=item *

notes the C<:win32> IO pseudolayer is removed (this happened in 5.35.2).

=back

=head3 L<perldeprecation>

=over 4

=item *

notes the new location for functions moved from L<Pod::Html> to
L<Pod::Html::Util> that are no longer intended to be used outside of core.

=back

=head1 Configuration and Compilation

=over 4

=item *

The makedepend step is now run in parallel by using make

This reduces the time for

  time sh ./makedepend MAKE=make cflags

from 5 seconds to 2 seconds with MAKEFLAGS=-j8

=item *

F<Configure> now tests whether C<< #include <xlocale.h> >> is required
to use the POSIX 1003 thread-safe locale functions or some related
extensions.  This prevents problems where a non-public F<xlocale.h> is
removed in a library update, or F<xlocale.h> isn't intended for public
use. (github L<#18936|https://github.com/Perl/perl5/pull/18936>)

=back

=head1 Internal Changes

=over 4

=item *

Macros have been added to F<perl.h> to facilitate version comparisons:
C<PERL_GCC_VERSION_GE>, C<PERL_GCC_VERSION_GT>, C<PERL_GCC_VERSION_LE> and
C<PERL_GCC_VERSION_LT>.

Inline functions have been added to F<embed.h> to determine the position of
the least significant 1 bit in a word: C<lsbit_pos32> and C<lsbit_pos64>.

=back

=head1 Selected Bug Fixes

=over 4

=item *

Use of the C<mktables> debugging facility would cause perl to croak since
v5.31.10; this problem has now been fixed.

=item *

C<makedepend> logic is now compatible with BSD make (fixes
L<GH #19046|https://github.com/Perl/perl5/issues/19046>).

=back

=head1 Errata From Previous Releases

=over 4

=item *

L<perl5300delta> mistakenly identified a CVE whose correct identification is CVE-2015-1592.

=back

=head1 Acknowledgements

Perl 5.35.3 represents approximately 4 weeks of development since Perl
5.35.2 and contains approximately 16,000 lines of changes across 220 files
from 25 authors.

Excluding auto-generated files, documentation and release tools, there were
approximately 9,200 lines of changes to 140 .pm, .t, .c and .h files.

Perl continues to flourish into its fourth decade thanks to a vibrant
community of users and developers. The following people are known to have
contributed the improvements that became Perl 5.35.3:

Aristotle Pagaltzis, Asher Mancinelli, Ben Cornett, Biswapriyo Nath, Chris
'BinGOs' Williams, Dagfinn Ilmari Mannsåker, Dan Book, Dan Jacobson, David
Golden, David Mitchell, H.Merijn Brand, James E Keenan, Karen Etheridge,
Karl Williamson, Leon Timmermans, Max Maischein, Neil Bowers, Nicholas
Clark, Petar-Kaleychev, Ricardo Signes, Richard Leach, Slaven Rezic, TAKAI
Kousuke, Thibault Duponchelle, Tony Cook.

The list above is almost certainly incomplete as it is automatically
generated from version control history. In particular, it does not include
the names of the (very much appreciated) contributors who reported issues to
the Perl bug tracker.

Many of the changes included in this version originated in the CPAN modules
included in Perl's core. We're grateful to the entire CPAN community for
helping Perl to flourish.

For a more complete list of all of Perl's historical contributors, please
see the F<AUTHORS> file in the Perl source distribution.

=head1 Reporting Bugs

If you find what you think is a bug, you might check the perl bug database
at L<https://github.com/Perl/perl5/issues>.  There may also be information at
L<http://www.perl.org/>, the Perl Home Page.

If you believe you have an unreported bug, please open an issue at
L<https://github.com/Perl/perl5/issues>.  Be sure to trim your bug down to a
tiny but sufficient test case.

If the bug you are reporting has security implications which make it
inappropriate to send to a public issue tracker, then see
L<perlsec/SECURITY VULNERABILITY CONTACT INFORMATION>
for details of how to report the issue.

=head1 Give Thanks

If you wish to thank the Perl 5 Porters for the work we had done in Perl 5,
you can do so by running the C<perlthanks> program:

    perlthanks

This will send an email to the Perl 5 Porters list with your show of thanks.

=head1 SEE ALSO

The F<Changes> file for an explanation of how to view exhaustive details on
what changed.

The F<INSTALL> file for how to build Perl.

The F<README> file for general stuff.

The F<Artistic> and F<Copying> files for copyright information.

=cut
