#!/bin/sh

# Check whether commit (default: HEAD) contains only whitespace changes (including newline changes)

git show \
    --word-diff=porcelain\
    --word-diff-regex='[^[:space:]]' \
    "${1:-HEAD}" \
|   grep -E '^(\+|-)'
