#!/usr/bin/perl

use strict;
use warnings;

# A tool to build a perl release tarball
# Very basic but functional - if you're on a unix system.
#
# If you're on Win32 then it should still work, but various Unix command-line
# tools will need to be available somewhere. An obvious choice is to install
# Cygwin and ensure its 'bin' folder is on the PATH in the shell where you run
# this script. The Cygwin 'bin' folder needs to precede the Windows 'system32'
# folder so that Cygwin's 'find' command is found in preference to the Windows
# 'find' command. In addition to the commands installed by default, your Cygwin
# installation will need to contain at least the 'cpio' and '7z' commands.
# Finally, ensure that the 'awk' and '7z' commands
# are copies of 'gawk.exe' and 'lib\p7zip\7z.exe' respectively,
# rather than the links to them that only work in a Cygwin bash shell which
# they are by default.
#
# No matter how automated this gets, you'll always need to read
# and re-read pumpkin.pod and release_managers_guide.pod to
# check for things to be done at various stages of the process.
#
# Tim Bunce, June 1997

use ExtUtils::Manifest qw(manicheck);
$ExtUtils::Manifest::Quiet = 1;
use Getopt::Long;
use Digest::SHA;

$|=1;

sub usage { die <<EOF; }
usage: $0 [ -r rootdir ] [-s suffix ] [ -x ] [ -n ]
    -r rootdir   directory under which to create the build dir and tarball
                 defaults to '..'
    -s suffix    suffix to append to the perl-x.y.z dir and tarball name
		 defaults to the concatenation of the local_patches entry
		 in patchlevel.h (or blank, if none)
    -x           make a .xz file in addition to a .gz file
    -n           do not make any tarballs, just the directory
    -c           perform a cleanup before building: clean git repo and target
                 directory/tarballs
    -e[1047|037] Make the outputs be translated into EBCDIC.  (They can then
                 be downloaded directly to an EBCDIC platform without needing
                 any further translation.)  1047 is assumed if the argument to
                 -e is omitted.
EOF

my $relroot = "..";
my $suffix;
my $additional_xz = 0;
my $no_tarballs = 0;
my $cleanup_first = 0;
my $ebcdic_code_page = undef;

GetOptions (
             "r=s" => \$relroot,
             "s:s" => \$suffix,
             "x"   => \$additional_xz,
             "n"   => \$no_tarballs,
             "c"   => \$cleanup_first,
             "e:s" => \$ebcdic_code_page,
            )
or die usage;

$ebcdic_code_page = "1047" if defined $ebcdic_code_page
                                 && ! $ebcdic_code_page;

die "Must be in root of the perl source tree.\n"
	unless -f "./MANIFEST" and -f "patchlevel.h";

open PATCHLEVEL, '<', 'patchlevel.h' or die;
my @patchlevel_h = <PATCHLEVEL>;
close PATCHLEVEL;
my $patchlevel_h = join "", grep { /^#\s*define/ } @patchlevel_h;
print $patchlevel_h;
my $revision = $1 if $patchlevel_h =~ /PERL_REVISION\s+(\d+)/;
my $patchlevel = $1 if $patchlevel_h =~ /PERL_VERSION\s+(\d+)/;
my $subversion = $1 if $patchlevel_h =~ /PERL_SUBVERSION\s+(\d+)/;
die "Unable to parse patchlevel.h" unless $subversion >= 0;
my $vers = sprintf("%d.%d.%d", $revision, $patchlevel, $subversion);

# fetch list of local patches
my (@local_patches, @lpatch_tags, $lpatch_tags);
@local_patches = grep { !/^\s*,?NULL/ && ! /,"uncommitted-changes"/ }
                 grep { /^static.*local_patches/../^};/ }
                 @patchlevel_h;
@lpatch_tags   = map  {  /^\s*,"(\w+)/ } @local_patches;
$lpatch_tags   = join "-", @lpatch_tags;

my $perl = "perl-$vers";
my $reldir = "$perl";

$lpatch_tags = $suffix if defined $suffix;
$reldir .= "-$lpatch_tags" if $lpatch_tags;

print "\nMaking a release for $perl in $relroot/$reldir\n\n";

cleanup($relroot, $reldir) if $cleanup_first;

print "Cross-checking the MANIFEST...\n";
my @missfile = manicheck();
if (@missfile) {
    warn "Can't make a release with MANIFEST files missing:\n";
    warn "\t".$_."\n" for (@missfile);
}
die "Aborted.\n" if @missfile;
print "\n";

# VMS no longer has hardcoded version numbers descrip.mms

print "Creating $relroot/$reldir release directory...\n";
die "$relroot/$reldir release directory already exists [consider using -c]\n"   if -e "$relroot/$reldir";
die "$relroot/$reldir.tar.gz release file already exists [consider using -c]\n" if -e "$relroot/$reldir.tar.gz";
die "$relroot/$reldir.tar.xz release file already exists [consider using -c]\n" if $additional_xz && -e "$relroot/$reldir.tar.xz";
mkdir("$relroot/$reldir", 0755) or die "mkdir $relroot/$reldir: $!\n";
print "\n";


print "Copying files to release directory...\n";
# ExtUtils::Manifest maniread does not preserve the order
my $cmd = "awk '{print \$1}' MANIFEST | cpio -pdm $relroot/$reldir";
system($cmd) == 0
    or die "$cmd failed";
print "\n";

chdir "$relroot/$reldir" or die $!;

my @exe = map   { my ($f) = split; glob($f) }
          grep  { $_ !~ /\A#/ && $_ !~ /\A\s*\z/ }
          map   { split "\n" }
          do    { local (@ARGV, $/) = 'Porting/exec-bit.txt'; <> };

if ($ebcdic_code_page) {
    die "$0 must be run on an ASCII platform" if ord("A") != 65;

    my @known_binary_files = qw(
        cpan/Archive-Tar/t/src/linktest/linktest_missing_dir.tar
        cpan/Archive-Tar/t/src/linktest/linktest_with_dir.tar
        cpan/Archive-Tar/t/src/long/bar.tar
        cpan/Archive-Tar/t/src/long/foo.tbz
        cpan/Archive-Tar/t/src/long/foo.tgz
        cpan/Archive-Tar/t/src/long/prefix-directory-concat.tar
        cpan/Archive-Tar/t/src/short/bar.tar
        cpan/Archive-Tar/t/src/short/foo.tbz
        cpan/Archive-Tar/t/src/short/foo.tgz
        cpan/Encode/t/big5-eten.enc
        cpan/Encode/t/big5-hkscs.enc
        cpan/Encode/t/enc_module.enc
        cpan/Encode/t/gb2312.enc
        cpan/Encode/t/jisx0201.enc
        cpan/Encode/t/jisx0208.enc
        cpan/Encode/t/jisx0212.enc
        cpan/Encode/t/ksc5601.enc
        cpan/ExtUtils-MakeMaker/t/testdata/reallylongdirectoryname/arch1/Config.pm
        cpan/ExtUtils-MakeMaker/t/testdata/reallylongdirectoryname/arch2/Config.pm
        cpan/IO-Compress/t/files/bad-efs.zip
        cpan/IO-Compress/t/files/encrypt-aes.zip
        cpan/IO-Compress/t/files/encrypt-standard.zip
        cpan/IO-Compress/t/files/jar.zip
        cpan/IO-Compress/t/files/test.ods
        cpan/IO-Compress/t/files/testfile1.odt
        cpan/IO-Compress/t/files/time-invalid.zip
        cpan/IO-Compress/t/files/time-zero.zip
        cpan/IPC-Cmd/t/src/x.tgz
        cpan/Pod-Checker/t/pod/empty.xr
        os2/diff.configure
        win32/perlexe.ico
    );

    my %known_binary_files;
    $known_binary_files{$_} = 1 for @known_binary_files;

    my @known_alien_encoding_files = qw(
        cpan/Pod-Simple/t/corpus/2202jp.txt
        cpan/Pod-Simple/t/corpus/2202jpx.txt
        cpan/Pod-Simple/t/corpus/2202jpy.txt
        cpan/Pod-Simple/t/corpus/2202jpz.txt
        cpan/Pod-Simple/t/corpus/8859_7.pod
        cpan/Pod-Simple/t/corpus/cp1256.txt
        cpan/Pod-Simple/t/corpus/fet_cont.txt
        cpan/Pod-Simple/t/corpus/fet_dup.txt
        cpan/Pod-Simple/t/corpus/iso6.txt
        cpan/Pod-Simple/t/corpus/koi8r.txt
        cpan/Pod-Simple/t/corpus/laozi38.txt
        cpan/Pod-Simple/t/corpus/laozi38b.txt
        cpan/Pod-Simple/t/corpus/laozi38p.pod
        cpan/Pod-Simple/t/corpus/nonesuch.txt
        cpan/Pod-Simple/t/corpus/pasternak_cp1251.txt
        cpan/Pod-Simple/t/corpus/s2763_sjis.txt
        cpan/Pod-Simple/t/corpus/thai_iso11.txt
        cpan/Pod-Simple/t/corpus2/fiqhakbar_iso6.txt
        cpan/Pod-Simple/t/enc-chars.t
        cpan/Pod-Simple/t/encod02.t
        cpan/Pod-Simple/t/encod03.t
    );

    my %known_alien_encoding_files;
    $known_alien_encoding_files{$_} = 1 for @known_alien_encoding_files;

    my @known_utf16_files = qw(
        cpan/CPAN-Meta-YAML/t/data/utf_16_le_bom.yml
        cpan/Module-Metadata/corpus/BOMTest/UTF16BE.pm
        cpan/Module-Metadata/corpus/BOMTest/UTF16LE.pm
        cpan/Pod-Simple/t/corpus2/polish_utf16be_bom.txt
        cpan/Pod-Simple/t/corpus2/polish_utf16le_bom.txt
    );

    my %known_utf16_files;
    $known_utf16_files{$_} = 1 for @known_utf16_files;

    require './regen/charset_translations.pl';

    # Translation tables
    my @charset = grep { /$ebcdic_code_page/ } get_supported_code_pages();
    die "Unknown EBCDIC code page '$ebcdic_code_page'" unless @charset;

    my $charset = $charset[0];
    my $a2e = get_a2n($charset);

    my $LATIN1_TO_EBCDIC = "";
    $LATIN1_TO_EBCDIC .= quotemeta chr $a2e->[$_] for 0..255;

    print "Translating to EBCDIC...\n";

    open my $mani_fh, "<", "MANIFEST" or die "Can't read copied MANIFEST: $!";
    my @manifest = <$mani_fh>;  # Slurp in whole thing before the file gets
                                # trashed
    close $mani_fh or die "Couldn't close MANIFEST: $!";
    while (defined ($_ = shift @manifest)) {
        chomp;
        my $file = $_ =~ s/\s.*//r; # Rmv description to get just the file
                                    # name

        local $/; # slurp mode
        open my $fh, "+<:raw", $file or die "Can't read copied $file: $!";
        my $text = <$fh>;
        my $xlated = "";
        my $utf16_high = 0;
        my $utf16_low = 0;

        my $potential_BOM = substr($text, 0, 2);
        if ($potential_BOM eq "\xFE\xFF") {
            $utf16_high = 0;
            $utf16_low = 1;
            print STDERR "$file is UTF-16BE\n"
                                            unless $known_utf16_files{$file};
        }
        elsif ($potential_BOM eq "\xFF\xFE") {
            $utf16_high = 1;
            $utf16_low = 0;
            print STDERR "$file is UTF-16LE\n"
                                            unless $known_utf16_files{$file};
        }

        if ($utf16_high || $utf16_low) {
            my $len = length $text;
            die "Odd length in UTF-16 files: $file" if $len % 2;

            # Look 2 bytes at a time
            for (my $i = 0; $i < $len; $i+=2) {
                my $cur = substr($text, $i, 2);

                # If the code point's high byte is 0, it means the code point
                # itself is 00-FF, so want native value of it.
                if (substr($cur, $utf16_high, 1) eq "\0") {

                    # Just substitute the translated native value
                    my $low_byte = substr($cur, $utf16_low, 1);
                    $low_byte = chr $a2e->[ord $low_byte];
                    substr($cur, $utf16_low, 1) = $low_byte;
                }

                $xlated .= $cur;
            }
        }
        else {
            my $has_alien_encoding = 0;
            if ($text =~ / ^ =encoding \s+ (\S*) \s* $ /mx) {
                my $encoding = $1;
                $has_alien_encoding =
                    $encoding !~ /  ^ (?:  utf -? 8
                                         | cp -? 1252
                                         | ascii
                                         | (?: iso -? )? 8859 -? 1 \b
                                      )
                                    \b
                                /ix;

            }

            if ($has_alien_encoding) {
                print STDERR "$file has alien encoding\n"
                                    unless $known_alien_encoding_files{$file};
                close $fh or die "Couldn't close $file: $!";
                next;
            }
            elsif ($text =~ / ^ [\000-\177]* $ /x) {

                # Here, $text consists entirely of one of the 160 ASCII and
                # control characters whose EBCDIC representation is the same
                # whether UTF-EBCDIC or not.  Just translate directly
                no warnings 'misc';     # Harmless here to have replacement
                                        # string longer
                $xlated = eval "\$text =~ tr/\000-\177/$LATIN1_TO_EBCDIC/r";
                die $@ if $@;
            }
            elsif (utf8::decode($text)) {

                # Here, $text is legal UTF-8, and the representation of some
                # character(s) in it it matters if is encoded in UTF-EBCDIC or
                # not.  Also, the decode caused $text to now be viewed as
                # UTF-8 characters instead of the input bytes.  We convert to
                # UTF-EBCDIC.
                $xlated = ($text =~ s/(.)/cp_2_utfbytes(ord $1, $charset)/rsge);
            }
            elsif (! -T $file) {   # Binary files aren't translated (don't use
                                   # -B, because that accepts empty files)
                print STDERR "$file is binary\n"
                                            unless $known_binary_files{$file};
                close $fh or die "Couldn't close $file: $!";
                next;
            }
            else {

                # Here, $text isn't legal UTF-8; assume it is Latin1
                $xlated = eval "\$text =~ tr/\000-\377/$LATIN1_TO_EBCDIC/r";
                die $@ if $@;
            }
        }

        # Overwrite the file with the translation
        truncate $fh, 0;
        seek $fh, 0, 0;
        print $fh $xlated;

        close $fh or die "Couldn't close $file: $!";
    }
}

print "Setting file permissions...\n";
system("find . -type f -print     | xargs chmod 0444");
system("find . -type d -print     | xargs chmod 0755");

system("chmod +x @exe") == 0
    or die "system: $!";

# MANIFEST may be resorted, so needs to be writable
# This list of files is parsed from this source code
# by t/porting/makerel.t
my @writables = qw(
    feature.h
    lib/feature.pm
    keywords.h
    keywords.c
    MANIFEST
    opcode.h
    opnames.h
    pp_proto.h
    proto.h
    embed.h
    embedvar.h
    overload.inc
    overload.h
    mg_vtable.h
    dist/Devel-PPPort/module2.c
    dist/Devel-PPPort/module3.c
    reentr.c
    reentr.h
    regcharclass.h
    regnodes.h
    warnings.h
    lib/warnings.pm
    win32/GNUmakefile
    win32/Makefile
    win32/config_H.gc
    win32/config_H.vc
);

my $out = `chmod u+w @writables 2>&1`;
if ($? != 0) {
    warn $out;
    if ($out =~ /no such file/i) {
        warn "Check that the files above still exist in the Perl core.\n";
        warn "If not, remove them from \@writables in Porting/makerel\n";
    }
    exit 1;
}

warn $out if $out;

chdir ".." or die $!;

exit if $no_tarballs;

my $src = (-e $perl) ? $perl : 'perl'; # 'perl' in maint branch

my $tar_cmd = "tar cf - --format=ustar $reldir";

my $output_7z;
my $have_7z;
if (! $ebcdic_code_page) {

    print "Checking if you have 7z...\n";
    $output_7z = `7z 2>&1`;
    $have_7z = defined $output_7z && $output_7z =~ /7-Zip/;
}

print "Checking if you have advdef...\n";
my $output_advdef = `advdef --version 2>&1`;
my $have_advdef = defined $output_advdef && $output_advdef =~ /advancecomp/;

if ($have_7z) {
    print "Creating and compressing the tar.gz file with 7z...\n";
    $cmd = "$tar_cmd | 7z a -tgzip -mx9 -bd -si $reldir.tar.gz";
    system($cmd) == 0 or die "$cmd failed";
} else {
    print "Creating and compressing the tar.gz file...\n";
    $cmd = "$tar_cmd | gzip --best > $reldir.tar.gz";
    system($cmd) == 0 or die "$cmd failed";
    if ($have_advdef) {
        print "Recompressing the tar.gz file with advdef...\n";
        $cmd = "advdef -z -4 $reldir.tar.gz";
        system($cmd) == 0 or die "$cmd failed";
    }
}

if ($additional_xz) {
    print "Creating and compressing the tar.xz file with xz...\n";
    $cmd = "$tar_cmd | xz -z -c > $reldir.tar.xz";
    system($cmd) == 0 or die "$cmd failed";
}

print "\n";

system("ls -ld $perl*");
print "\n";

my @files = glob "'$perl*.tar.*'";
for my $file (@files) {
    my $sha = Digest::SHA->new('sha256');
    $sha->addfile($file, 'b');
    print $sha->hexdigest . "  $file\n";
}

sub cleanup {
    my ( $relroot, $reldir ) = @_;

    require File::Path;

    my @cmds = (
        [ qw{make distclean} ],
        [ qw{git clean -dxf} ],
    );

    foreach my $cmd (@cmds) {
        print join( ' ', "Running:", @$cmd, "\n" );
        system @$cmd;
        die "fail to run ".(join(' ', @$cmd) ) unless $? == 0;
    }

    if ( -d "$relroot/$reldir" ) {
        print "Removing directory $relroot/$reldir\n";
        File::Path::rmtree("$relroot/$reldir");
    }

    # always clean both
    my @files = ( "$relroot/$reldir.tar.gz", "$relroot/$reldir.tar.xz" );

    foreach my $f ( @files ) {
        next unless -f $f;
        print "Removing file '$f'\n";
        unlink($f);
    }

    return;

}

1;
