#!/usr/bin/env perl
use v5.30.0;
use warnings;
use JSON::PP;

my $file = 'Porting/core-team.json';
my $data = JSON::PP->new->decode(scalar `cat $file`);

my $pod = q{};

for my $key (qw( active inactive )) {
  $pod .= qq{=head2 \u$key Members\n\n=over 4\n\n};

  my @items = map {; "<$_>" } $data->{$key}->@*;

  open(my $fh, '-|', 'git', 'check-mailmap', @items)
    or die "error running check-mailmap: $!";

  my @lines = <$fh>;

  $pod .= "=item $_\n" for sort @lines;

  $pod .= "=back\n\n";
}

say $pod;
