=encoding utf8

=head1 Perl 5.14 release schedule

=over

=item December 20, 2010

Contentious Changes freeze

=item February 20, 2011

User-visible Changes freeze

=item March 20, 2011

Code Freeze

=item April 1, 2011

Target date for 5.14.0 RC0

=item Seven days after the release of a 5.14.0-RCx with no showstoppers reported

5.14.0

=back

=head1 Development Release schedule

This document lists the release engineers for at least the next
four months of releases of bleadperl. If there are fewer than 
four months listed as you make a release, it's important
that you extend the schedule AND B<identify the next release engineer>.

Before adding a release engineer, you B<must> contact them and they
B<must> consent to ship the release.

When shipping a release, you should include the schedule for (at least)
the next four releases. If a stable version of Perl is released,
you should reset the version numbers to the next blead series.

=head2 2009

 October 2       -   Jesse Vincent
 October 20      -   Jesse Vincent
 November 20     -   Leon Brocard
 December 20     -   Jesse Vincent

=head2 2010

 January 20      -   Ricardo Signes
 February 20     -   Steve Hay
 March 20        -   Ask Bjørn Hansen (skipped due to 5.12.0-RC1)
 April 20        -   Leon Brocard
 May 20          -   Ricardo Signes
 June 20         -   Matt Trout
 July 20         -   David Golden
 August 20       -   Florian Ragwitz
 September 20    -   Steve Hay
 October 20      -   Tatsuhiko Miyagawa
 November 20     -   Chris Williams
 December 20     -   Zefram

=head2 2011

 January 20      -   Jesse
 February 20     -   Ævar Arnfjörð Bjarmason
 March 20        -   Florian Ragwitz
 April 20        -   Jesse (5.14.0-RC0)
 May 20          -   Ricardo Signes
 June 20         -   David Golden

=head1 VICTIMS

The following porters have all consented to do at least
one release of bleadperl.  If you can't do a release
and can't find a substitute amongst this list, mail p5p.

Jesse Vincent <jesse@cpan.org>
Leon Brocard <acme@astray.com>
Yves Orton <demerphq@gmail.com>
Ricardo Signes <rjbs@cpan.org>
Steve Hay <steve.m.hay@googlemail.com>
Ask Bjørn Hansen <ask@perl.org>
David Golden <dagolden@cpan.org>
Philippe Bruhat <book@cpan.org>
Matt Trout <mst@shadowcat.co.uk>
Florian Ragwitz <rafl@debian.org>
Tatsuhiko Miyagawa <miyagawa@bulknews.net>
Chris Williams <bingos@cpan.org>
Zefram <zefram@fysh.org>
Ævar Arnfjörð Bjarmason <avar@cpan.org>


=head2 Reticent victims

These folks have said that they'd be willing to release Perl but would
prefer that others have the opportunity before they pitch in:



=head1 AUTHOR

Jesse Vincent <jesse@cpan.org>

=cut
