extraction:
  cpp:
    configure:
      command:
        - "./Configure -des -Dusedevel"
    index:
      build_command:
        - "make"
path_classifiers:
  generated:
    - charclass_invlists.h
    # These files are incorrectly classified as generated. Work around
    # this pending a fix on LGTM.com.
    - exclude: perl.c
    - exclude: op.c
