#!./perl

BEGIN {require POSIX; import POSIX; }


print POSIX::pipe(), "\n";

$sigset = new POSIX::SigSet 1,3;
delset $sigset 1;
if (ismember $sigset 1) { print "BAD\n" }
if (ismember $sigset 3) { print "GOOD\n" }
$mask = new POSIX::SigSet &SIGINT;
$action = new POSIX::SigAction 'main::SigHUP', $mask, 0;
sigaction(&SIGHUP, $action);
kill HUP, $$;
print "DONE\n";

sub SigHUP {
    print "SigHUP1\n";
    sleep 10;
    print "SigHUP2\n";
}

__END__
print &_POSIX_OPEN_MAX, "\n";

$x =  setlocale(&LC_NUMERIC, "En_TRY");
print $x,"\n";
$! = 12;

print +POSIX::errno(), "\n";
print 123.45,"\n";
__END__
$lconv = localeconv();
print %$lconv, "\n";
