/* -*- buffer-read-only: t -*-
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by regen/mk_invlists.pl from Unicode::UCD.
 * Any changes made here will be lost!
 */

/* See the generating file for comments */


#ifndef PERL_IN_XSUB_RE

static const UV Latin1_invlist[] = {
	2,	/* Number of elements */
	148565664, /* Version and data structure type */
	0,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	256
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV AboveLatin1_invlist[] = {
	2,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	256
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV ASCII_invlist[] = {
	2,	/* Number of elements */
	148565664, /* Version and data structure type */
	0,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	128
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1Cased_invlist[] = {
	17,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	65,
	91,
	97,
	123,
	170,
	171,
	181,
	182,
	186,
	187,
	192,
	215,
	216,
	247,
	248,
	443
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV VertSpace_invlist[] = {
	7,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	10,
	14,
	133,
	134,
	8232,
	8234
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PerlSpace_invlist[] = {
	5,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	9,
	14,
	32,
	33
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV XPerlSpace_invlist[] = {
	23,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	9,
	14,
	32,
	33,
	133,
	134,
	160,
	161,
	5760,
	5761,
	6158,
	6159,
	8192,
	8203,
	8232,
	8234,
	8239,
	8240,
	8287,
	8288,
	12288,
	12289
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixAlnum_invlist[] = {
	7,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	48,
	58,
	65,
	91,
	97,
	123
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1PosixAlnum_invlist[] = {
	19,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	48,
	58,
	65,
	91,
	97,
	123,
	170,
	171,
	181,
	182,
	186,
	187,
	192,
	215,
	216,
	247,
	248,
	706
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixAlpha_invlist[] = {
	5,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	65,
	91,
	97,
	123
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1PosixAlpha_invlist[] = {
	17,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	65,
	91,
	97,
	123,
	170,
	171,
	181,
	182,
	186,
	187,
	192,
	215,
	216,
	247,
	248,
	706
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixBlank_invlist[] = {
	5,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	9,
	10,
	32,
	33
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV XPosixBlank_invlist[] = {
	19,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	9,
	10,
	32,
	33,
	160,
	161,
	5760,
	5761,
	6158,
	6159,
	8192,
	8203,
	8239,
	8240,
	8287,
	8288,
	12288,
	12289
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixCntrl_invlist[] = {
	4,	/* Number of elements */
	148565664, /* Version and data structure type */
	0,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	32,
	127,
	128
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV XPosixCntrl_invlist[] = {
	4,	/* Number of elements */
	148565664, /* Version and data structure type */
	0,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	32,
	127,
	160
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixDigit_invlist[] = {
	3,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	48,
	58
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixGraph_invlist[] = {
	3,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	33,
	127
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1PosixGraph_invlist[] = {
	5,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	33,
	127,
	161,
	888
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixLower_invlist[] = {
	3,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	97,
	123
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1PosixLower_invlist[] = {
	13,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	97,
	123,
	170,
	171,
	181,
	182,
	186,
	187,
	223,
	247,
	248,
	256
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixPrint_invlist[] = {
	3,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	32,
	127
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1PosixPrint_invlist[] = {
	5,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	32,
	127,
	160,
	888
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixPunct_invlist[] = {
	9,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	33,
	48,
	58,
	65,
	91,
	97,
	123,
	127
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1PosixPunct_invlist[] = {
	21,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	33,
	48,
	58,
	65,
	91,
	97,
	123,
	127,
	161,
	162,
	167,
	168,
	171,
	172,
	182,
	184,
	187,
	188,
	191,
	192
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixSpace_invlist[] = {
	5,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	9,
	14,
	32,
	33
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV XPosixSpace_invlist[] = {
	23,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	9,
	14,
	32,
	33,
	133,
	134,
	160,
	161,
	5760,
	5761,
	6158,
	6159,
	8192,
	8203,
	8232,
	8234,
	8239,
	8240,
	8287,
	8288,
	12288,
	12289
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixUpper_invlist[] = {
	3,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	65,
	91
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1PosixUpper_invlist[] = {
	7,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	65,
	91,
	192,
	215,
	216,
	223
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixWord_invlist[] = {
	9,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	48,
	58,
	65,
	91,
	95,
	96,
	97,
	123
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV L1PosixWord_invlist[] = {
	21,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	48,
	58,
	65,
	91,
	95,
	96,
	97,
	123,
	170,
	171,
	181,
	182,
	186,
	187,
	192,
	215,
	216,
	247,
	248,
	706
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV PosixXDigit_invlist[] = {
	7,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	48,
	58,
	65,
	71,
	97,
	103
};

#endif

#ifndef PERL_IN_XSUB_RE

static const UV XPosixXDigit_invlist[] = {
	13,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	48,
	58,
	65,
	71,
	97,
	103,
	65296,
	65306,
	65313,
	65319,
	65345,
	65351
};

#endif

static const UV NonL1_Perl_Non_Final_Folds_invlist[] = {
	45,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	700,
	701,
	776,
	777,
	787,
	788,
	834,
	835,
	940,
	941,
	942,
	943,
	945,
	946,
	951,
	952,
	953,
	954,
	961,
	962,
	965,
	966,
	969,
	970,
	974,
	975,
	1381,
	1382,
	1396,
	1397,
	1406,
	1407,
	7936,
	7944,
	7968,
	7976,
	8032,
	8040,
	8048,
	8049,
	8052,
	8053,
	8060,
	8061
};

#ifndef PERL_IN_XSUB_RE

static const UV _Perl_Multi_Char_Folds_invlist[] = {
	59,	/* Number of elements */
	148565664, /* Version and data structure type */
	1,	/* 0 if the list starts at 0;
		   1 if it starts at the element beyond 0 */
	0,
	223,
	224,
	304,
	305,
	329,
	330,
	496,
	497,
	912,
	913,
	944,
	945,
	1415,
	1416,
	7830,
	7835,
	7838,
	7839,
	8016,
	8017,
	8018,
	8019,
	8020,
	8021,
	8022,
	8023,
	8064,
	8112,
	8114,
	8117,
	8118,
	8120,
	8124,
	8125,
	8130,
	8133,
	8134,
	8136,
	8140,
	8141,
	8146,
	8148,
	8150,
	8152,
	8162,
	8165,
	8166,
	8168,
	8178,
	8181,
	8182,
	8184,
	8188,
	8189,
	64256,
	64263,
	64275,
	64280
};

#endif

/* ex: set ro: */
