/* This file is derived from global.sym and interp.sym */

/* (Doing namespace management portably in C is really gross.) */

#ifdef EMBED

/* globals we need to hide from the world */
#define No		perl_No
#define Sv		perl_Sv
#define Xpv		perl_Xpv
#define Yes		perl_Yes
#define additem		perl_additem
#define an		perl_an
#define buf		perl_buf
#define bufend		perl_bufend
#define bufptr		perl_bufptr
#define check		perl_check
#define coeff		perl_coeff
#define compiling	perl_compiling
#define comppad		perl_comppad
#define comppad_name	perl_comppad_name
#define comppad_name_fill	perl_comppad_name_fill
#define cop_seqmax	perl_cop_seqmax
#define cryptseen	perl_cryptseen
#define cshlen		perl_cshlen
#define cshname		perl_cshname
#define curinterp	perl_curinterp
#define curpad		perl_curpad
#define dc		perl_dc
#define di		perl_di
#define ds		perl_ds
#define egid		perl_egid
#define error_count	perl_error_count
#define euid		perl_euid
#define evalseq		perl_evalseq
#define evstr		perl_evstr
#define expect		perl_expect
#define expectterm	perl_expectterm
#define fold		perl_fold
#define freq		perl_freq
#define gid		perl_gid
#define hexdigit	perl_hexdigit
#define hints		perl_hints
#define in_my		perl_in_my
#define know_next	perl_know_next
#define last_lop	perl_last_lop
#define last_lop_op	perl_last_lop_op
#define last_uni	perl_last_uni
#define linestr		perl_linestr
#define markstack	perl_markstack
#define markstack_max	perl_markstack_max
#define markstack_ptr	perl_markstack_ptr
#define max_intro_pending	perl_max_intro_pending
#define min_intro_pending	perl_min_intro_pending
#define multi_close	perl_multi_close
#define multi_end	perl_multi_end
#define multi_open	perl_multi_open
#define multi_start	perl_multi_start
#define na		perl_na
#define nexttype	perl_nexttype
#define nextval		perl_nextval
#define no_aelem	perl_no_aelem
#define no_dir_func	perl_no_dir_func
#define no_func		perl_no_func
#define no_helem	perl_no_helem
#define no_mem		perl_no_mem
#define no_modify	perl_no_modify
#define no_security	perl_no_security
#define no_sock_func	perl_no_sock_func
#define no_usym		perl_no_usym
#define nointrp		perl_nointrp
#define nomem		perl_nomem
#define nomemok		perl_nomemok
#define oldbufptr	perl_oldbufptr
#define oldoldbufptr	perl_oldoldbufptr
#define op		perl_op
#define op_name		perl_op_name
#define op_seqmax	perl_op_seqmax
#define opargs		perl_opargs
#define origalen	perl_origalen
#define origenviron	perl_origenviron
#define padix		perl_padix
#define patleave	perl_patleave
#define ppaddr		perl_ppaddr
#define rcsid		perl_rcsid
#define reall_srchlen	perl_reall_srchlen
#define regarglen	perl_regarglen
#define regbol		perl_regbol
#define regcode		perl_regcode
#define regdummy	perl_regdummy
#define regendp		perl_regendp
#define regeol		perl_regeol
#define regfold		perl_regfold
#define reginput	perl_reginput
#define reglastparen	perl_reglastparen
#define regmyendp	perl_regmyendp
#define regmyp_size	perl_regmyp_size
#define regmystartp	perl_regmystartp
#define regnarrate	perl_regnarrate
#define regnpar		perl_regnpar
#define regparse	perl_regparse
#define regprecomp	perl_regprecomp
#define regprev		perl_regprev
#define regsawback	perl_regsawback
#define regsawbracket	perl_regsawbracket
#define regsize		perl_regsize
#define regstartp	perl_regstartp
#define regtill		perl_regtill
#define regxend		perl_regxend
#define retstack	perl_retstack
#define retstack_ix	perl_retstack_ix
#define retstack_max	perl_retstack_max
#define rsfp		perl_rsfp
#define savestack	perl_savestack
#define savestack_ix	perl_savestack_ix
#define savestack_max	perl_savestack_max
#define saw_return	perl_saw_return
#define scopestack	perl_scopestack
#define scopestack_ix	perl_scopestack_ix
#define scopestack_max	perl_scopestack_max
#define scrgv		perl_scrgv
#define sig_name	perl_sig_name
#define simple		perl_simple
#define stack_base	perl_stack_base
#define stack_max	perl_stack_max
#define stack_sp	perl_stack_sp
#define statbuf		perl_statbuf
#define sub_generation	perl_sub_generation
#define subline		perl_subline
#define subname		perl_subname
#define sv_no		perl_sv_no
#define sv_undef	perl_sv_undef
#define sv_yes		perl_sv_yes
#define thisexpr	perl_thisexpr
#define timesbuf	perl_timesbuf
#define tokenbuf	perl_tokenbuf
#define uid		perl_uid
#define varies		perl_varies
#define vert		perl_vert
#define vtbl_arylen	perl_vtbl_arylen
#define vtbl_bm		perl_vtbl_bm
#define vtbl_dbline	perl_vtbl_dbline
#define vtbl_env	perl_vtbl_env
#define vtbl_envelem	perl_vtbl_envelem
#define vtbl_glob	perl_vtbl_glob
#define vtbl_isa	perl_vtbl_isa
#define vtbl_isaelem	perl_vtbl_isaelem
#define vtbl_mglob	perl_vtbl_mglob
#define vtbl_pack	perl_vtbl_pack
#define vtbl_packelem	perl_vtbl_packelem
#define vtbl_sig	perl_vtbl_sig
#define vtbl_sigelem	perl_vtbl_sigelem
#define vtbl_substr	perl_vtbl_substr
#define vtbl_sv		perl_vtbl_sv
#define vtbl_taint	perl_vtbl_taint
#define vtbl_uvar	perl_vtbl_uvar
#define vtbl_vec	perl_vtbl_vec
#define warn_nl		perl_warn_nl
#define warn_nosemi	perl_warn_nosemi
#define warn_reserved	perl_warn_reserved
#define watchaddr	perl_watchaddr
#define watchok		perl_watchok
#define yychar		perl_yychar
#define yycheck		perl_yycheck
#define yydebug		perl_yydebug
#define yydefred	perl_yydefred
#define yydgoto		perl_yydgoto
#define yyerrflag	perl_yyerrflag
#define yygindex	perl_yygindex
#define yylen		perl_yylen
#define yylhs		perl_yylhs
#define yylval		perl_yylval
#define yyname		perl_yyname
#define yynerrs		perl_yynerrs
#define yyrindex	perl_yyrindex
#define yyrule		perl_yyrule
#define yysindex	perl_yysindex
#define yytable		perl_yytable
#define yyval		perl_yyval
#define append_elem	perl_append_elem
#define append_list	perl_append_list
#define apply		perl_apply
#define av_clear	perl_av_clear
#define av_fake		perl_av_fake
#define av_fetch	perl_av_fetch
#define av_fill		perl_av_fill
#define av_len		perl_av_len
#define av_make		perl_av_make
#define av_pop		perl_av_pop
#define av_popnulls	perl_av_popnulls
#define av_push		perl_av_push
#define av_shift	perl_av_shift
#define av_store	perl_av_store
#define av_undef	perl_av_undef
#define av_unshift	perl_av_unshift
#define bind_match	perl_bind_match
#define block_head	perl_block_head
#define calllist	perl_calllist
#define cando		perl_cando
#define check_uni	perl_check_uni
#define checkcomma	perl_checkcomma
#define ck_aelem	perl_ck_aelem
#define ck_chop		perl_ck_chop
#define ck_concat	perl_ck_concat
#define ck_eof		perl_ck_eof
#define ck_eval		perl_ck_eval
#define ck_exec		perl_ck_exec
#define ck_formline	perl_ck_formline
#define ck_ftst		perl_ck_ftst
#define ck_fun		perl_ck_fun
#define ck_glob		perl_ck_glob
#define ck_grep		perl_ck_grep
#define ck_gvconst	perl_ck_gvconst
#define ck_index	perl_ck_index
#define ck_lengthconst	perl_ck_lengthconst
#define ck_lfun		perl_ck_lfun
#define ck_listiob	perl_ck_listiob
#define ck_match	perl_ck_match
#define ck_null		perl_ck_null
#define ck_repeat	perl_ck_repeat
#define ck_retarget	perl_ck_retarget
#define ck_rvconst	perl_ck_rvconst
#define ck_select	perl_ck_select
#define ck_shift	perl_ck_shift
#define ck_sort		perl_ck_sort
#define ck_split	perl_ck_split
#define ck_subr		perl_ck_subr
#define ck_trunc	perl_ck_trunc
#define convert		perl_convert
#define cpy7bit		perl_cpy7bit
#define cpytill		perl_cpytill
#define croak		perl_croak
#define cv_undef	perl_cv_undef
#define cxinc		perl_cxinc
#define deb		perl_deb
#define deb_growlevel	perl_deb_growlevel
#define debop		perl_debop
#define debstack	perl_debstack
#define debstackptrs	perl_debstackptrs
#define die		perl_die
#define die_where	perl_die_where
#define do_aexec	perl_do_aexec
#define do_chop		perl_do_chop
#define do_close	perl_do_close
#define do_ctl		perl_do_ctl
#define do_eof		perl_do_eof
#define do_exec		perl_do_exec
#define do_execfree	perl_do_execfree
#define do_ipcctl	perl_do_ipcctl
#define do_ipcget	perl_do_ipcget
#define do_join		perl_do_join
#define do_kv		perl_do_kv
#define do_msgrcv	perl_do_msgrcv
#define do_msgsnd	perl_do_msgsnd
#define do_open		perl_do_open
#define do_pipe		perl_do_pipe
#define do_print	perl_do_print
#define do_readline	perl_do_readline
#define do_seek		perl_do_seek
#define do_semop	perl_do_semop
#define do_shmio	perl_do_shmio
#define do_sprintf	perl_do_sprintf
#define do_tell		perl_do_tell
#define do_trans	perl_do_trans
#define do_vecset	perl_do_vecset
#define do_vop		perl_do_vop
#define doeval		perl_doeval
#define dofindlabel	perl_dofindlabel
#define dopoptoeval	perl_dopoptoeval
#define dump_all	perl_dump_all
#define dump_eval	perl_dump_eval
#define dump_gv		perl_dump_gv
#define dump_op		perl_dump_op
#define dump_packsubs	perl_dump_packsubs
#define dump_pm		perl_dump_pm
#define dump_sub	perl_dump_sub
#define fbm_compile	perl_fbm_compile
#define fbm_instr	perl_fbm_instr
#define fetch_gv	perl_fetch_gv
#define fetch_io	perl_fetch_io
#define fetch_stash	perl_fetch_stash
#define fold_constants	perl_fold_constants
#define force_ident	perl_force_ident
#define force_next	perl_force_next
#define force_word	perl_force_word
#define free_tmps	perl_free_tmps
#define gen_constant_list	perl_gen_constant_list
#define getgimme	perl_getgimme
#define gp_free		perl_gp_free
#define gp_ref		perl_gp_ref
#define gv_AVadd	perl_gv_AVadd
#define gv_HVadd	perl_gv_HVadd
#define gv_check	perl_gv_check
#define gv_efullname	perl_gv_efullname
#define gv_fetchfile	perl_gv_fetchfile
#define gv_fetchmeth	perl_gv_fetchmeth
#define gv_fetchmethod	perl_gv_fetchmethod
#define gv_fetchpv	perl_gv_fetchpv
#define gv_fullname	perl_gv_fullname
#define gv_init		perl_gv_init
#define he_delayfree	perl_he_delayfree
#define he_free		perl_he_free
#define hint		perl_hint
#define hoistmust	perl_hoistmust
#define hv_clear	perl_hv_clear
#define hv_delete	perl_hv_delete
#define hv_fetch	perl_hv_fetch
#define hv_iterinit	perl_hv_iterinit
#define hv_iterkey	perl_hv_iterkey
#define hv_iternext	perl_hv_iternext
#define hv_iterval	perl_hv_iterval
#define hv_magic	perl_hv_magic
#define hv_store	perl_hv_store
#define hv_undef	perl_hv_undef
#define ibcmp		perl_ibcmp
#define ingroup		perl_ingroup
#define instr		perl_instr
#define intuit_more	perl_intuit_more
#define invert		perl_invert
#define jmaybe		perl_jmaybe
#define keyword		perl_keyword
#define leave_scope	perl_leave_scope
#define lex_end		perl_lex_end
#define lex_start	perl_lex_start
#define linklist	perl_linklist
#define list		perl_list
#define listkids	perl_listkids
#define localize	perl_localize
#define looks_like_number	perl_looks_like_number
#define magic_clearpack	perl_magic_clearpack
#define magic_get	perl_magic_get
#define magic_getarylen	perl_magic_getarylen
#define magic_getglob	perl_magic_getglob
#define magic_getpack	perl_magic_getpack
#define magic_gettaint	perl_magic_gettaint
#define magic_getuvar	perl_magic_getuvar
#define magic_len	perl_magic_len
#define magic_nextpack	perl_magic_nextpack
#define magic_set	perl_magic_set
#define magic_setarylen	perl_magic_setarylen
#define magic_setbm	perl_magic_setbm
#define magic_setdbline	perl_magic_setdbline
#define magic_setenv	perl_magic_setenv
#define magic_setglob	perl_magic_setglob
#define magic_setisa	perl_magic_setisa
#define magic_setmglob	perl_magic_setmglob
#define magic_setpack	perl_magic_setpack
#define magic_setsig	perl_magic_setsig
#define magic_setsubstr	perl_magic_setsubstr
#define magic_settaint	perl_magic_settaint
#define magic_setuvar	perl_magic_setuvar
#define magic_setvec	perl_magic_setvec
#define magicname	perl_magicname
#define mess		perl_mess
#define mg_clear	perl_mg_clear
#define mg_copy		perl_mg_copy
#define mg_find		perl_mg_find
#define mg_free		perl_mg_free
#define mg_get		perl_mg_get
#define mg_len		perl_mg_len
#define mg_magical	perl_mg_magical
#define mg_set		perl_mg_set
#define mod		perl_mod
#define modkids		perl_modkids
#define moreswitches	perl_moreswitches
#define my		perl_my
#define my_exit		perl_my_exit
#define my_lstat	perl_my_lstat
#define my_pclose	perl_my_pclose
#define my_popen	perl_my_popen
#define my_setenv	perl_my_setenv
#define my_stat		perl_my_stat
#define my_unexec	perl_my_unexec
#define newANONHASH	perl_newANONHASH
#define newANONLIST	perl_newANONLIST
#define newASSIGNOP	perl_newASSIGNOP
#define newAV		perl_newAV
#define newAVREF	perl_newAVREF
#define newBINOP	perl_newBINOP
#define newCONDOP	perl_newCONDOP
#define newCVOP		perl_newCVOP
#define newCVREF	perl_newCVREF
#define newFORM		perl_newFORM
#define newFOROP	perl_newFOROP
#define newGVOP		perl_newGVOP
#define newGVREF	perl_newGVREF
#define newGVgen	perl_newGVgen
#define newHV		perl_newHV
#define newHVREF	perl_newHVREF
#define newIO		perl_newIO
#define newLISTOP	perl_newLISTOP
#define newLOGOP	perl_newLOGOP
#define newLOOPEX	perl_newLOOPEX
#define newLOOPOP	perl_newLOOPOP
#define newMETHOD	perl_newMETHOD
#define newNULLLIST	perl_newNULLLIST
#define newOP		perl_newOP
#define newPMOP		perl_newPMOP
#define newPVOP		perl_newPVOP
#define newRANGE	perl_newRANGE
#define newSLICEOP	perl_newSLICEOP
#define newSTATEOP	perl_newSTATEOP
#define newSUB		perl_newSUB
#define newSV		perl_newSV
#define newSVOP		perl_newSVOP
#define newSVREF	perl_newSVREF
#define newSViv		perl_newSViv
#define newSVnv		perl_newSVnv
#define newSVpv		perl_newSVpv
#define newSVsv		perl_newSVsv
#define newUNOP		perl_newUNOP
#define newWHILEOP	perl_newWHILEOP
#define newXSUB		perl_newXSUB
#define nextargv	perl_nextargv
#define ninstr		perl_ninstr
#define no_fh_allowed	perl_no_fh_allowed
#define no_op		perl_no_op
#define nsavestr	perl_nsavestr
#define oopsAV		perl_oopsAV
#define oopsCV		perl_oopsCV
#define oopsHV		perl_oopsHV
#define op_free		perl_op_free
#define package		perl_package
#define pad_alloc	perl_pad_alloc
#define pad_allocmy	perl_pad_allocmy
#define pad_findmy	perl_pad_findmy
#define pad_free	perl_pad_free
#define pad_leavemy	perl_pad_leavemy
#define pad_reset	perl_pad_reset
#define pad_sv		perl_pad_sv
#define pad_swipe	perl_pad_swipe
#define peep		perl_peep
#define pidgone		perl_pidgone
#define pmruntime	perl_pmruntime
#define pmtrans		perl_pmtrans
#define pop_return	perl_pop_return
#define pop_scope	perl_pop_scope
#define pp_aassign	perl_pp_aassign
#define pp_accept	perl_pp_accept
#define pp_add		perl_pp_add
#define pp_aelem	perl_pp_aelem
#define pp_aelemfast	perl_pp_aelemfast
#define pp_alarm	perl_pp_alarm
#define pp_and		perl_pp_and
#define pp_andassign	perl_pp_andassign
#define pp_anonhash	perl_pp_anonhash
#define pp_anonlist	perl_pp_anonlist
#define pp_aslice	perl_pp_aslice
#define pp_atan2	perl_pp_atan2
#define pp_av2arylen	perl_pp_av2arylen
#define pp_backtick	perl_pp_backtick
#define pp_bind		perl_pp_bind
#define pp_binmode	perl_pp_binmode
#define pp_bit_and	perl_pp_bit_and
#define pp_bit_or	perl_pp_bit_or
#define pp_bless	perl_pp_bless
#define pp_caller	perl_pp_caller
#define pp_chdir	perl_pp_chdir
#define pp_chmod	perl_pp_chmod
#define pp_chop		perl_pp_chop
#define pp_chown	perl_pp_chown
#define pp_chroot	perl_pp_chroot
#define pp_close	perl_pp_close
#define pp_closedir	perl_pp_closedir
#define pp_complement	perl_pp_complement
#define pp_concat	perl_pp_concat
#define pp_cond_expr	perl_pp_cond_expr
#define pp_connect	perl_pp_connect
#define pp_const	perl_pp_const
#define pp_cos		perl_pp_cos
#define pp_crypt	perl_pp_crypt
#define pp_cswitch	perl_pp_cswitch
#define pp_dbmclose	perl_pp_dbmclose
#define pp_dbmopen	perl_pp_dbmopen
#define pp_dbstate	perl_pp_dbstate
#define pp_defined	perl_pp_defined
#define pp_delete	perl_pp_delete
#define pp_die		perl_pp_die
#define pp_divide	perl_pp_divide
#define pp_dofile	perl_pp_dofile
#define pp_done		perl_pp_done
#define pp_dump		perl_pp_dump
#define pp_each		perl_pp_each
#define pp_egrent	perl_pp_egrent
#define pp_ehostent	perl_pp_ehostent
#define pp_enetent	perl_pp_enetent
#define pp_enter	perl_pp_enter
#define pp_entereval	perl_pp_entereval
#define pp_enteriter	perl_pp_enteriter
#define pp_enterloop	perl_pp_enterloop
#define pp_entersubr	perl_pp_entersubr
#define pp_entertry	perl_pp_entertry
#define pp_enterwrite	perl_pp_enterwrite
#define pp_eof		perl_pp_eof
#define pp_eprotoent	perl_pp_eprotoent
#define pp_epwent	perl_pp_epwent
#define pp_eq		perl_pp_eq
#define pp_eservent	perl_pp_eservent
#define pp_evalonce	perl_pp_evalonce
#define pp_exec		perl_pp_exec
#define pp_exit		perl_pp_exit
#define pp_exp		perl_pp_exp
#define pp_fcntl	perl_pp_fcntl
#define pp_fileno	perl_pp_fileno
#define pp_flip		perl_pp_flip
#define pp_flock	perl_pp_flock
#define pp_flop		perl_pp_flop
#define pp_fork		perl_pp_fork
#define pp_formline	perl_pp_formline
#define pp_ftatime	perl_pp_ftatime
#define pp_ftbinary	perl_pp_ftbinary
#define pp_ftblk	perl_pp_ftblk
#define pp_ftchr	perl_pp_ftchr
#define pp_ftctime	perl_pp_ftctime
#define pp_ftdir	perl_pp_ftdir
#define pp_fteexec	perl_pp_fteexec
#define pp_fteowned	perl_pp_fteowned
#define pp_fteread	perl_pp_fteread
#define pp_ftewrite	perl_pp_ftewrite
#define pp_ftfile	perl_pp_ftfile
#define pp_ftis		perl_pp_ftis
#define pp_ftlink	perl_pp_ftlink
#define pp_ftmtime	perl_pp_ftmtime
#define pp_ftpipe	perl_pp_ftpipe
#define pp_ftrexec	perl_pp_ftrexec
#define pp_ftrowned	perl_pp_ftrowned
#define pp_ftrread	perl_pp_ftrread
#define pp_ftrwrite	perl_pp_ftrwrite
#define pp_ftsgid	perl_pp_ftsgid
#define pp_ftsize	perl_pp_ftsize
#define pp_ftsock	perl_pp_ftsock
#define pp_ftsuid	perl_pp_ftsuid
#define pp_ftsvtx	perl_pp_ftsvtx
#define pp_fttext	perl_pp_fttext
#define pp_fttty	perl_pp_fttty
#define pp_ftzero	perl_pp_ftzero
#define pp_ge		perl_pp_ge
#define pp_getc		perl_pp_getc
#define pp_getlogin	perl_pp_getlogin
#define pp_getpeername	perl_pp_getpeername
#define pp_getpgrp	perl_pp_getpgrp
#define pp_getppid	perl_pp_getppid
#define pp_getpriority	perl_pp_getpriority
#define pp_getsockname	perl_pp_getsockname
#define pp_ggrent	perl_pp_ggrent
#define pp_ggrgid	perl_pp_ggrgid
#define pp_ggrnam	perl_pp_ggrnam
#define pp_ghbyaddr	perl_pp_ghbyaddr
#define pp_ghbyname	perl_pp_ghbyname
#define pp_ghostent	perl_pp_ghostent
#define pp_glob		perl_pp_glob
#define pp_gmtime	perl_pp_gmtime
#define pp_gnbyaddr	perl_pp_gnbyaddr
#define pp_gnbyname	perl_pp_gnbyname
#define pp_gnetent	perl_pp_gnetent
#define pp_goto		perl_pp_goto
#define pp_gpbyname	perl_pp_gpbyname
#define pp_gpbynumber	perl_pp_gpbynumber
#define pp_gprotoent	perl_pp_gprotoent
#define pp_gpwent	perl_pp_gpwent
#define pp_gpwnam	perl_pp_gpwnam
#define pp_gpwuid	perl_pp_gpwuid
#define pp_grepstart	perl_pp_grepstart
#define pp_grepwhile	perl_pp_grepwhile
#define pp_gsbyname	perl_pp_gsbyname
#define pp_gsbyport	perl_pp_gsbyport
#define pp_gservent	perl_pp_gservent
#define pp_gsockopt	perl_pp_gsockopt
#define pp_gt		perl_pp_gt
#define pp_gv		perl_pp_gv
#define pp_gvsv		perl_pp_gvsv
#define pp_helem	perl_pp_helem
#define pp_hex		perl_pp_hex
#define pp_hslice	perl_pp_hslice
#define pp_index	perl_pp_index
#define pp_indread	perl_pp_indread
#define pp_int		perl_pp_int
#define pp_interp	perl_pp_interp
#define pp_ioctl	perl_pp_ioctl
#define pp_iter		perl_pp_iter
#define pp_join		perl_pp_join
#define pp_keys		perl_pp_keys
#define pp_kill		perl_pp_kill
#define pp_last		perl_pp_last
#define pp_lc		perl_pp_lc
#define pp_lcfirst	perl_pp_lcfirst
#define pp_le		perl_pp_le
#define pp_leave	perl_pp_leave
#define pp_leaveeval	perl_pp_leaveeval
#define pp_leaveloop	perl_pp_leaveloop
#define pp_leavesubr	perl_pp_leavesubr
#define pp_leavetry	perl_pp_leavetry
#define pp_leavewrite	perl_pp_leavewrite
#define pp_left_shift	perl_pp_left_shift
#define pp_length	perl_pp_length
#define pp_lineseq	perl_pp_lineseq
#define pp_link		perl_pp_link
#define pp_list		perl_pp_list
#define pp_listen	perl_pp_listen
#define pp_localtime	perl_pp_localtime
#define pp_log		perl_pp_log
#define pp_lslice	perl_pp_lslice
#define pp_lstat	perl_pp_lstat
#define pp_lt		perl_pp_lt
#define pp_match	perl_pp_match
#define pp_method	perl_pp_method
#define pp_mkdir	perl_pp_mkdir
#define pp_modulo	perl_pp_modulo
#define pp_msgctl	perl_pp_msgctl
#define pp_msgget	perl_pp_msgget
#define pp_msgrcv	perl_pp_msgrcv
#define pp_msgsnd	perl_pp_msgsnd
#define pp_multiply	perl_pp_multiply
#define pp_ncmp		perl_pp_ncmp
#define pp_ne		perl_pp_ne
#define pp_negate	perl_pp_negate
#define pp_next		perl_pp_next
#define pp_nextstate	perl_pp_nextstate
#define pp_not		perl_pp_not
#define pp_nswitch	perl_pp_nswitch
#define pp_null		perl_pp_null
#define pp_oct		perl_pp_oct
#define pp_open		perl_pp_open
#define pp_open_dir	perl_pp_open_dir
#define pp_or		perl_pp_or
#define pp_orassign	perl_pp_orassign
#define pp_ord		perl_pp_ord
#define pp_pack		perl_pp_pack
#define pp_padav	perl_pp_padav
#define pp_padhv	perl_pp_padhv
#define pp_padsv	perl_pp_padsv
#define pp_pipe_op	perl_pp_pipe_op
#define pp_pop		perl_pp_pop
#define pp_postdec	perl_pp_postdec
#define pp_postinc	perl_pp_postinc
#define pp_pow		perl_pp_pow
#define pp_predec	perl_pp_predec
#define pp_preinc	perl_pp_preinc
#define pp_print	perl_pp_print
#define pp_prtf		perl_pp_prtf
#define pp_push		perl_pp_push
#define pp_pushmark	perl_pp_pushmark
#define pp_pushre	perl_pp_pushre
#define pp_rand		perl_pp_rand
#define pp_range	perl_pp_range
#define pp_rcatline	perl_pp_rcatline
#define pp_read		perl_pp_read
#define pp_readdir	perl_pp_readdir
#define pp_readline	perl_pp_readline
#define pp_readlink	perl_pp_readlink
#define pp_recv		perl_pp_recv
#define pp_redo		perl_pp_redo
#define pp_ref		perl_pp_ref
#define pp_refgen	perl_pp_refgen
#define pp_regcmaybe	perl_pp_regcmaybe
#define pp_regcomp	perl_pp_regcomp
#define pp_rename	perl_pp_rename
#define pp_repeat	perl_pp_repeat
#define pp_require	perl_pp_require
#define pp_reset	perl_pp_reset
#define pp_return	perl_pp_return
#define pp_reverse	perl_pp_reverse
#define pp_rewinddir	perl_pp_rewinddir
#define pp_right_shift	perl_pp_right_shift
#define pp_rindex	perl_pp_rindex
#define pp_rmdir	perl_pp_rmdir
#define pp_rv2av	perl_pp_rv2av
#define pp_rv2cv	perl_pp_rv2cv
#define pp_rv2gv	perl_pp_rv2gv
#define pp_rv2hv	perl_pp_rv2hv
#define pp_rv2sv	perl_pp_rv2sv
#define pp_sassign	perl_pp_sassign
#define pp_scalar	perl_pp_scalar
#define pp_schop	perl_pp_schop
#define pp_scmp		perl_pp_scmp
#define pp_scope	perl_pp_scope
#define pp_seek		perl_pp_seek
#define pp_seekdir	perl_pp_seekdir
#define pp_select	perl_pp_select
#define pp_semctl	perl_pp_semctl
#define pp_semget	perl_pp_semget
#define pp_semop	perl_pp_semop
#define pp_send		perl_pp_send
#define pp_seq		perl_pp_seq
#define pp_setpgrp	perl_pp_setpgrp
#define pp_setpriority	perl_pp_setpriority
#define pp_sge		perl_pp_sge
#define pp_sgrent	perl_pp_sgrent
#define pp_sgt		perl_pp_sgt
#define pp_shift	perl_pp_shift
#define pp_shmctl	perl_pp_shmctl
#define pp_shmget	perl_pp_shmget
#define pp_shmread	perl_pp_shmread
#define pp_shmwrite	perl_pp_shmwrite
#define pp_shostent	perl_pp_shostent
#define pp_shutdown	perl_pp_shutdown
#define pp_sin		perl_pp_sin
#define pp_sle		perl_pp_sle
#define pp_sleep	perl_pp_sleep
#define pp_slt		perl_pp_slt
#define pp_sne		perl_pp_sne
#define pp_snetent	perl_pp_snetent
#define pp_socket	perl_pp_socket
#define pp_sockpair	perl_pp_sockpair
#define pp_sort		perl_pp_sort
#define pp_splice	perl_pp_splice
#define pp_split	perl_pp_split
#define pp_sprintf	perl_pp_sprintf
#define pp_sprotoent	perl_pp_sprotoent
#define pp_spwent	perl_pp_spwent
#define pp_sqrt		perl_pp_sqrt
#define pp_srand	perl_pp_srand
#define pp_sselect	perl_pp_sselect
#define pp_sservent	perl_pp_sservent
#define pp_ssockopt	perl_pp_ssockopt
#define pp_stat		perl_pp_stat
#define pp_stub		perl_pp_stub
#define pp_study	perl_pp_study
#define pp_subst	perl_pp_subst
#define pp_substcont	perl_pp_substcont
#define pp_substr	perl_pp_substr
#define pp_subtract	perl_pp_subtract
#define pp_sv2len	perl_pp_sv2len
#define pp_symlink	perl_pp_symlink
#define pp_syscall	perl_pp_syscall
#define pp_sysread	perl_pp_sysread
#define pp_system	perl_pp_system
#define pp_syswrite	perl_pp_syswrite
#define pp_tell		perl_pp_tell
#define pp_telldir	perl_pp_telldir
#define pp_tie		perl_pp_tie
#define pp_time		perl_pp_time
#define pp_tms		perl_pp_tms
#define pp_trans	perl_pp_trans
#define pp_truncate	perl_pp_truncate
#define pp_uc		perl_pp_uc
#define pp_ucfirst	perl_pp_ucfirst
#define pp_umask	perl_pp_umask
#define pp_undef	perl_pp_undef
#define pp_unlink	perl_pp_unlink
#define pp_unpack	perl_pp_unpack
#define pp_unshift	perl_pp_unshift
#define pp_unstack	perl_pp_unstack
#define pp_untie	perl_pp_untie
#define pp_utime	perl_pp_utime
#define pp_values	perl_pp_values
#define pp_vec		perl_pp_vec
#define pp_wait		perl_pp_wait
#define pp_waitpid	perl_pp_waitpid
#define pp_wantarray	perl_pp_wantarray
#define pp_warn		perl_pp_warn
#define pp_xor		perl_pp_xor
#define prepend_elem	perl_prepend_elem
#define push_return	perl_push_return
#define push_scope	perl_push_scope
#define q		perl_q
#define ref		perl_ref
#define refkids		perl_refkids
#define regcomp		perl_regcomp
#define regdump		perl_regdump
#define regexec		perl_regexec
#define regfree		perl_regfree
#define regnext		perl_regnext
#define regprop		perl_regprop
#define repeatcpy	perl_repeatcpy
#define rninstr		perl_rninstr
#define run		perl_run
#define save_I32	perl_save_I32
#define save_aptr	perl_save_aptr
#define save_ary	perl_save_ary
#define save_clearsv	perl_save_clearsv
#define save_delete	perl_save_delete
#define save_freeop	perl_save_freeop
#define save_freepv	perl_save_freepv
#define save_freesv	perl_save_freesv
#define save_hash	perl_save_hash
#define save_hptr	perl_save_hptr
#define save_int	perl_save_int
#define save_item	perl_save_item
#define save_list	perl_save_list
#define save_nogv	perl_save_nogv
#define save_scalar	perl_save_scalar
#define save_sptr	perl_save_sptr
#define save_svref	perl_save_svref
#define savestack_grow	perl_savestack_grow
#define savestr		perl_savestr
#define sawparens	perl_sawparens
#define scalar		perl_scalar
#define scalarkids	perl_scalarkids
#define scalarseq	perl_scalarseq
#define scalarvoid	perl_scalarvoid
#define scan_const	perl_scan_const
#define scan_formline	perl_scan_formline
#define scan_heredoc	perl_scan_heredoc
#define scan_hex	perl_scan_hex
#define scan_ident	perl_scan_ident
#define scan_inputsymbol	perl_scan_inputsymbol
#define scan_num	perl_scan_num
#define scan_oct	perl_scan_oct
#define scan_pat	perl_scan_pat
#define scan_prefix	perl_scan_prefix
#define scan_str	perl_scan_str
#define scan_subst	perl_scan_subst
#define scan_trans	perl_scan_trans
#define scan_word	perl_scan_word
#define scope		perl_scope
#define screaminstr	perl_screaminstr
#define setenv_getix	perl_setenv_getix
#define skipspace	perl_skipspace
#define start_subparse	perl_start_subparse
#define sublex_done	perl_sublex_done
#define sublex_start	perl_sublex_start
#define sv_2bool	perl_sv_2bool
#define sv_2cv		perl_sv_2cv
#define sv_2iv		perl_sv_2iv
#define sv_2mortal	perl_sv_2mortal
#define sv_2nv		perl_sv_2nv
#define sv_2pv		perl_sv_2pv
#define sv_backoff	perl_sv_backoff
#define sv_catpv	perl_sv_catpv
#define sv_catpvn	perl_sv_catpvn
#define sv_catsv	perl_sv_catsv
#define sv_chop		perl_sv_chop
#define sv_clean_all	perl_sv_clean_all
#define sv_clean_magic	perl_sv_clean_magic
#define sv_clean_refs	perl_sv_clean_refs
#define sv_clear	perl_sv_clear
#define sv_cmp		perl_sv_cmp
#define sv_dec		perl_sv_dec
#define sv_dump		perl_sv_dump
#define sv_eq		perl_sv_eq
#define sv_free		perl_sv_free
#define sv_gets		perl_sv_gets
#define sv_grow		perl_sv_grow
#define sv_inc		perl_sv_inc
#define sv_insert	perl_sv_insert
#define sv_isa		perl_sv_isa
#define sv_len		perl_sv_len
#define sv_magic	perl_sv_magic
#define sv_mortalcopy	perl_sv_mortalcopy
#define sv_newmortal	perl_sv_newmortal
#define sv_peek		perl_sv_peek
#define sv_ref		perl_sv_ref
#define sv_replace	perl_sv_replace
#define sv_report_used	perl_sv_report_used
#define sv_reset	perl_sv_reset
#define sv_setiv	perl_sv_setiv
#define sv_setnv	perl_sv_setnv
#define sv_setptrobj	perl_sv_setptrobj
#define sv_setpv	perl_sv_setpv
#define sv_setpvn	perl_sv_setpvn
#define sv_setsv	perl_sv_setsv
#define sv_unmagic	perl_sv_unmagic
#define sv_upgrade	perl_sv_upgrade
#define sv_usepvn	perl_sv_usepvn
#define taint_env	perl_taint_env
#define taint_not	perl_taint_not
#define taint_proper	perl_taint_proper
#define too_few_arguments	perl_too_few_arguments
#define too_many_arguments	perl_too_many_arguments
#define wait4pid	perl_wait4pid
#define warn		perl_warn
#define watch		perl_watch
#define whichsig	perl_whichsig
#define xiv_root	perl_xiv_root
#define xnv_root	perl_xnv_root
#define xpv_root	perl_xpv_root
#define xrv_root	perl_xrv_root
#define yyerror		perl_yyerror
#define yyerror		perl_yyerror
#define yylex		perl_yylex
#define yyparse		perl_yyparse
#define yywarn		perl_yywarn

#endif /* EMBED */

/* Put interpreter specific symbols into a struct? */

#ifdef MULTIPLICITY

#define Argv		(curinterp->IArgv)
#define Cmd		(curinterp->ICmd)
#define DBgv		(curinterp->IDBgv)
#define DBline		(curinterp->IDBline)
#define DBsignal	(curinterp->IDBsignal)
#define DBsingle	(curinterp->IDBsingle)
#define DBsub		(curinterp->IDBsub)
#define DBtrace		(curinterp->IDBtrace)
#define allgvs		(curinterp->Iallgvs)
#define ampergv		(curinterp->Iampergv)
#define argvgv		(curinterp->Iargvgv)
#define argvoutgv	(curinterp->Iargvoutgv)
#define arybase		(curinterp->Iarybase)
#define basetime	(curinterp->Ibasetime)
#define beginav		(curinterp->Ibeginav)
#define bodytarget	(curinterp->Ibodytarget)
#define cddir		(curinterp->Icddir)
#define chopset		(curinterp->Ichopset)
#define copline		(curinterp->Icopline)
#define curblock	(curinterp->Icurblock)
#define curcop		(curinterp->Icurcop)
#define curcsv		(curinterp->Icurcsv)
#define curoutgv	(curinterp->Icuroutgv)
#define curpm		(curinterp->Icurpm)
#define curstash	(curinterp->Icurstash)
#define curstname	(curinterp->Icurstname)
#define cxstack		(curinterp->Icxstack)
#define cxstack_ix	(curinterp->Icxstack_ix)
#define cxstack_max	(curinterp->Icxstack_max)
#define dbargs		(curinterp->Idbargs)
#define debdelim	(curinterp->Idebdelim)
#define debname		(curinterp->Idebname)
#define debstash	(curinterp->Idebstash)
#define debug		(curinterp->Idebug)
#define defgv		(curinterp->Idefgv)
#define defoutgv	(curinterp->Idefoutgv)
#define defstash	(curinterp->Idefstash)
#define delaymagic	(curinterp->Idelaymagic)
#define dirty		(curinterp->Idirty)
#define dlevel		(curinterp->Idlevel)
#define dlmax		(curinterp->Idlmax)
#define do_undump	(curinterp->Ido_undump)
#define doextract	(curinterp->Idoextract)
#define doswitches	(curinterp->Idoswitches)
#define dowarn		(curinterp->Idowarn)
#define dumplvl		(curinterp->Idumplvl)
#define e_fp		(curinterp->Ie_fp)
#define e_tmpname	(curinterp->Ie_tmpname)
#define endav		(curinterp->Iendav)
#define envgv		(curinterp->Ienvgv)
#define eval_root	(curinterp->Ieval_root)
#define eval_start	(curinterp->Ieval_start)
#define fdpid		(curinterp->Ifdpid)
#define filemode	(curinterp->Ifilemode)
#define firstgv		(curinterp->Ifirstgv)
#define forkprocess	(curinterp->Iforkprocess)
#define formfeed	(curinterp->Iformfeed)
#define formtarget	(curinterp->Iformtarget)
#define gensym		(curinterp->Igensym)
#define in_eval		(curinterp->Iin_eval)
#define incgv		(curinterp->Iincgv)
#define inplace		(curinterp->Iinplace)
#define last_in_gv	(curinterp->Ilast_in_gv)
#define lastfd		(curinterp->Ilastfd)
#define lastretstr	(curinterp->Ilastretstr)
#define lastscream	(curinterp->Ilastscream)
#define lastsize	(curinterp->Ilastsize)
#define lastspbase	(curinterp->Ilastspbase)
#define laststatval	(curinterp->Ilaststatval)
#define laststype	(curinterp->Ilaststype)
#define leftgv		(curinterp->Ileftgv)
#define lineary		(curinterp->Ilineary)
#define localizing	(curinterp->Ilocalizing)
#define main_root	(curinterp->Imain_root)
#define main_start	(curinterp->Imain_start)
#define mainstack	(curinterp->Imainstack)
#define maxscream	(curinterp->Imaxscream)
#define maxsysfd	(curinterp->Imaxsysfd)
#define minus_F		(curinterp->Iminus_F)
#define minus_a		(curinterp->Iminus_a)
#define minus_c		(curinterp->Iminus_c)
#define minus_l		(curinterp->Iminus_l)
#define minus_n		(curinterp->Iminus_n)
#define minus_p		(curinterp->Iminus_p)
#define multiline	(curinterp->Imultiline)
#define mystack_base	(curinterp->Imystack_base)
#define mystack_mark	(curinterp->Imystack_mark)
#define mystack_max	(curinterp->Imystack_max)
#define mystack_sp	(curinterp->Imystack_sp)
#define mystrk		(curinterp->Imystrk)
#define nrs		(curinterp->Inrs)
#define nrschar		(curinterp->Inrschar)
#define nrslen		(curinterp->Inrslen)
#define ofmt		(curinterp->Iofmt)
#define ofs		(curinterp->Iofs)
#define ofslen		(curinterp->Iofslen)
#define oldlastpm	(curinterp->Ioldlastpm)
#define oldname		(curinterp->Ioldname)
#define origargc	(curinterp->Iorigargc)
#define origargv	(curinterp->Iorigargv)
#define origfilename	(curinterp->Iorigfilename)
#define ors		(curinterp->Iors)
#define orslen		(curinterp->Iorslen)
#define pad		(curinterp->Ipad)
#define padname		(curinterp->Ipadname)
#define patchlevel	(curinterp->Ipatchlevel)
#define perldb		(curinterp->Iperldb)
#define pidstatus	(curinterp->Ipidstatus)
#define preambled	(curinterp->Ipreambled)
#define preprocess	(curinterp->Ipreprocess)
#define restartop	(curinterp->Irestartop)
#define rightgv		(curinterp->Irightgv)
#define rs		(curinterp->Irs)
#define rschar		(curinterp->Irschar)
#define rslen		(curinterp->Irslen)
#define rspara		(curinterp->Irspara)
#define sawampersand	(curinterp->Isawampersand)
#define sawi		(curinterp->Isawi)
#define sawstudy	(curinterp->Isawstudy)
#define sawvec		(curinterp->Isawvec)
#define screamfirst	(curinterp->Iscreamfirst)
#define screamnext	(curinterp->Iscreamnext)
#define secondgv	(curinterp->Isecondgv)
#define siggv		(curinterp->Isiggv)
#define signalstack	(curinterp->Isignalstack)
#define sortcop		(curinterp->Isortcop)
#define sortstack	(curinterp->Isortstack)
#define sortstash	(curinterp->Isortstash)
#define splitstr	(curinterp->Isplitstr)
#define stack		(curinterp->Istack)
#define statcache	(curinterp->Istatcache)
#define statgv		(curinterp->Istatgv)
#define statname	(curinterp->Istatname)
#define statusvalue	(curinterp->Istatusvalue)
#define stdingv		(curinterp->Istdingv)
#define strchop		(curinterp->Istrchop)
#define sv_count	(curinterp->Isv_count)
#define sv_rvcount	(curinterp->Isv_rvcount)
#define sv_root		(curinterp->Isv_root)
#define sv_arenaroot	(curinterp->Isv_arenaroot)
#define tainted		(curinterp->Itainted)
#define tainting	(curinterp->Itainting)
#define tmps_floor	(curinterp->Itmps_floor)
#define tmps_ix		(curinterp->Itmps_ix)
#define tmps_max	(curinterp->Itmps_max)
#define tmps_stack	(curinterp->Itmps_stack)
#define top_env		(curinterp->Itop_env)
#define toptarget	(curinterp->Itoptarget)
#define unsafe		(curinterp->Iunsafe)

#else	/* not multiple, so translate interpreter symbols the other way... */

#define IArgv		Argv
#define ICmd		Cmd
#define IDBgv		DBgv
#define IDBline		DBline
#define IDBsignal	DBsignal
#define IDBsingle	DBsingle
#define IDBsub		DBsub
#define IDBtrace	DBtrace
#define Iallgvs		allgvs
#define Iampergv	ampergv
#define Iargvgv		argvgv
#define Iargvoutgv	argvoutgv
#define Iarybase	arybase
#define Ibasetime	basetime
#define Ibeginav	beginav
#define Ibodytarget	bodytarget
#define Icddir		cddir
#define Ichopset	chopset
#define Icopline	copline
#define Icurblock	curblock
#define Icurcop		curcop
#define Icurcsv		curcsv
#define Icuroutgv	curoutgv
#define Icurpm		curpm
#define Icurstash	curstash
#define Icurstname	curstname
#define Icxstack	cxstack
#define Icxstack_ix	cxstack_ix
#define Icxstack_max	cxstack_max
#define Idbargs		dbargs
#define Idebdelim	debdelim
#define Idebname	debname
#define Idebstash	debstash
#define Idebug		debug
#define Idefgv		defgv
#define Idefoutgv	defoutgv
#define Idefstash	defstash
#define Idelaymagic	delaymagic
#define Idirty		dirty
#define Idlevel		dlevel
#define Idlmax		dlmax
#define Ido_undump	do_undump
#define Idoextract	doextract
#define Idoswitches	doswitches
#define Idowarn		dowarn
#define Idumplvl	dumplvl
#define Ie_fp		e_fp
#define Ie_tmpname	e_tmpname
#define Iendav		endav
#define Ienvgv		envgv
#define Ieval_root	eval_root
#define Ieval_start	eval_start
#define Ifdpid		fdpid
#define Ifilemode	filemode
#define Ifirstgv	firstgv
#define Iforkprocess	forkprocess
#define Iformfeed	formfeed
#define Iformtarget	formtarget
#define Igensym		gensym
#define Iin_eval	in_eval
#define Iincgv		incgv
#define Iinplace	inplace
#define Ilast_in_gv	last_in_gv
#define Ilastfd		lastfd
#define Ilastretstr	lastretstr
#define Ilastscream	lastscream
#define Ilastsize	lastsize
#define Ilastspbase	lastspbase
#define Ilaststatval	laststatval
#define Ilaststype	laststype
#define Ileftgv		leftgv
#define Ilineary	lineary
#define Ilocalizing	localizing
#define Imain_root	main_root
#define Imain_start	main_start
#define Imainstack	mainstack
#define Imaxscream	maxscream
#define Imaxsysfd	maxsysfd
#define Iminus_F	minus_F
#define Iminus_a	minus_a
#define Iminus_c	minus_c
#define Iminus_l	minus_l
#define Iminus_n	minus_n
#define Iminus_p	minus_p
#define Imultiline	multiline
#define Imystack_base	mystack_base
#define Imystack_mark	mystack_mark
#define Imystack_max	mystack_max
#define Imystack_sp	mystack_sp
#define Imystrk		mystrk
#define Inrs		nrs
#define Inrschar	nrschar
#define Inrslen		nrslen
#define Iofmt		ofmt
#define Iofs		ofs
#define Iofslen		ofslen
#define Ioldlastpm	oldlastpm
#define Ioldname	oldname
#define Iorigargc	origargc
#define Iorigargv	origargv
#define Iorigfilename	origfilename
#define Iors		ors
#define Iorslen		orslen
#define Ipad		pad
#define Ipadname	padname
#define Ipatchlevel	patchlevel
#define Iperldb		perldb
#define Ipidstatus	pidstatus
#define Ipreambled	preambled
#define Ipreprocess	preprocess
#define Irestartop	restartop
#define Irightgv	rightgv
#define Irs		rs
#define Irschar		rschar
#define Irslen		rslen
#define Irspara		rspara
#define Isawampersand	sawampersand
#define Isawi		sawi
#define Isawstudy	sawstudy
#define Isawvec		sawvec
#define Iscreamfirst	screamfirst
#define Iscreamnext	screamnext
#define Isecondgv	secondgv
#define Isiggv		siggv
#define Isignalstack	signalstack
#define Isortcop	sortcop
#define Isortstack	sortstack
#define Isortstash	sortstash
#define Isplitstr	splitstr
#define Istack		stack
#define Istatcache	statcache
#define Istatgv		statgv
#define Istatname	statname
#define Istatusvalue	statusvalue
#define Istdingv	stdingv
#define Istrchop	strchop
#define Isv_count	sv_count
#define Isv_rvcount	sv_rvcount
#define Isv_root	sv_root
#define Isv_arenaroot	sv_arenaroot
#define Itainted	tainted
#define Itainting	tainting
#define Itmps_floor	tmps_floor
#define Itmps_ix	tmps_ix
#define Itmps_max	tmps_max
#define Itmps_stack	tmps_stack
#define Itop_env	top_env
#define Itoptarget	toptarget
#define Iunsafe		unsafe

#endif /* MULTIPLICITY */
