/* This file is derived from global.var and interp.var */

/* (Doing namespace management portably in C is really gross.) */

#ifdef EMBED

/* globals we need to hide from the world */
#define No		PERLNo
#define Sv		PERLSv
#define Xpv		PERLXpv
#define Yes		PERLYes
#define additem		PERLadditem
#define an		PERLan
#define buf		PERLbuf
#define bufend		PERLbufend
#define bufptr		PERLbufptr
#define check		PERLcheck
#define coeff		PERLcoeff
#define compiling	PERLcompiling
#define comppad		PERLcomppad
#define comppadname	PERLcomppadname
#define comppadnamefill	PERLcomppadnamefill
#define cop_seqmax	PERLcop_seqmax
#define cryptseen	PERLcryptseen
#define cshlen		PERLcshlen
#define cshname		PERLcshname
#define curinterp	PERLcurinterp
#define curpad		PERLcurpad
#define dc		PERLdc
#define di		PERLdi
#define ds		PERLds
#define egid		PERLegid
#define error_count	PERLerror_count
#define euid		PERLeuid
#define evstr		PERLevstr
#define expect		PERLexpect
#define expectterm	PERLexpectterm
#define fold		PERLfold
#define freq		PERLfreq
#define gid		PERLgid
#define hexdigit	PERLhexdigit
#define in_format	PERLin_format
#define in_my		PERLin_my
#define know_next	PERLknow_next
#define last_lop	PERLlast_lop
#define last_uni	PERLlast_uni
#define linestr		PERLlinestr
#define markstack	PERLmarkstack
#define markstack_max	PERLmarkstack_max
#define markstack_ptr	PERLmarkstack_ptr
#define multi_close	PERLmulti_close
#define multi_end	PERLmulti_end
#define multi_open	PERLmulti_open
#define multi_start	PERLmulti_start
#define na		PERLna
#define needblockscope	PERLneedblockscope
#define nexttype	PERLnexttype
#define nextval		PERLnextval
#define no_aelem	PERLno_aelem
#define no_dir_func	PERLno_dir_func
#define no_func		PERLno_func
#define no_helem	PERLno_helem
#define no_mem		PERLno_mem
#define no_modify	PERLno_modify
#define no_security	PERLno_security
#define no_sock_func	PERLno_sock_func
#define no_usym		PERLno_usym
#define nointrp		PERLnointrp
#define nomem		PERLnomem
#define nomemok		PERLnomemok
#define oldbufptr	PERLoldbufptr
#define oldoldbufptr	PERLoldoldbufptr
#define op		PERLop
#define op_name		PERLop_name
#define op_seqmax	PERLop_seqmax
#define opargs		PERLopargs
#define origalen	PERLorigalen
#define origenviron	PERLorigenviron
#define padix		PERLpadix
#define patleave	PERLpatleave
#define ppaddr		PERLppaddr
#define rcsid		PERLrcsid
#define reall_srchlen	PERLreall_srchlen
#define regarglen	PERLregarglen
#define regbol		PERLregbol
#define regcode		PERLregcode
#define regdummy	PERLregdummy
#define regendp		PERLregendp
#define regeol		PERLregeol
#define regfold		PERLregfold
#define reginput	PERLreginput
#define reglastparen	PERLreglastparen
#define regmyendp	PERLregmyendp
#define regmyp_size	PERLregmyp_size
#define regmystartp	PERLregmystartp
#define regnarrate	PERLregnarrate
#define regnpar		PERLregnpar
#define regparse	PERLregparse
#define regprecomp	PERLregprecomp
#define regprev		PERLregprev
#define regsawback	PERLregsawback
#define regsawbracket	PERLregsawbracket
#define regsize		PERLregsize
#define regstartp	PERLregstartp
#define regtill		PERLregtill
#define regxend		PERLregxend
#define retstack	PERLretstack
#define retstack_ix	PERLretstack_ix
#define retstack_max	PERLretstack_max
#define rsfp		PERLrsfp
#define savestack	PERLsavestack
#define savestack_ix	PERLsavestack_ix
#define savestack_max	PERLsavestack_max
#define saw_return	PERLsaw_return
#define scopestack	PERLscopestack
#define scopestack_ix	PERLscopestack_ix
#define scopestack_max	PERLscopestack_max
#define scrgv		PERLscrgv
#define sig_name	PERLsig_name
#define simple		PERLsimple
#define stack_base	PERLstack_base
#define stack_max	PERLstack_max
#define stack_sp	PERLstack_sp
#define statbuf		PERLstatbuf
#define sub_generation	PERLsub_generation
#define subline		PERLsubline
#define subname		PERLsubname
#define sv_no		PERLsv_no
#define sv_undef	PERLsv_undef
#define sv_yes		PERLsv_yes
#define thisexpr	PERLthisexpr
#define timesbuf	PERLtimesbuf
#define tokenbuf	PERLtokenbuf
#define uid		PERLuid
#define varies		PERLvaries
#define vert		PERLvert
#define vtbl_arylen	PERLvtbl_arylen
#define vtbl_bm		PERLvtbl_bm
#define vtbl_dbline	PERLvtbl_dbline
#define vtbl_env	PERLvtbl_env
#define vtbl_envelem	PERLvtbl_envelem
#define vtbl_glob	PERLvtbl_glob
#define vtbl_isa	PERLvtbl_isa
#define vtbl_isaelem	PERLvtbl_isaelem
#define vtbl_mglob	PERLvtbl_mglob
#define vtbl_pack	PERLvtbl_pack
#define vtbl_packelem	PERLvtbl_packelem
#define vtbl_sig	PERLvtbl_sig
#define vtbl_sigelem	PERLvtbl_sigelem
#define vtbl_substr	PERLvtbl_substr
#define vtbl_sv		PERLvtbl_sv
#define vtbl_taint	PERLvtbl_taint
#define vtbl_uvar	PERLvtbl_uvar
#define vtbl_vec	PERLvtbl_vec
#define warn_nl		PERLwarn_nl
#define warn_nosemi	PERLwarn_nosemi
#define warn_reserved	PERLwarn_reserved
#define watchaddr	PERLwatchaddr
#define watchok		PERLwatchok
#define yychar		PERLyychar
#define yycheck		PERLyycheck
#define yydebug		PERLyydebug
#define yydefred	PERLyydefred
#define yydgoto		PERLyydgoto
#define yyerrflag	PERLyyerrflag
#define yygindex	PERLyygindex
#define yylen		PERLyylen
#define yylhs		PERLyylhs
#define yylval		PERLyylval
#define yyname		PERLyyname
#define yynerrs		PERLyynerrs
#define yyrindex	PERLyyrindex
#define yyrule		PERLyyrule
#define yysindex	PERLyysindex
#define yytable		PERLyytable
#define yyval		PERLyyval
#define append_elem	PERLappend_elem
#define append_list	PERLappend_list
#define apply		PERLapply
#define av_clear	PERLav_clear
#define av_fake		PERLav_fake
#define av_fetch	PERLav_fetch
#define av_fill		PERLav_fill
#define av_free		PERLav_free
#define av_len		PERLav_len
#define av_make		PERLav_make
#define av_pop		PERLav_pop
#define av_popnulls	PERLav_popnulls
#define av_push		PERLav_push
#define av_shift	PERLav_shift
#define av_store	PERLav_store
#define av_undef	PERLav_undef
#define av_unshift	PERLav_unshift
#define bind_match	PERLbind_match
#define block_head	PERLblock_head
#define calllist	PERLcalllist
#define cando		PERLcando
#define check_uni	PERLcheck_uni
#define checkcomma	PERLcheckcomma
#define ck_aelem	PERLck_aelem
#define ck_chop		PERLck_chop
#define ck_concat	PERLck_concat
#define ck_eof		PERLck_eof
#define ck_eval		PERLck_eval
#define ck_exec		PERLck_exec
#define ck_formline	PERLck_formline
#define ck_ftst		PERLck_ftst
#define ck_fun		PERLck_fun
#define ck_glob		PERLck_glob
#define ck_grep		PERLck_grep
#define ck_gvconst	PERLck_gvconst
#define ck_index	PERLck_index
#define ck_lengthconst	PERLck_lengthconst
#define ck_lfun		PERLck_lfun
#define ck_listiob	PERLck_listiob
#define ck_match	PERLck_match
#define ck_null		PERLck_null
#define ck_repeat	PERLck_repeat
#define ck_retarget	PERLck_retarget
#define ck_rvconst	PERLck_rvconst
#define ck_select	PERLck_select
#define ck_shift	PERLck_shift
#define ck_sort		PERLck_sort
#define ck_split	PERLck_split
#define ck_subr		PERLck_subr
#define ck_trunc	PERLck_trunc
#define convert		PERLconvert
#define cpy7bit		PERLcpy7bit
#define cpytill		PERLcpytill
#define croak		PERLcroak
#define cv_clear	PERLcv_clear
#define cxinc		PERLcxinc
#define deb		PERLdeb
#define deb_growlevel	PERLdeb_growlevel
#define debop		PERLdebop
#define debstack	PERLdebstack
#define debstackptrs	PERLdebstackptrs
#define die		PERLdie
#define die_where	PERLdie_where
#define do_aexec	PERLdo_aexec
#define do_chop		PERLdo_chop
#define do_close	PERLdo_close
#define do_ctl		PERLdo_ctl
#define do_eof		PERLdo_eof
#define do_exec		PERLdo_exec
#define do_execfree	PERLdo_execfree
#define do_ipcctl	PERLdo_ipcctl
#define do_ipcget	PERLdo_ipcget
#define do_join		PERLdo_join
#define do_kv		PERLdo_kv
#define do_msgrcv	PERLdo_msgrcv
#define do_msgsnd	PERLdo_msgsnd
#define do_open		PERLdo_open
#define do_pipe		PERLdo_pipe
#define do_print	PERLdo_print
#define do_readline	PERLdo_readline
#define do_seek		PERLdo_seek
#define do_semop	PERLdo_semop
#define do_shmio	PERLdo_shmio
#define do_sprintf	PERLdo_sprintf
#define do_tell		PERLdo_tell
#define do_trans	PERLdo_trans
#define do_vecset	PERLdo_vecset
#define do_vop		PERLdo_vop
#define doeval		PERLdoeval
#define dofindlabel	PERLdofindlabel
#define dopoptoeval	PERLdopoptoeval
#define dump_all	PERLdump_all
#define dump_eval	PERLdump_eval
#define dump_gv		PERLdump_gv
#define dump_op		PERLdump_op
#define dump_packsubs	PERLdump_packsubs
#define dump_pm		PERLdump_pm
#define dump_sub	PERLdump_sub
#define fbm_compile	PERLfbm_compile
#define fbm_instr	PERLfbm_instr
#define fetch_gv	PERLfetch_gv
#define fetch_io	PERLfetch_io
#define fetch_stash	PERLfetch_stash
#define fold_constants	PERLfold_constants
#define force_ident	PERLforce_ident
#define force_next	PERLforce_next
#define force_word	PERLforce_word
#define free_tmps	PERLfree_tmps
#define gen_constant_list	PERLgen_constant_list
#define getgimme	PERLgetgimme
#define gp_free		PERLgp_free
#define gp_ref		PERLgp_ref
#define gv_AVadd	PERLgv_AVadd
#define gv_HVadd	PERLgv_HVadd
#define gv_check	PERLgv_check
#define gv_efullname	PERLgv_efullname
#define gv_fetchfile	PERLgv_fetchfile
#define gv_fetchmeth	PERLgv_fetchmeth
#define gv_fetchmethod	PERLgv_fetchmethod
#define gv_fetchpv	PERLgv_fetchpv
#define gv_fullname	PERLgv_fullname
#define gv_init		PERLgv_init
#define he_delayfree	PERLhe_delayfree
#define he_free		PERLhe_free
#define hoistmust	PERLhoistmust
#define hv_clear	PERLhv_clear
#define hv_delete	PERLhv_delete
#define hv_fetch	PERLhv_fetch
#define hv_free		PERLhv_free
#define hv_iterinit	PERLhv_iterinit
#define hv_iterkey	PERLhv_iterkey
#define hv_iternext	PERLhv_iternext
#define hv_iterval	PERLhv_iterval
#define hv_magic	PERLhv_magic
#define hv_store	PERLhv_store
#define hv_undef	PERLhv_undef
#define ibcmp		PERLibcmp
#define ingroup		PERLingroup
#define instr		PERLinstr
#define intuit_more	PERLintuit_more
#define invert		PERLinvert
#define jmaybe		PERLjmaybe
#define keyword		PERLkeyword
#define leave_scope	PERLleave_scope
#define lex_end		PERLlex_end
#define lex_start	PERLlex_start
#define linklist	PERLlinklist
#define list		PERLlist
#define listkids	PERLlistkids
#define localize	PERLlocalize
#define looks_like_number	PERLlooks_like_number
#define magic_clearpack	PERLmagic_clearpack
#define magic_get	PERLmagic_get
#define magic_getarylen	PERLmagic_getarylen
#define magic_getglob	PERLmagic_getglob
#define magic_getpack	PERLmagic_getpack
#define magic_gettaint	PERLmagic_gettaint
#define magic_getuvar	PERLmagic_getuvar
#define magic_len	PERLmagic_len
#define magic_nextpack	PERLmagic_nextpack
#define magic_set	PERLmagic_set
#define magic_setarylen	PERLmagic_setarylen
#define magic_setbm	PERLmagic_setbm
#define magic_setdbline	PERLmagic_setdbline
#define magic_setenv	PERLmagic_setenv
#define magic_setglob	PERLmagic_setglob
#define magic_setisa	PERLmagic_setisa
#define magic_setmglob	PERLmagic_setmglob
#define magic_setpack	PERLmagic_setpack
#define magic_setsig	PERLmagic_setsig
#define magic_setsubstr	PERLmagic_setsubstr
#define magic_settaint	PERLmagic_settaint
#define magic_setuvar	PERLmagic_setuvar
#define magic_setvec	PERLmagic_setvec
#define magicname	PERLmagicname
#define mess		PERLmess
#define mg_clear	PERLmg_clear
#define mg_copy		PERLmg_copy
#define mg_find		PERLmg_find
#define mg_free		PERLmg_free
#define mg_get		PERLmg_get
#define mg_len		PERLmg_len
#define mg_set		PERLmg_set
#define mod		PERLmod
#define modkids		PERLmodkids
#define moreswitches	PERLmoreswitches
#define my		PERLmy
#define my_exit		PERLmy_exit
#define my_lstat	PERLmy_lstat
#define my_pclose	PERLmy_pclose
#define my_popen	PERLmy_popen
#define my_setenv	PERLmy_setenv
#define my_stat		PERLmy_stat
#define my_unexec	PERLmy_unexec
#define newANONHASH	PERLnewANONHASH
#define newANONLIST	PERLnewANONLIST
#define newASSIGNOP	PERLnewASSIGNOP
#define newAV		PERLnewAV
#define newAVREF	PERLnewAVREF
#define newBINOP	PERLnewBINOP
#define newCONDOP	PERLnewCONDOP
#define newCVOP		PERLnewCVOP
#define newCVREF	PERLnewCVREF
#define newFORM		PERLnewFORM
#define newFOROP	PERLnewFOROP
#define newGVOP		PERLnewGVOP
#define newGVREF	PERLnewGVREF
#define newGVgen	PERLnewGVgen
#define newHV		PERLnewHV
#define newHVREF	PERLnewHVREF
#define newIO		PERLnewIO
#define newLISTOP	PERLnewLISTOP
#define newLOGOP	PERLnewLOGOP
#define newLOOPOP	PERLnewLOOPOP
#define newMETHOD	PERLnewMETHOD
#define newNULLLIST	PERLnewNULLLIST
#define newOP		PERLnewOP
#define newPMOP		PERLnewPMOP
#define newPVOP		PERLnewPVOP
#define newRANGE	PERLnewRANGE
#define newSLICEOP	PERLnewSLICEOP
#define newSTATEOP	PERLnewSTATEOP
#define newSUB		PERLnewSUB
#define newSV		PERLnewSV
#define newSVOP		PERLnewSVOP
#define newSVREF	PERLnewSVREF
#define newSViv		PERLnewSViv
#define newSVnv		PERLnewSVnv
#define newSVpv		PERLnewSVpv
#define newSVsv		PERLnewSVsv
#define newUNOP		PERLnewUNOP
#define newWHILEOP	PERLnewWHILEOP
#define newXSUB		PERLnewXSUB
#define nextargv	PERLnextargv
#define ninstr		PERLninstr
#define no_fh_allowed	PERLno_fh_allowed
#define no_op		PERLno_op
#define nsavestr	PERLnsavestr
#define oopsAV		PERLoopsAV
#define oopsCV		PERLoopsCV
#define oopsHV		PERLoopsHV
#define op_free		PERLop_free
#define package		PERLpackage
#define pad_alloc	PERLpad_alloc
#define pad_allocmy	PERLpad_allocmy
#define pad_findmy	PERLpad_findmy
#define pad_free	PERLpad_free
#define pad_leavemy	PERLpad_leavemy
#define pad_reset	PERLpad_reset
#define pad_sv		PERLpad_sv
#define pad_swipe	PERLpad_swipe
#define peep		PERLpeep
#define pidgone		PERLpidgone
#define pmruntime	PERLpmruntime
#define pmtrans		PERLpmtrans
#define pop_return	PERLpop_return
#define pop_scope	PERLpop_scope
#define pp_aassign	PERLpp_aassign
#define pp_accept	PERLpp_accept
#define pp_add		PERLpp_add
#define pp_aelem	PERLpp_aelem
#define pp_aelemfast	PERLpp_aelemfast
#define pp_alarm	PERLpp_alarm
#define pp_and		PERLpp_and
#define pp_andassign	PERLpp_andassign
#define pp_anonhash	PERLpp_anonhash
#define pp_anonlist	PERLpp_anonlist
#define pp_aslice	PERLpp_aslice
#define pp_atan2	PERLpp_atan2
#define pp_av2arylen	PERLpp_av2arylen
#define pp_backtick	PERLpp_backtick
#define pp_bind		PERLpp_bind
#define pp_binmode	PERLpp_binmode
#define pp_bit_and	PERLpp_bit_and
#define pp_bit_or	PERLpp_bit_or
#define pp_bless	PERLpp_bless
#define pp_caller	PERLpp_caller
#define pp_chdir	PERLpp_chdir
#define pp_chmod	PERLpp_chmod
#define pp_chop		PERLpp_chop
#define pp_chown	PERLpp_chown
#define pp_chroot	PERLpp_chroot
#define pp_close	PERLpp_close
#define pp_closedir	PERLpp_closedir
#define pp_complement	PERLpp_complement
#define pp_concat	PERLpp_concat
#define pp_cond_expr	PERLpp_cond_expr
#define pp_connect	PERLpp_connect
#define pp_const	PERLpp_const
#define pp_cos		PERLpp_cos
#define pp_crypt	PERLpp_crypt
#define pp_cswitch	PERLpp_cswitch
#define pp_dbmclose	PERLpp_dbmclose
#define pp_dbmopen	PERLpp_dbmopen
#define pp_dbstate	PERLpp_dbstate
#define pp_defined	PERLpp_defined
#define pp_delete	PERLpp_delete
#define pp_die		PERLpp_die
#define pp_divide	PERLpp_divide
#define pp_dofile	PERLpp_dofile
#define pp_done		PERLpp_done
#define pp_dump		PERLpp_dump
#define pp_each		PERLpp_each
#define pp_egrent	PERLpp_egrent
#define pp_ehostent	PERLpp_ehostent
#define pp_enetent	PERLpp_enetent
#define pp_enter	PERLpp_enter
#define pp_entereval	PERLpp_entereval
#define pp_enteriter	PERLpp_enteriter
#define pp_enterloop	PERLpp_enterloop
#define pp_entersubr	PERLpp_entersubr
#define pp_entertry	PERLpp_entertry
#define pp_enterwrite	PERLpp_enterwrite
#define pp_eof		PERLpp_eof
#define pp_eprotoent	PERLpp_eprotoent
#define pp_epwent	PERLpp_epwent
#define pp_eq		PERLpp_eq
#define pp_eservent	PERLpp_eservent
#define pp_evalonce	PERLpp_evalonce
#define pp_exec		PERLpp_exec
#define pp_exit		PERLpp_exit
#define pp_exp		PERLpp_exp
#define pp_fcntl	PERLpp_fcntl
#define pp_fileno	PERLpp_fileno
#define pp_flip		PERLpp_flip
#define pp_flock	PERLpp_flock
#define pp_flop		PERLpp_flop
#define pp_fork		PERLpp_fork
#define pp_formline	PERLpp_formline
#define pp_ftatime	PERLpp_ftatime
#define pp_ftbinary	PERLpp_ftbinary
#define pp_ftblk	PERLpp_ftblk
#define pp_ftchr	PERLpp_ftchr
#define pp_ftctime	PERLpp_ftctime
#define pp_ftdir	PERLpp_ftdir
#define pp_fteexec	PERLpp_fteexec
#define pp_fteowned	PERLpp_fteowned
#define pp_fteread	PERLpp_fteread
#define pp_ftewrite	PERLpp_ftewrite
#define pp_ftfile	PERLpp_ftfile
#define pp_ftis		PERLpp_ftis
#define pp_ftlink	PERLpp_ftlink
#define pp_ftmtime	PERLpp_ftmtime
#define pp_ftpipe	PERLpp_ftpipe
#define pp_ftrexec	PERLpp_ftrexec
#define pp_ftrowned	PERLpp_ftrowned
#define pp_ftrread	PERLpp_ftrread
#define pp_ftrwrite	PERLpp_ftrwrite
#define pp_ftsgid	PERLpp_ftsgid
#define pp_ftsize	PERLpp_ftsize
#define pp_ftsock	PERLpp_ftsock
#define pp_ftsuid	PERLpp_ftsuid
#define pp_ftsvtx	PERLpp_ftsvtx
#define pp_fttext	PERLpp_fttext
#define pp_fttty	PERLpp_fttty
#define pp_ftzero	PERLpp_ftzero
#define pp_ge		PERLpp_ge
#define pp_getc		PERLpp_getc
#define pp_getlogin	PERLpp_getlogin
#define pp_getpeername	PERLpp_getpeername
#define pp_getpgrp	PERLpp_getpgrp
#define pp_getppid	PERLpp_getppid
#define pp_getpriority	PERLpp_getpriority
#define pp_getsockname	PERLpp_getsockname
#define pp_ggrent	PERLpp_ggrent
#define pp_ggrgid	PERLpp_ggrgid
#define pp_ggrnam	PERLpp_ggrnam
#define pp_ghbyaddr	PERLpp_ghbyaddr
#define pp_ghbyname	PERLpp_ghbyname
#define pp_ghostent	PERLpp_ghostent
#define pp_glob		PERLpp_glob
#define pp_gmtime	PERLpp_gmtime
#define pp_gnbyaddr	PERLpp_gnbyaddr
#define pp_gnbyname	PERLpp_gnbyname
#define pp_gnetent	PERLpp_gnetent
#define pp_goto		PERLpp_goto
#define pp_gpbyname	PERLpp_gpbyname
#define pp_gpbynumber	PERLpp_gpbynumber
#define pp_gprotoent	PERLpp_gprotoent
#define pp_gpwent	PERLpp_gpwent
#define pp_gpwnam	PERLpp_gpwnam
#define pp_gpwuid	PERLpp_gpwuid
#define pp_grepstart	PERLpp_grepstart
#define pp_grepwhile	PERLpp_grepwhile
#define pp_gsbyname	PERLpp_gsbyname
#define pp_gsbyport	PERLpp_gsbyport
#define pp_gservent	PERLpp_gservent
#define pp_gsockopt	PERLpp_gsockopt
#define pp_gt		PERLpp_gt
#define pp_gv		PERLpp_gv
#define pp_gvsv		PERLpp_gvsv
#define pp_helem	PERLpp_helem
#define pp_hex		PERLpp_hex
#define pp_hslice	PERLpp_hslice
#define pp_index	PERLpp_index
#define pp_indread	PERLpp_indread
#define pp_int		PERLpp_int
#define pp_intadd	PERLpp_intadd
#define pp_interp	PERLpp_interp
#define pp_ioctl	PERLpp_ioctl
#define pp_iter		PERLpp_iter
#define pp_join		PERLpp_join
#define pp_keys		PERLpp_keys
#define pp_kill		PERLpp_kill
#define pp_last		PERLpp_last
#define pp_lc		PERLpp_lc
#define pp_lcfirst	PERLpp_lcfirst
#define pp_le		PERLpp_le
#define pp_leave	PERLpp_leave
#define pp_leaveeval	PERLpp_leaveeval
#define pp_leaveloop	PERLpp_leaveloop
#define pp_leavesubr	PERLpp_leavesubr
#define pp_leavetry	PERLpp_leavetry
#define pp_leavewrite	PERLpp_leavewrite
#define pp_left_shift	PERLpp_left_shift
#define pp_length	PERLpp_length
#define pp_lineseq	PERLpp_lineseq
#define pp_link		PERLpp_link
#define pp_list		PERLpp_list
#define pp_listen	PERLpp_listen
#define pp_localtime	PERLpp_localtime
#define pp_log		PERLpp_log
#define pp_lslice	PERLpp_lslice
#define pp_lstat	PERLpp_lstat
#define pp_lt		PERLpp_lt
#define pp_match	PERLpp_match
#define pp_method	PERLpp_method
#define pp_mkdir	PERLpp_mkdir
#define pp_modulo	PERLpp_modulo
#define pp_msgctl	PERLpp_msgctl
#define pp_msgget	PERLpp_msgget
#define pp_msgrcv	PERLpp_msgrcv
#define pp_msgsnd	PERLpp_msgsnd
#define pp_multiply	PERLpp_multiply
#define pp_ncmp		PERLpp_ncmp
#define pp_ne		PERLpp_ne
#define pp_negate	PERLpp_negate
#define pp_next		PERLpp_next
#define pp_nextstate	PERLpp_nextstate
#define pp_not		PERLpp_not
#define pp_nswitch	PERLpp_nswitch
#define pp_null		PERLpp_null
#define pp_oct		PERLpp_oct
#define pp_open		PERLpp_open
#define pp_open_dir	PERLpp_open_dir
#define pp_or		PERLpp_or
#define pp_orassign	PERLpp_orassign
#define pp_ord		PERLpp_ord
#define pp_pack		PERLpp_pack
#define pp_padav	PERLpp_padav
#define pp_padhv	PERLpp_padhv
#define pp_padsv	PERLpp_padsv
#define pp_pipe_op	PERLpp_pipe_op
#define pp_pop		PERLpp_pop
#define pp_postdec	PERLpp_postdec
#define pp_postinc	PERLpp_postinc
#define pp_pow		PERLpp_pow
#define pp_predec	PERLpp_predec
#define pp_preinc	PERLpp_preinc
#define pp_print	PERLpp_print
#define pp_prtf		PERLpp_prtf
#define pp_push		PERLpp_push
#define pp_pushmark	PERLpp_pushmark
#define pp_pushre	PERLpp_pushre
#define pp_rand		PERLpp_rand
#define pp_range	PERLpp_range
#define pp_rcatline	PERLpp_rcatline
#define pp_read		PERLpp_read
#define pp_readdir	PERLpp_readdir
#define pp_readline	PERLpp_readline
#define pp_readlink	PERLpp_readlink
#define pp_recv		PERLpp_recv
#define pp_redo		PERLpp_redo
#define pp_ref		PERLpp_ref
#define pp_refgen	PERLpp_refgen
#define pp_regcmaybe	PERLpp_regcmaybe
#define pp_regcomp	PERLpp_regcomp
#define pp_rename	PERLpp_rename
#define pp_repeat	PERLpp_repeat
#define pp_require	PERLpp_require
#define pp_reset	PERLpp_reset
#define pp_return	PERLpp_return
#define pp_reverse	PERLpp_reverse
#define pp_rewinddir	PERLpp_rewinddir
#define pp_right_shift	PERLpp_right_shift
#define pp_rindex	PERLpp_rindex
#define pp_rmdir	PERLpp_rmdir
#define pp_rv2av	PERLpp_rv2av
#define pp_rv2cv	PERLpp_rv2cv
#define pp_rv2gv	PERLpp_rv2gv
#define pp_rv2hv	PERLpp_rv2hv
#define pp_rv2sv	PERLpp_rv2sv
#define pp_sassign	PERLpp_sassign
#define pp_scalar	PERLpp_scalar
#define pp_schop	PERLpp_schop
#define pp_scmp		PERLpp_scmp
#define pp_scope	PERLpp_scope
#define pp_seek		PERLpp_seek
#define pp_seekdir	PERLpp_seekdir
#define pp_select	PERLpp_select
#define pp_semctl	PERLpp_semctl
#define pp_semget	PERLpp_semget
#define pp_semop	PERLpp_semop
#define pp_send		PERLpp_send
#define pp_seq		PERLpp_seq
#define pp_setpgrp	PERLpp_setpgrp
#define pp_setpriority	PERLpp_setpriority
#define pp_sge		PERLpp_sge
#define pp_sgrent	PERLpp_sgrent
#define pp_sgt		PERLpp_sgt
#define pp_shift	PERLpp_shift
#define pp_shmctl	PERLpp_shmctl
#define pp_shmget	PERLpp_shmget
#define pp_shmread	PERLpp_shmread
#define pp_shmwrite	PERLpp_shmwrite
#define pp_shostent	PERLpp_shostent
#define pp_shutdown	PERLpp_shutdown
#define pp_sin		PERLpp_sin
#define pp_sle		PERLpp_sle
#define pp_sleep	PERLpp_sleep
#define pp_slt		PERLpp_slt
#define pp_sne		PERLpp_sne
#define pp_snetent	PERLpp_snetent
#define pp_socket	PERLpp_socket
#define pp_sockpair	PERLpp_sockpair
#define pp_sort		PERLpp_sort
#define pp_splice	PERLpp_splice
#define pp_split	PERLpp_split
#define pp_sprintf	PERLpp_sprintf
#define pp_sprotoent	PERLpp_sprotoent
#define pp_spwent	PERLpp_spwent
#define pp_sqrt		PERLpp_sqrt
#define pp_srand	PERLpp_srand
#define pp_sselect	PERLpp_sselect
#define pp_sservent	PERLpp_sservent
#define pp_ssockopt	PERLpp_ssockopt
#define pp_stat		PERLpp_stat
#define pp_stub		PERLpp_stub
#define pp_study	PERLpp_study
#define pp_subst	PERLpp_subst
#define pp_substcont	PERLpp_substcont
#define pp_substr	PERLpp_substr
#define pp_subtract	PERLpp_subtract
#define pp_sv2len	PERLpp_sv2len
#define pp_symlink	PERLpp_symlink
#define pp_syscall	PERLpp_syscall
#define pp_sysread	PERLpp_sysread
#define pp_system	PERLpp_system
#define pp_syswrite	PERLpp_syswrite
#define pp_tell		PERLpp_tell
#define pp_telldir	PERLpp_telldir
#define pp_tie		PERLpp_tie
#define pp_time		PERLpp_time
#define pp_tms		PERLpp_tms
#define pp_trans	PERLpp_trans
#define pp_truncate	PERLpp_truncate
#define pp_uc		PERLpp_uc
#define pp_ucfirst	PERLpp_ucfirst
#define pp_umask	PERLpp_umask
#define pp_undef	PERLpp_undef
#define pp_unlink	PERLpp_unlink
#define pp_unpack	PERLpp_unpack
#define pp_unshift	PERLpp_unshift
#define pp_unstack	PERLpp_unstack
#define pp_untie	PERLpp_untie
#define pp_utime	PERLpp_utime
#define pp_values	PERLpp_values
#define pp_vec		PERLpp_vec
#define pp_wait		PERLpp_wait
#define pp_waitpid	PERLpp_waitpid
#define pp_wantarray	PERLpp_wantarray
#define pp_warn		PERLpp_warn
#define pp_xor		PERLpp_xor
#define prepend_elem	PERLprepend_elem
#define push_return	PERLpush_return
#define push_scope	PERLpush_scope
#define pv_grow		PERLpv_grow
#define q		PERLq
#define ref		PERLref
#define refkids		PERLrefkids
#define regcomp		PERLregcomp
#define regdump		PERLregdump
#define regexec		PERLregexec
#define regfree		PERLregfree
#define regnext		PERLregnext
#define regprop		PERLregprop
#define repeatcpy	PERLrepeatcpy
#define rninstr		PERLrninstr
#define run		PERLrun
#define save_I32	PERLsave_I32
#define save_aptr	PERLsave_aptr
#define save_ary	PERLsave_ary
#define save_hash	PERLsave_hash
#define save_hptr	PERLsave_hptr
#define save_int	PERLsave_int
#define save_item	PERLsave_item
#define save_list	PERLsave_list
#define save_nogv	PERLsave_nogv
#define save_scalar	PERLsave_scalar
#define save_sptr	PERLsave_sptr
#define save_svref	PERLsave_svref
#define savestack_grow	PERLsavestack_grow
#define savestr		PERLsavestr
#define sawparens	PERLsawparens
#define scalar		PERLscalar
#define scalarkids	PERLscalarkids
#define scalarseq	PERLscalarseq
#define scalarvoid	PERLscalarvoid
#define scan_const	PERLscan_const
#define scan_formline	PERLscan_formline
#define scan_heredoc	PERLscan_heredoc
#define scan_hex	PERLscan_hex
#define scan_ident	PERLscan_ident
#define scan_inputsymbol	PERLscan_inputsymbol
#define scan_num	PERLscan_num
#define scan_oct	PERLscan_oct
#define scan_pat	PERLscan_pat
#define scan_prefix	PERLscan_prefix
#define scan_str	PERLscan_str
#define scan_subst	PERLscan_subst
#define scan_trans	PERLscan_trans
#define scan_word	PERLscan_word
#define scope		PERLscope
#define screaminstr	PERLscreaminstr
#define setenv_getix	PERLsetenv_getix
#define skipspace	PERLskipspace
#define sublex_done	PERLsublex_done
#define sublex_start	PERLsublex_start
#define sv_2bool	PERLsv_2bool
#define sv_2cv		PERLsv_2cv
#define sv_2iv		PERLsv_2iv
#define sv_2mortal	PERLsv_2mortal
#define sv_2nv		PERLsv_2nv
#define sv_2pv		PERLsv_2pv
#define sv_backoff	PERLsv_backoff
#define sv_catpv	PERLsv_catpv
#define sv_catpvn	PERLsv_catpvn
#define sv_catsv	PERLsv_catsv
#define sv_chop		PERLsv_chop
#define sv_clear	PERLsv_clear
#define sv_cmp		PERLsv_cmp
#define sv_dec		PERLsv_dec
#define sv_eq		PERLsv_eq
#define sv_free		PERLsv_free
#define sv_gets		PERLsv_gets
#define sv_grow		PERLsv_grow
#define sv_inc		PERLsv_inc
#define sv_insert	PERLsv_insert
#define sv_isa		PERLsv_isa
#define sv_len		PERLsv_len
#define sv_magic	PERLsv_magic
#define sv_mortalcopy	PERLsv_mortalcopy
#define sv_peek		PERLsv_peek
#define sv_ref		PERLsv_ref
#define sv_replace	PERLsv_replace
#define sv_reset	PERLsv_reset
#define sv_setiv	PERLsv_setiv
#define sv_setnv	PERLsv_setnv
#define sv_setptrobj	PERLsv_setptrobj
#define sv_setpv	PERLsv_setpv
#define sv_setpvn	PERLsv_setpvn
#define sv_setsv	PERLsv_setsv
#define sv_unmagic	PERLsv_unmagic
#define sv_upgrade	PERLsv_upgrade
#define sv_usepvn	PERLsv_usepvn
#define taint_env	PERLtaint_env
#define taint_not	PERLtaint_not
#define taint_proper	PERLtaint_proper
#define too_few_arguments	PERLtoo_few_arguments
#define too_many_arguments	PERLtoo_many_arguments
#define wait4pid	PERLwait4pid
#define warn		PERLwarn
#define watch		PERLwatch
#define whichsig	PERLwhichsig
#define yyerror		PERLyyerror
#define yylex		PERLyylex
#define yyparse		PERLyyparse

#endif /* EMBEDDED */

/* Put interpreter specific variables into a struct? */

#ifdef MULTIPLICITY

#define Argv		(curinterp->IArgv)
#define Cmd		(curinterp->ICmd)
#define DBgv		(curinterp->IDBgv)
#define DBline		(curinterp->IDBline)
#define DBsignal	(curinterp->IDBsignal)
#define DBsingle	(curinterp->IDBsingle)
#define DBsub		(curinterp->IDBsub)
#define DBtrace		(curinterp->IDBtrace)
#define allgvs		(curinterp->Iallgvs)
#define ampergv		(curinterp->Iampergv)
#define argvgv		(curinterp->Iargvgv)
#define argvoutgv	(curinterp->Iargvoutgv)
#define arybase		(curinterp->Iarybase)
#define basetime	(curinterp->Ibasetime)
#define beginav		(curinterp->Ibeginav)
#define bodytarget	(curinterp->Ibodytarget)
#define cddir		(curinterp->Icddir)
#define chopset		(curinterp->Ichopset)
#define copline		(curinterp->Icopline)
#define curblock	(curinterp->Icurblock)
#define curcop		(curinterp->Icurcop)
#define curcsv		(curinterp->Icurcsv)
#define curoutgv	(curinterp->Icuroutgv)
#define curpm		(curinterp->Icurpm)
#define curstash	(curinterp->Icurstash)
#define curstname	(curinterp->Icurstname)
#define cxstack		(curinterp->Icxstack)
#define cxstack_ix	(curinterp->Icxstack_ix)
#define cxstack_max	(curinterp->Icxstack_max)
#define dbargs		(curinterp->Idbargs)
#define debdelim	(curinterp->Idebdelim)
#define debname		(curinterp->Idebname)
#define debstash	(curinterp->Idebstash)
#define debug		(curinterp->Idebug)
#define defgv		(curinterp->Idefgv)
#define defoutgv	(curinterp->Idefoutgv)
#define defstash	(curinterp->Idefstash)
#define delaymagic	(curinterp->Idelaymagic)
#define dirty		(curinterp->Idirty)
#define dlevel		(curinterp->Idlevel)
#define dlmax		(curinterp->Idlmax)
#define do_undump	(curinterp->Ido_undump)
#define doextract	(curinterp->Idoextract)
#define doswitches	(curinterp->Idoswitches)
#define dowarn		(curinterp->Idowarn)
#define dumplvl		(curinterp->Idumplvl)
#define e_fp		(curinterp->Ie_fp)
#define e_tmpname	(curinterp->Ie_tmpname)
#define endav		(curinterp->Iendav)
#define envgv		(curinterp->Ienvgv)
#define eval_root	(curinterp->Ieval_root)
#define eval_start	(curinterp->Ieval_start)
#define fdpid		(curinterp->Ifdpid)
#define filemode	(curinterp->Ifilemode)
#define firstgv		(curinterp->Ifirstgv)
#define forkprocess	(curinterp->Iforkprocess)
#define formfeed	(curinterp->Iformfeed)
#define formtarget	(curinterp->Iformtarget)
#define freestrroot	(curinterp->Ifreestrroot)
#define gensym		(curinterp->Igensym)
#define in_eval		(curinterp->Iin_eval)
#define incgv		(curinterp->Iincgv)
#define inplace		(curinterp->Iinplace)
#define last_in_gv	(curinterp->Ilast_in_gv)
#define lastfd		(curinterp->Ilastfd)
#define lastretstr	(curinterp->Ilastretstr)
#define lastscream	(curinterp->Ilastscream)
#define lastsize	(curinterp->Ilastsize)
#define lastspbase	(curinterp->Ilastspbase)
#define laststatval	(curinterp->Ilaststatval)
#define laststype	(curinterp->Ilaststype)
#define leftgv		(curinterp->Ileftgv)
#define lineary		(curinterp->Ilineary)
#define localizing	(curinterp->Ilocalizing)
#define main_root	(curinterp->Imain_root)
#define main_start	(curinterp->Imain_start)
#define mainstack	(curinterp->Imainstack)
#define maxscream	(curinterp->Imaxscream)
#define maxsysfd	(curinterp->Imaxsysfd)
#define minus_a		(curinterp->Iminus_a)
#define minus_c		(curinterp->Iminus_c)
#define minus_l		(curinterp->Iminus_l)
#define minus_n		(curinterp->Iminus_n)
#define minus_p		(curinterp->Iminus_p)
#define multiline	(curinterp->Imultiline)
#define mystack_base	(curinterp->Imystack_base)
#define mystack_mark	(curinterp->Imystack_mark)
#define mystack_max	(curinterp->Imystack_max)
#define mystack_sp	(curinterp->Imystack_sp)
#define mystrk		(curinterp->Imystrk)
#define nrs		(curinterp->Inrs)
#define nrschar		(curinterp->Inrschar)
#define nrslen		(curinterp->Inrslen)
#define ofmt		(curinterp->Iofmt)
#define ofs		(curinterp->Iofs)
#define ofslen		(curinterp->Iofslen)
#define oldlastpm	(curinterp->Ioldlastpm)
#define oldname		(curinterp->Ioldname)
#define origargc	(curinterp->Iorigargc)
#define origargv	(curinterp->Iorigargv)
#define origfilename	(curinterp->Iorigfilename)
#define ors		(curinterp->Iors)
#define orslen		(curinterp->Iorslen)
#define pad		(curinterp->Ipad)
#define padname		(curinterp->Ipadname)
#define patchlevel	(curinterp->Ipatchlevel)
#define perldb		(curinterp->Iperldb)
#define pidstatus	(curinterp->Ipidstatus)
#define preambled	(curinterp->Ipreambled)
#define preprocess	(curinterp->Ipreprocess)
#define restartop	(curinterp->Irestartop)
#define rightgv		(curinterp->Irightgv)
#define rs		(curinterp->Irs)
#define rschar		(curinterp->Irschar)
#define rslen		(curinterp->Irslen)
#define rspara		(curinterp->Irspara)
#define sawampersand	(curinterp->Isawampersand)
#define sawi		(curinterp->Isawi)
#define sawstudy	(curinterp->Isawstudy)
#define sawvec		(curinterp->Isawvec)
#define screamfirst	(curinterp->Iscreamfirst)
#define screamnext	(curinterp->Iscreamnext)
#define secondgv	(curinterp->Isecondgv)
#define siggv		(curinterp->Isiggv)
#define signalstack	(curinterp->Isignalstack)
#define sortcop		(curinterp->Isortcop)
#define sortstack	(curinterp->Isortstack)
#define sortstash	(curinterp->Isortstash)
#define stack		(curinterp->Istack)
#define statcache	(curinterp->Istatcache)
#define statgv		(curinterp->Istatgv)
#define statname	(curinterp->Istatname)
#define statusvalue	(curinterp->Istatusvalue)
#define stdingv		(curinterp->Istdingv)
#define strchop		(curinterp->Istrchop)
#define tainted		(curinterp->Itainted)
#define tainting	(curinterp->Itainting)
#define tmps_floor	(curinterp->Itmps_floor)
#define tmps_ix		(curinterp->Itmps_ix)
#define tmps_max	(curinterp->Itmps_max)
#define tmps_stack	(curinterp->Itmps_stack)
#define top_env		(curinterp->Itop_env)
#define toptarget	(curinterp->Itoptarget)
#define unsafe		(curinterp->Iunsafe)

#else	/* not multiple, so translate interpreter variables the other way... */

#define IArgv		Argv
#define ICmd		Cmd
#define IDBgv		DBgv
#define IDBline		DBline
#define IDBsignal	DBsignal
#define IDBsingle	DBsingle
#define IDBsub		DBsub
#define IDBtrace	DBtrace
#define Iallgvs		allgvs
#define Iampergv	ampergv
#define Iargvgv		argvgv
#define Iargvoutgv	argvoutgv
#define Iarybase	arybase
#define Ibasetime	basetime
#define Ibeginav	beginav
#define Ibodytarget	bodytarget
#define Icddir		cddir
#define Ichopset	chopset
#define Icopline	copline
#define Icurblock	curblock
#define Icurcop		curcop
#define Icurcsv		curcsv
#define Icuroutgv	curoutgv
#define Icurpm		curpm
#define Icurstash	curstash
#define Icurstname	curstname
#define Icxstack	cxstack
#define Icxstack_ix	cxstack_ix
#define Icxstack_max	cxstack_max
#define Idbargs		dbargs
#define Idebdelim	debdelim
#define Idebname	debname
#define Idebstash	debstash
#define Idebug		debug
#define Idefgv		defgv
#define Idefoutgv	defoutgv
#define Idefstash	defstash
#define Idelaymagic	delaymagic
#define Idirty		dirty
#define Idlevel		dlevel
#define Idlmax		dlmax
#define Ido_undump	do_undump
#define Idoextract	doextract
#define Idoswitches	doswitches
#define Idowarn		dowarn
#define Idumplvl	dumplvl
#define Ie_fp		e_fp
#define Ie_tmpname	e_tmpname
#define Iendav		endav
#define Ienvgv		envgv
#define Ieval_root	eval_root
#define Ieval_start	eval_start
#define Ifdpid		fdpid
#define Ifilemode	filemode
#define Ifirstgv	firstgv
#define Iforkprocess	forkprocess
#define Iformfeed	formfeed
#define Iformtarget	formtarget
#define Ifreestrroot	freestrroot
#define Igensym		gensym
#define Iin_eval	in_eval
#define Iincgv		incgv
#define Iinplace	inplace
#define Ilast_in_gv	last_in_gv
#define Ilastfd		lastfd
#define Ilastretstr	lastretstr
#define Ilastscream	lastscream
#define Ilastsize	lastsize
#define Ilastspbase	lastspbase
#define Ilaststatval	laststatval
#define Ilaststype	laststype
#define Ileftgv		leftgv
#define Ilineary	lineary
#define Ilocalizing	localizing
#define Imain_root	main_root
#define Imain_start	main_start
#define Imainstack	mainstack
#define Imaxscream	maxscream
#define Imaxsysfd	maxsysfd
#define Iminus_a	minus_a
#define Iminus_c	minus_c
#define Iminus_l	minus_l
#define Iminus_n	minus_n
#define Iminus_p	minus_p
#define Imultiline	multiline
#define Imystack_base	mystack_base
#define Imystack_mark	mystack_mark
#define Imystack_max	mystack_max
#define Imystack_sp	mystack_sp
#define Imystrk		mystrk
#define Inrs		nrs
#define Inrschar	nrschar
#define Inrslen		nrslen
#define Iofmt		ofmt
#define Iofs		ofs
#define Iofslen		ofslen
#define Ioldlastpm	oldlastpm
#define Ioldname	oldname
#define Iorigargc	origargc
#define Iorigargv	origargv
#define Iorigfilename	origfilename
#define Iors		ors
#define Iorslen		orslen
#define Ipad		pad
#define Ipadname	padname
#define Ipatchlevel	patchlevel
#define Iperldb		perldb
#define Ipidstatus	pidstatus
#define Ipreambled	preambled
#define Ipreprocess	preprocess
#define Irestartop	restartop
#define Irightgv	rightgv
#define Irs		rs
#define Irschar		rschar
#define Irslen		rslen
#define Irspara		rspara
#define Isawampersand	sawampersand
#define Isawi		sawi
#define Isawstudy	sawstudy
#define Isawvec		sawvec
#define Iscreamfirst	screamfirst
#define Iscreamnext	screamnext
#define Isecondgv	secondgv
#define Isiggv		siggv
#define Isignalstack	signalstack
#define Isortcop	sortcop
#define Isortstack	sortstack
#define Isortstash	sortstash
#define Istack		stack
#define Istatcache	statcache
#define Istatgv		statgv
#define Istatname	statname
#define Istatusvalue	statusvalue
#define Istdingv	stdingv
#define Istrchop	strchop
#define Itainted	tainted
#define Itainting	tainting
#define Itmps_floor	tmps_floor
#define Itmps_ix	tmps_ix
#define Itmps_max	tmps_max
#define Itmps_stack	tmps_stack
#define Itop_env	top_env
#define Itoptarget	toptarget
#define Iunsafe		unsafe

#endif /* MULTIPLE_INTERPRETERS */
