#!/usr/bin/perl

sub fib
{
    local($a) = $_[0];
    ($a < 2) ? $a : &fib($a-1) + &fib($a-2);
}

sub myruntime
{
    local(@t) = times;          #  in seconds
    $t[0] + $t[1];
}

$x = (shift || 20);
print "Starting fib($x)\n";
$before = &myruntime;
$y = &fib($x);
$after = &myruntime;
printf("Done. Result $y in %g cpu seconds.\n", $after-$before);

