# : Makefile.SH,v 303Revision: 4.0.1.4 303Date: 92/06/08 11:40:43 $
#
# $Log:	Makefile.SH,v $
# Revision 4.0.1.4  92/06/08  11:40:43  lwall
# patch20: cray didn't give enough memory to /bin/sh
# patch20: various and sundry fixes
# 
# Revision 4.0.1.3  91/11/05  15:48:11  lwall
# patch11: saberized perl
# patch11: added support for dbz
# 
# Revision 4.0.1.2  91/06/07  10:14:43  lwall
# patch4: cflags now emits entire cc command except for the filename
# patch4: alternate make programs are now semi-supported
# patch4: uperl.o no longer tries to link in libraries prematurely
# patch4: installperl now installs x2p stuff too
# 
# Revision 4.0.1.1  91/04/11  17:30:39  lwall
# patch1: C flags are now settable on a per-file basis
# 
# Revision 4.0  91/03/20  00:58:54  lwall
# 4.0 baseline.
# 
# 

CC = cc
YACC = /bin/yacc
bin = /usr/local/bin
scriptdir = /usr/local/bin
privlib = /usr/local/lib/perl
mansrc = /usr/man/manl
manext = l
LDFLAGS = 
CLDFLAGS = 
SMALL = 
LARGE =  
mallocsrc = malloc.c
mallocobj = malloc.o
SLN = ln -s
RMS = rm -f
LIB = .

libs = -ldbm -lm -lposix 

public = perl taintperl 

shellflags = 

# To use an alternate make, set  in config.sh.
MAKE = make


CCCMD = `sh $(shellflags) cflags $@`

private = 

scripts = h2ph

manpages = perl.man h2ph.man

util =

sh = Makefile.SH makedepend.SH h2ph.SH

h1 = EXTERN.h INTERN.h arg.h array.h cmd.h config.h embed.h form.h handy.h
h2 = hash.h perl.h regcomp.h regexp.h spat.h stab.h str.h util.h

h = $(h1) $(h2)

c1 = array.c cmd.c cons.c consarg.c doarg.c doio.c dolist.c dump.c
c2 = eval.c form.c hash.c main.c $(mallocsrc) perl.c pp.c regcomp.c regexec.c
c3 = stab.c str.c toke.c util.c usersub.c

c = $(c1) $(c2) $(c3)

s1 = array.c cmd.c cons.c consarg.c doarg.c doio.c dolist.c dump.c
s2 = eval.c form.c hash.c main.c perl.c pp.c regcomp.c regexec.c
s3 = stab.c str.c toke.c util.c usersub.c perly.c

saber = $(s1) $(s2) $(s3)

obj1 = array.o cmd.o cons.o consarg.o doarg.o doio.o dolist.o dump.o
obj2 = eval.o form.o $(mallocobj) perl.o pp.o regcomp.o regexec.o
obj3 = stab.o str.o toke.o util.o

obj = $(obj1) $(obj2) $(obj3)

tobj1 = tarray.o tcmd.o tcons.o tconsarg.o tdoarg.o tdoio.o tdolist.o tdump.o
tobj2 = teval.o tform.o thash.o $(mallocobj) tpp.o tregcomp.o tregexec.o
tobj3 = tstab.o tstr.o ttoke.o tutil.o

tobj = $(tobj1) $(tobj2) $(tobj3)

lintflags = -hbvxac

addedbyconf = Makefile.old bsd eunice filexp loc pdp11 usg v7

# grrr
SHELL = /bin/sh

.c.o:
	$(CCCMD) $*.c

all: libperl.rlb

#all: $(public) $(private) $(util) uperl.o $(scripts)
#	cd x2p; $(MAKE) all
#	touch all

# This is the standard version that contains no "taint" checks and is
# used for all scripts that aren't set-id or running under something set-id.
# The $& notation is tells Sequent machines that it can do a parallel make,
# and is harmless otherwise.

#perl: $& main.o $(obj) hash.o perly.o usersub.o
#	$(CC) $(LARGE) $(CLDFLAGS) main.o $(obj) hash.o perly.o usersub.o \
#	    $(libs) -o perl
#	echo ''

perl: $& main.o libperl.rlb
	$(CC) $(LARGE) $(CLDFLAGS) main.o $(LIB)/libperl.a $(libs) -o perl
	echo ''

libperl.rlb: $(LIB)/libperl.a
	ranlib $(LIB)/libperl.a
	touch libperl.rlb

$(LIB)/libperl.a: $& perly.o perl.o $(obj) hash.o usersub.o
	ar rcuv $(LIB)/libperl.a $(obj) hash.o perly.o usersub.o

# This version, if specified in Configure, does ONLY those scripts which need
# set-id emulation.  Suidperl must be setuid root.  It contains the "taint"
# checks as well as the special code to validate that the script in question
# has been invoked correctly.

suidperl: $& sperl.o main.o libtperl.rlb
	$(CC) $(LARGE) $(CLDFLAGS) sperl.o main.o libtperl.a $(libs) -o suidperl

# This version interprets scripts that are already set-id either via a wrapper
# or through the kernel allowing set-id scripts (bad idea).  Taintperl must
# NOT be setuid to root or anything else.  The only difference between it
# and normal perl is the presence of the "taint" checks.

taintperl: $& main.o libtperl.rlb
	$(CC) $(LARGE) $(CLDFLAGS) main.o libtperl.a $(libs) -o taintperl

libtperl.rlb: libtperl.a
	ranlib libtperl.a
	touch libtperl.rlb

libtperl.a: $& tperly.o tperl.o $(tobj) thash.o usersub.o
	ar rcuv libtperl.a $(tobj) thash.o tperly.o usersub.o tperl.o

# This command assumes that /usr/include/dbz.h and /usr/lib/dbz.o exist.

dbzperl: $& main.o zhash.o libperl.rlb
	$(CC) $(LARGE) $(CLDFLAGS) main.o zhash.o /usr/lib/dbz.o $(LIB)/libperl.a $(libs) -o dbzperl

zhash.o: hash.c $(h)
	$(RMS) zhash.c
	$(SLN) hash.c zhash.c
	$(CCCMD) -DWANT_DBZ zhash.c
	$(RMS) zhash.c

uperl.o: $& $(obj) main.o hash.o perly.o
	-ld $(LARGE) $(LDFLAGS) -r $(obj) main.o hash.o perly.o -o uperl.o

saber: $(saber)
	# load $(saber)
	# load /lib/libm.a

# Replicating all this junk is yucky, but I don't see a portable way to fix it.

tperly.o: perly.c perly.h $(h)
	$(RMS) tperly.c
	$(SLN) perly.c tperly.c
	$(CCCMD) -DTAINT tperly.c
	$(RMS) tperly.c

tperl.o: perl.c perly.h patchlevel.h perl.h $(h)
	$(RMS) tperl.c
	$(SLN) perl.c tperl.c
	$(CCCMD) -DTAINT tperl.c
	$(RMS) tperl.c

sperl.o: perl.c perly.h patchlevel.h $(h)
	$(RMS) sperl.c
	$(SLN) perl.c sperl.c
	$(CCCMD) -DTAINT -DIAMSUID sperl.c
	$(RMS) sperl.c

tarray.o: array.c $(h)
	$(RMS) tarray.c
	$(SLN) array.c tarray.c
	$(CCCMD) -DTAINT tarray.c
	$(RMS) tarray.c

tcmd.o: cmd.c $(h)
	$(RMS) tcmd.c
	$(SLN) cmd.c tcmd.c
	$(CCCMD) -DTAINT tcmd.c
	$(RMS) tcmd.c

tcons.o: cons.c $(h) perly.h
	$(RMS) tcons.c
	$(SLN) cons.c tcons.c
	$(CCCMD) -DTAINT tcons.c
	$(RMS) tcons.c

tconsarg.o: consarg.c $(h)
	$(RMS) tconsarg.c
	$(SLN) consarg.c tconsarg.c
	$(CCCMD) -DTAINT tconsarg.c
	$(RMS) tconsarg.c

tdoarg.o: doarg.c $(h)
	$(RMS) tdoarg.c
	$(SLN) doarg.c tdoarg.c
	$(CCCMD) -DTAINT tdoarg.c
	$(RMS) tdoarg.c

tdoio.o: doio.c $(h)
	$(RMS) tdoio.c
	$(SLN) doio.c tdoio.c
	$(CCCMD) -DTAINT tdoio.c
	$(RMS) tdoio.c

tdolist.o: dolist.c $(h)
	$(RMS) tdolist.c
	$(SLN) dolist.c tdolist.c
	$(CCCMD) -DTAINT tdolist.c
	$(RMS) tdolist.c

tdump.o: dump.c $(h)
	$(RMS) tdump.c
	$(SLN) dump.c tdump.c
	$(CCCMD) -DTAINT tdump.c
	$(RMS) tdump.c

teval.o: eval.c $(h)
	$(RMS) teval.c
	$(SLN) eval.c teval.c
	$(CCCMD) -DTAINT teval.c
	$(RMS) teval.c

tform.o: form.c $(h)
	$(RMS) tform.c
	$(SLN) form.c tform.c
	$(CCCMD) -DTAINT tform.c
	$(RMS) tform.c

thash.o: hash.c $(h)
	$(RMS) thash.c
	$(SLN) hash.c thash.c
	$(CCCMD) -DTAINT thash.c
	$(RMS) thash.c

tpp.o: pp.c $(h)
	$(RMS) tpp.c
	$(SLN) pp.c tpp.c
	$(CCCMD) -DTAINT tpp.c
	$(RMS) tpp.c

tregcomp.o: regcomp.c $(h)
	$(RMS) tregcomp.c
	$(SLN) regcomp.c tregcomp.c
	$(CCCMD) -DTAINT tregcomp.c
	$(RMS) tregcomp.c

tregexec.o: regexec.c $(h)
	$(RMS) tregexec.c
	$(SLN) regexec.c tregexec.c
	$(CCCMD) -DTAINT tregexec.c
	$(RMS) tregexec.c

tstab.o: stab.c $(h)
	$(RMS) tstab.c
	$(SLN) stab.c tstab.c
	$(CCCMD) -DTAINT tstab.c
	$(RMS) tstab.c

tstr.o: str.c $(h) perly.h
	$(RMS) tstr.c
	$(SLN) str.c tstr.c
	$(CCCMD) -DTAINT tstr.c
	$(RMS) tstr.c

ttoke.o: toke.c $(h) perly.h
	$(RMS) ttoke.c
	$(SLN) toke.c ttoke.c
	$(CCCMD) -DTAINT ttoke.c
	$(RMS) ttoke.c

tutil.o: util.c $(h)
	$(RMS) tutil.c
	$(SLN) util.c tutil.c
	$(CCCMD) -DTAINT tutil.c
	$(RMS) tutil.c

perly.h: perly.c
	@ echo Dummy dependency for dumb parallel make
	touch perly.h

embed.h: embed_h.SH global.var interp.var
	sh embed_h.SH

perly.c: perly.y perly.fixer
	@ \
case "$(YACC)" in \
    *bison*) echo 'Expect' 25 shift/reduce and 53 reduce/reduce conflicts;; \
    *) echo 'Expect' 27 shift/reduce and 51 reduce/reduce conflicts;; \
esac
	$(YACC) -d perly.y
	sh $(shellflags) ./perly.fixer y.tab.c perly.c
	mv y.tab.h perly.h
	echo 'extern YYSTYPE yylval;' >>perly.h

perly.o: perly.c perly.h $(h)
	$(CCCMD) perly.c

install: all
	./perl installperl

clean:
	rm -f *.o all perl taintperl suidperl perly.c
	cd x2p; $(MAKE) clean

realclean: clean
	cd x2p; $(MAKE) realclean
	rm -f *.orig */*.orig *~ */*~ core $(addedbyconf) h2ph h2ph.man
	rm -f perly.c perly.h t/perl Makefile config.h makedepend makedir
	rm -f makefile x2p/Makefile x2p/makefile cflags x2p/cflags
	rm -f c2ph pstruct

# The following lint has practically everything turned on.  Unfortunately,
# you have to wade through a lot of mumbo jumbo that can't be suppressed.
# If the source file has a /*NOSTRICT*/ somewhere, ignore the lint message
# for that spot.

lint: perly.c $(c)
	lint $(lintflags) $(defs) perly.c $(c) > perl.fuzz

depend: makedepend
	- test -f perly.h || cp /dev/null perly.h
	./makedepend
	- test -s perly.h || /bin/rm -f perly.h
	cd x2p; $(MAKE) depend

test: perl
	- cd t && chmod +x TEST */*.t
	- cd t && (rm -f perl; $(SLN) ../perl perl) && ./perl TEST </dev/tty

clist:
	echo $(c) | tr ' ' '\012' >.clist

hlist:
	echo $(h) | tr ' ' '\012' >.hlist

shlist:
	echo $(sh) | tr ' ' '\012' >.shlist

# AUTOMATICALLY GENERATED MAKE DEPENDENCIES--PUT NOTHING BELOW THIS LINE
# If this runs make out of memory, delete /usr/include lines.
array.o: 
array.o: /usr/ucbinclude/ctype.h
array.o: /usr/ucbinclude/dirent.h
array.o: /usr/ucbinclude/errno.h
array.o: /usr/ucbinclude/machine/param.h
array.o: /usr/ucbinclude/machine/setjmp.h
array.o: /usr/ucbinclude/ndbm.h
array.o: /usr/ucbinclude/netinet/in.h
array.o: /usr/ucbinclude/setjmp.h
array.o: /usr/ucbinclude/stdio.h
array.o: /usr/ucbinclude/sys/dirent.h
array.o: /usr/ucbinclude/sys/errno.h
array.o: /usr/ucbinclude/sys/filio.h
array.o: /usr/ucbinclude/sys/ioccom.h
array.o: /usr/ucbinclude/sys/ioctl.h
array.o: /usr/ucbinclude/sys/param.h
array.o: /usr/ucbinclude/sys/signal.h
array.o: /usr/ucbinclude/sys/sockio.h
array.o: /usr/ucbinclude/sys/stat.h
array.o: /usr/ucbinclude/sys/stdtypes.h
array.o: /usr/ucbinclude/sys/sysmacros.h
array.o: /usr/ucbinclude/sys/time.h
array.o: /usr/ucbinclude/sys/times.h
array.o: /usr/ucbinclude/sys/ttold.h
array.o: /usr/ucbinclude/sys/ttychars.h
array.o: /usr/ucbinclude/sys/ttycom.h
array.o: /usr/ucbinclude/sys/ttydev.h
array.o: /usr/ucbinclude/sys/types.h
array.o: /usr/ucbinclude/time.h
array.o: /usr/ucbinclude/vm/faultcode.h
array.o: EXTERN.h
array.o: arg.h
array.o: array.c
array.o: array.h
array.o: cmd.h
array.o: config.h
array.o: embed.h
array.o: form.h
array.o: handy.h
array.o: hash.h
array.o: perl.h
array.o: regexp.h
array.o: spat.h
array.o: stab.h
array.o: str.h
array.o: unixish.h
array.o: util.h
cmd.o: 
cmd.o: /usr/ucbinclude/ctype.h
cmd.o: /usr/ucbinclude/dirent.h
cmd.o: /usr/ucbinclude/errno.h
cmd.o: /usr/ucbinclude/machine/param.h
cmd.o: /usr/ucbinclude/machine/setjmp.h
cmd.o: /usr/ucbinclude/ndbm.h
cmd.o: /usr/ucbinclude/netinet/in.h
cmd.o: /usr/ucbinclude/setjmp.h
cmd.o: /usr/ucbinclude/stdio.h
cmd.o: /usr/ucbinclude/sys/dirent.h
cmd.o: /usr/ucbinclude/sys/errno.h
cmd.o: /usr/ucbinclude/sys/filio.h
cmd.o: /usr/ucbinclude/sys/ioccom.h
cmd.o: /usr/ucbinclude/sys/ioctl.h
cmd.o: /usr/ucbinclude/sys/param.h
cmd.o: /usr/ucbinclude/sys/signal.h
cmd.o: /usr/ucbinclude/sys/sockio.h
cmd.o: /usr/ucbinclude/sys/stat.h
cmd.o: /usr/ucbinclude/sys/stdtypes.h
cmd.o: /usr/ucbinclude/sys/sysmacros.h
cmd.o: /usr/ucbinclude/sys/time.h
cmd.o: /usr/ucbinclude/sys/times.h
cmd.o: /usr/ucbinclude/sys/ttold.h
cmd.o: /usr/ucbinclude/sys/ttychars.h
cmd.o: /usr/ucbinclude/sys/ttycom.h
cmd.o: /usr/ucbinclude/sys/ttydev.h
cmd.o: /usr/ucbinclude/sys/types.h
cmd.o: /usr/ucbinclude/time.h
cmd.o: /usr/ucbinclude/varargs.h
cmd.o: /usr/ucbinclude/vm/faultcode.h
cmd.o: EXTERN.h
cmd.o: arg.h
cmd.o: array.h
cmd.o: cmd.c
cmd.o: cmd.h
cmd.o: config.h
cmd.o: embed.h
cmd.o: form.h
cmd.o: handy.h
cmd.o: hash.h
cmd.o: perl.h
cmd.o: regexp.h
cmd.o: spat.h
cmd.o: stab.h
cmd.o: str.h
cmd.o: unixish.h
cmd.o: util.h
cons.o: 
cons.o: /usr/ucbinclude/ctype.h
cons.o: /usr/ucbinclude/dirent.h
cons.o: /usr/ucbinclude/errno.h
cons.o: /usr/ucbinclude/machine/param.h
cons.o: /usr/ucbinclude/machine/setjmp.h
cons.o: /usr/ucbinclude/ndbm.h
cons.o: /usr/ucbinclude/netinet/in.h
cons.o: /usr/ucbinclude/setjmp.h
cons.o: /usr/ucbinclude/stdio.h
cons.o: /usr/ucbinclude/sys/dirent.h
cons.o: /usr/ucbinclude/sys/errno.h
cons.o: /usr/ucbinclude/sys/filio.h
cons.o: /usr/ucbinclude/sys/ioccom.h
cons.o: /usr/ucbinclude/sys/ioctl.h
cons.o: /usr/ucbinclude/sys/param.h
cons.o: /usr/ucbinclude/sys/signal.h
cons.o: /usr/ucbinclude/sys/sockio.h
cons.o: /usr/ucbinclude/sys/stat.h
cons.o: /usr/ucbinclude/sys/stdtypes.h
cons.o: /usr/ucbinclude/sys/sysmacros.h
cons.o: /usr/ucbinclude/sys/time.h
cons.o: /usr/ucbinclude/sys/times.h
cons.o: /usr/ucbinclude/sys/ttold.h
cons.o: /usr/ucbinclude/sys/ttychars.h
cons.o: /usr/ucbinclude/sys/ttycom.h
cons.o: /usr/ucbinclude/sys/ttydev.h
cons.o: /usr/ucbinclude/sys/types.h
cons.o: /usr/ucbinclude/time.h
cons.o: /usr/ucbinclude/vm/faultcode.h
cons.o: EXTERN.h
cons.o: arg.h
cons.o: array.h
cons.o: cmd.h
cons.o: config.h
cons.o: cons.c
cons.o: embed.h
cons.o: form.h
cons.o: handy.h
cons.o: hash.h
cons.o: perl.h
cons.o: perly.h
cons.o: regexp.h
cons.o: spat.h
cons.o: stab.h
cons.o: str.h
cons.o: unixish.h
cons.o: util.h
consarg.o: 
consarg.o: /usr/ucbinclude/ctype.h
consarg.o: /usr/ucbinclude/dirent.h
consarg.o: /usr/ucbinclude/errno.h
consarg.o: /usr/ucbinclude/machine/param.h
consarg.o: /usr/ucbinclude/machine/setjmp.h
consarg.o: /usr/ucbinclude/ndbm.h
consarg.o: /usr/ucbinclude/netinet/in.h
consarg.o: /usr/ucbinclude/setjmp.h
consarg.o: /usr/ucbinclude/stdio.h
consarg.o: /usr/ucbinclude/sys/dirent.h
consarg.o: /usr/ucbinclude/sys/errno.h
consarg.o: /usr/ucbinclude/sys/filio.h
consarg.o: /usr/ucbinclude/sys/ioccom.h
consarg.o: /usr/ucbinclude/sys/ioctl.h
consarg.o: /usr/ucbinclude/sys/param.h
consarg.o: /usr/ucbinclude/sys/signal.h
consarg.o: /usr/ucbinclude/sys/sockio.h
consarg.o: /usr/ucbinclude/sys/stat.h
consarg.o: /usr/ucbinclude/sys/stdtypes.h
consarg.o: /usr/ucbinclude/sys/sysmacros.h
consarg.o: /usr/ucbinclude/sys/time.h
consarg.o: /usr/ucbinclude/sys/times.h
consarg.o: /usr/ucbinclude/sys/ttold.h
consarg.o: /usr/ucbinclude/sys/ttychars.h
consarg.o: /usr/ucbinclude/sys/ttycom.h
consarg.o: /usr/ucbinclude/sys/ttydev.h
consarg.o: /usr/ucbinclude/sys/types.h
consarg.o: /usr/ucbinclude/time.h
consarg.o: /usr/ucbinclude/vm/faultcode.h
consarg.o: EXTERN.h
consarg.o: arg.h
consarg.o: array.h
consarg.o: cmd.h
consarg.o: config.h
consarg.o: consarg.c
consarg.o: embed.h
consarg.o: form.h
consarg.o: handy.h
consarg.o: hash.h
consarg.o: perl.h
consarg.o: regexp.h
consarg.o: spat.h
consarg.o: stab.h
consarg.o: str.h
consarg.o: unixish.h
consarg.o: util.h
doarg.o: 
doarg.o: /usr/ucbinclude/ctype.h
doarg.o: /usr/ucbinclude/dirent.h
doarg.o: /usr/ucbinclude/errno.h
doarg.o: /usr/ucbinclude/machine/param.h
doarg.o: /usr/ucbinclude/machine/setjmp.h
doarg.o: /usr/ucbinclude/ndbm.h
doarg.o: /usr/ucbinclude/netinet/in.h
doarg.o: /usr/ucbinclude/setjmp.h
doarg.o: /usr/ucbinclude/stdio.h
doarg.o: /usr/ucbinclude/sys/dirent.h
doarg.o: /usr/ucbinclude/sys/errno.h
doarg.o: /usr/ucbinclude/sys/filio.h
doarg.o: /usr/ucbinclude/sys/ioccom.h
doarg.o: /usr/ucbinclude/sys/ioctl.h
doarg.o: /usr/ucbinclude/sys/param.h
doarg.o: /usr/ucbinclude/sys/signal.h
doarg.o: /usr/ucbinclude/sys/sockio.h
doarg.o: /usr/ucbinclude/sys/stat.h
doarg.o: /usr/ucbinclude/sys/stdtypes.h
doarg.o: /usr/ucbinclude/sys/sysmacros.h
doarg.o: /usr/ucbinclude/sys/time.h
doarg.o: /usr/ucbinclude/sys/times.h
doarg.o: /usr/ucbinclude/sys/ttold.h
doarg.o: /usr/ucbinclude/sys/ttychars.h
doarg.o: /usr/ucbinclude/sys/ttycom.h
doarg.o: /usr/ucbinclude/sys/ttydev.h
doarg.o: /usr/ucbinclude/sys/types.h
doarg.o: /usr/ucbinclude/time.h
doarg.o: /usr/ucbinclude/vm/faultcode.h
doarg.o: EXTERN.h
doarg.o: arg.h
doarg.o: array.h
doarg.o: cmd.h
doarg.o: config.h
doarg.o: doarg.c
doarg.o: embed.h
doarg.o: form.h
doarg.o: handy.h
doarg.o: hash.h
doarg.o: perl.h
doarg.o: regexp.h
doarg.o: spat.h
doarg.o: stab.h
doarg.o: str.h
doarg.o: unixish.h
doarg.o: util.h
doio.o: 
doio.o: /usr/ucbinclude/ctype.h
doio.o: /usr/ucbinclude/debug/debug.h
doio.o: /usr/ucbinclude/dirent.h
doio.o: /usr/ucbinclude/errno.h
doio.o: /usr/ucbinclude/grp.h
doio.o: /usr/ucbinclude/machine/mmu.h
doio.o: /usr/ucbinclude/machine/param.h
doio.o: /usr/ucbinclude/machine/setjmp.h
doio.o: /usr/ucbinclude/mon/obpdefs.h
doio.o: /usr/ucbinclude/mon/openprom.h
doio.o: /usr/ucbinclude/mon/sunromvec.h
doio.o: /usr/ucbinclude/ndbm.h
doio.o: /usr/ucbinclude/netdb.h
doio.o: /usr/ucbinclude/netinet/in.h
doio.o: /usr/ucbinclude/pwd.h
doio.o: /usr/ucbinclude/setjmp.h
doio.o: /usr/ucbinclude/stdio.h
doio.o: /usr/ucbinclude/sys/dirent.h
doio.o: /usr/ucbinclude/sys/errno.h
doio.o: /usr/ucbinclude/sys/fcntlcom.h
doio.o: /usr/ucbinclude/sys/file.h
doio.o: /usr/ucbinclude/sys/filio.h
doio.o: /usr/ucbinclude/sys/ioccom.h
doio.o: /usr/ucbinclude/sys/ioctl.h
doio.o: /usr/ucbinclude/sys/ipc.h
doio.o: /usr/ucbinclude/sys/msg.h
doio.o: /usr/ucbinclude/sys/param.h
doio.o: /usr/ucbinclude/sys/sem.h
doio.o: /usr/ucbinclude/sys/shm.h
doio.o: /usr/ucbinclude/sys/signal.h
doio.o: /usr/ucbinclude/sys/socket.h
doio.o: /usr/ucbinclude/sys/sockio.h
doio.o: /usr/ucbinclude/sys/stat.h
doio.o: /usr/ucbinclude/sys/stdtypes.h
doio.o: /usr/ucbinclude/sys/sysmacros.h
doio.o: /usr/ucbinclude/sys/time.h
doio.o: /usr/ucbinclude/sys/times.h
doio.o: /usr/ucbinclude/sys/ttold.h
doio.o: /usr/ucbinclude/sys/ttychars.h
doio.o: /usr/ucbinclude/sys/ttycom.h
doio.o: /usr/ucbinclude/sys/ttydev.h
doio.o: /usr/ucbinclude/sys/types.h
doio.o: /usr/ucbinclude/time.h
doio.o: /usr/ucbinclude/utime.h
doio.o: /usr/ucbinclude/vm/faultcode.h
doio.o: EXTERN.h
doio.o: arg.h
doio.o: array.h
doio.o: cmd.h
doio.o: config.h
doio.o: doio.c
doio.o: embed.h
doio.o: form.h
doio.o: handy.h
doio.o: hash.h
doio.o: perl.h
doio.o: regexp.h
doio.o: spat.h
doio.o: stab.h
doio.o: str.h
doio.o: unixish.h
doio.o: util.h
dolist.o: 
dolist.o: /usr/ucbinclude/ctype.h
dolist.o: /usr/ucbinclude/dirent.h
dolist.o: /usr/ucbinclude/errno.h
dolist.o: /usr/ucbinclude/machine/param.h
dolist.o: /usr/ucbinclude/machine/setjmp.h
dolist.o: /usr/ucbinclude/ndbm.h
dolist.o: /usr/ucbinclude/netinet/in.h
dolist.o: /usr/ucbinclude/setjmp.h
dolist.o: /usr/ucbinclude/stdio.h
dolist.o: /usr/ucbinclude/sys/dirent.h
dolist.o: /usr/ucbinclude/sys/errno.h
dolist.o: /usr/ucbinclude/sys/filio.h
dolist.o: /usr/ucbinclude/sys/ioccom.h
dolist.o: /usr/ucbinclude/sys/ioctl.h
dolist.o: /usr/ucbinclude/sys/param.h
dolist.o: /usr/ucbinclude/sys/signal.h
dolist.o: /usr/ucbinclude/sys/sockio.h
dolist.o: /usr/ucbinclude/sys/stat.h
dolist.o: /usr/ucbinclude/sys/stdtypes.h
dolist.o: /usr/ucbinclude/sys/sysmacros.h
dolist.o: /usr/ucbinclude/sys/time.h
dolist.o: /usr/ucbinclude/sys/times.h
dolist.o: /usr/ucbinclude/sys/ttold.h
dolist.o: /usr/ucbinclude/sys/ttychars.h
dolist.o: /usr/ucbinclude/sys/ttycom.h
dolist.o: /usr/ucbinclude/sys/ttydev.h
dolist.o: /usr/ucbinclude/sys/types.h
dolist.o: /usr/ucbinclude/time.h
dolist.o: /usr/ucbinclude/vm/faultcode.h
dolist.o: EXTERN.h
dolist.o: arg.h
dolist.o: array.h
dolist.o: cmd.h
dolist.o: config.h
dolist.o: dolist.c
dolist.o: embed.h
dolist.o: form.h
dolist.o: handy.h
dolist.o: hash.h
dolist.o: perl.h
dolist.o: regexp.h
dolist.o: spat.h
dolist.o: stab.h
dolist.o: str.h
dolist.o: unixish.h
dolist.o: util.h
dump.o: 
dump.o: /usr/ucbinclude/ctype.h
dump.o: /usr/ucbinclude/dirent.h
dump.o: /usr/ucbinclude/errno.h
dump.o: /usr/ucbinclude/machine/param.h
dump.o: /usr/ucbinclude/machine/setjmp.h
dump.o: /usr/ucbinclude/ndbm.h
dump.o: /usr/ucbinclude/netinet/in.h
dump.o: /usr/ucbinclude/setjmp.h
dump.o: /usr/ucbinclude/stdio.h
dump.o: /usr/ucbinclude/sys/dirent.h
dump.o: /usr/ucbinclude/sys/errno.h
dump.o: /usr/ucbinclude/sys/filio.h
dump.o: /usr/ucbinclude/sys/ioccom.h
dump.o: /usr/ucbinclude/sys/ioctl.h
dump.o: /usr/ucbinclude/sys/param.h
dump.o: /usr/ucbinclude/sys/signal.h
dump.o: /usr/ucbinclude/sys/sockio.h
dump.o: /usr/ucbinclude/sys/stat.h
dump.o: /usr/ucbinclude/sys/stdtypes.h
dump.o: /usr/ucbinclude/sys/sysmacros.h
dump.o: /usr/ucbinclude/sys/time.h
dump.o: /usr/ucbinclude/sys/times.h
dump.o: /usr/ucbinclude/sys/ttold.h
dump.o: /usr/ucbinclude/sys/ttychars.h
dump.o: /usr/ucbinclude/sys/ttycom.h
dump.o: /usr/ucbinclude/sys/ttydev.h
dump.o: /usr/ucbinclude/sys/types.h
dump.o: /usr/ucbinclude/time.h
dump.o: /usr/ucbinclude/vm/faultcode.h
dump.o: EXTERN.h
dump.o: arg.h
dump.o: array.h
dump.o: cmd.h
dump.o: config.h
dump.o: dump.c
dump.o: embed.h
dump.o: form.h
dump.o: handy.h
dump.o: hash.h
dump.o: perl.h
dump.o: regexp.h
dump.o: spat.h
dump.o: stab.h
dump.o: str.h
dump.o: unixish.h
dump.o: util.h
eval.o: 
eval.o: /usr/ucbinclude/ctype.h
eval.o: /usr/ucbinclude/dirent.h
eval.o: /usr/ucbinclude/errno.h
eval.o: /usr/ucbinclude/machine/param.h
eval.o: /usr/ucbinclude/machine/setjmp.h
eval.o: /usr/ucbinclude/ndbm.h
eval.o: /usr/ucbinclude/netinet/in.h
eval.o: /usr/ucbinclude/setjmp.h
eval.o: /usr/ucbinclude/stdio.h
eval.o: /usr/ucbinclude/sys/dirent.h
eval.o: /usr/ucbinclude/sys/errno.h
eval.o: /usr/ucbinclude/sys/fcntlcom.h
eval.o: /usr/ucbinclude/sys/file.h
eval.o: /usr/ucbinclude/sys/filio.h
eval.o: /usr/ucbinclude/sys/ioccom.h
eval.o: /usr/ucbinclude/sys/ioctl.h
eval.o: /usr/ucbinclude/sys/param.h
eval.o: /usr/ucbinclude/sys/signal.h
eval.o: /usr/ucbinclude/sys/sockio.h
eval.o: /usr/ucbinclude/sys/stat.h
eval.o: /usr/ucbinclude/sys/stdtypes.h
eval.o: /usr/ucbinclude/sys/sysmacros.h
eval.o: /usr/ucbinclude/sys/time.h
eval.o: /usr/ucbinclude/sys/times.h
eval.o: /usr/ucbinclude/sys/ttold.h
eval.o: /usr/ucbinclude/sys/ttychars.h
eval.o: /usr/ucbinclude/sys/ttycom.h
eval.o: /usr/ucbinclude/sys/ttydev.h
eval.o: /usr/ucbinclude/sys/types.h
eval.o: /usr/ucbinclude/time.h
eval.o: /usr/ucbinclude/vfork.h
eval.o: /usr/ucbinclude/vm/faultcode.h
eval.o: EXTERN.h
eval.o: arg.h
eval.o: array.h
eval.o: cmd.h
eval.o: config.h
eval.o: embed.h
eval.o: eval.c
eval.o: form.h
eval.o: handy.h
eval.o: hash.h
eval.o: perl.h
eval.o: regexp.h
eval.o: spat.h
eval.o: stab.h
eval.o: str.h
eval.o: unixish.h
eval.o: util.h
form.o: 
form.o: /usr/ucbinclude/ctype.h
form.o: /usr/ucbinclude/dirent.h
form.o: /usr/ucbinclude/errno.h
form.o: /usr/ucbinclude/machine/param.h
form.o: /usr/ucbinclude/machine/setjmp.h
form.o: /usr/ucbinclude/ndbm.h
form.o: /usr/ucbinclude/netinet/in.h
form.o: /usr/ucbinclude/setjmp.h
form.o: /usr/ucbinclude/stdio.h
form.o: /usr/ucbinclude/sys/dirent.h
form.o: /usr/ucbinclude/sys/errno.h
form.o: /usr/ucbinclude/sys/filio.h
form.o: /usr/ucbinclude/sys/ioccom.h
form.o: /usr/ucbinclude/sys/ioctl.h
form.o: /usr/ucbinclude/sys/param.h
form.o: /usr/ucbinclude/sys/signal.h
form.o: /usr/ucbinclude/sys/sockio.h
form.o: /usr/ucbinclude/sys/stat.h
form.o: /usr/ucbinclude/sys/stdtypes.h
form.o: /usr/ucbinclude/sys/sysmacros.h
form.o: /usr/ucbinclude/sys/time.h
form.o: /usr/ucbinclude/sys/times.h
form.o: /usr/ucbinclude/sys/ttold.h
form.o: /usr/ucbinclude/sys/ttychars.h
form.o: /usr/ucbinclude/sys/ttycom.h
form.o: /usr/ucbinclude/sys/ttydev.h
form.o: /usr/ucbinclude/sys/types.h
form.o: /usr/ucbinclude/time.h
form.o: /usr/ucbinclude/vm/faultcode.h
form.o: EXTERN.h
form.o: arg.h
form.o: array.h
form.o: cmd.h
form.o: config.h
form.o: embed.h
form.o: form.c
form.o: form.h
form.o: handy.h
form.o: hash.h
form.o: perl.h
form.o: regexp.h
form.o: spat.h
form.o: stab.h
form.o: str.h
form.o: unixish.h
form.o: util.h
hash.o: 
hash.o: /usr/ucbinclude/ctype.h
hash.o: /usr/ucbinclude/dirent.h
hash.o: /usr/ucbinclude/errno.h
hash.o: /usr/ucbinclude/machine/param.h
hash.o: /usr/ucbinclude/machine/setjmp.h
hash.o: /usr/ucbinclude/ndbm.h
hash.o: /usr/ucbinclude/netinet/in.h
hash.o: /usr/ucbinclude/setjmp.h
hash.o: /usr/ucbinclude/stdio.h
hash.o: /usr/ucbinclude/sys/dirent.h
hash.o: /usr/ucbinclude/sys/errno.h
hash.o: /usr/ucbinclude/sys/fcntlcom.h
hash.o: /usr/ucbinclude/sys/file.h
hash.o: /usr/ucbinclude/sys/filio.h
hash.o: /usr/ucbinclude/sys/ioccom.h
hash.o: /usr/ucbinclude/sys/ioctl.h
hash.o: /usr/ucbinclude/sys/param.h
hash.o: /usr/ucbinclude/sys/signal.h
hash.o: /usr/ucbinclude/sys/sockio.h
hash.o: /usr/ucbinclude/sys/stat.h
hash.o: /usr/ucbinclude/sys/stdtypes.h
hash.o: /usr/ucbinclude/sys/sysmacros.h
hash.o: /usr/ucbinclude/sys/time.h
hash.o: /usr/ucbinclude/sys/times.h
hash.o: /usr/ucbinclude/sys/ttold.h
hash.o: /usr/ucbinclude/sys/ttychars.h
hash.o: /usr/ucbinclude/sys/ttycom.h
hash.o: /usr/ucbinclude/sys/ttydev.h
hash.o: /usr/ucbinclude/sys/types.h
hash.o: /usr/ucbinclude/time.h
hash.o: /usr/ucbinclude/vm/faultcode.h
hash.o: EXTERN.h
hash.o: arg.h
hash.o: array.h
hash.o: cmd.h
hash.o: config.h
hash.o: embed.h
hash.o: form.h
hash.o: handy.h
hash.o: hash.c
hash.o: hash.h
hash.o: perl.h
hash.o: regexp.h
hash.o: spat.h
hash.o: stab.h
hash.o: str.h
hash.o: unixish.h
hash.o: util.h
main.o: 
main.o: /usr/ucbinclude/ctype.h
main.o: /usr/ucbinclude/dirent.h
main.o: /usr/ucbinclude/errno.h
main.o: /usr/ucbinclude/machine/param.h
main.o: /usr/ucbinclude/machine/setjmp.h
main.o: /usr/ucbinclude/ndbm.h
main.o: /usr/ucbinclude/netinet/in.h
main.o: /usr/ucbinclude/setjmp.h
main.o: /usr/ucbinclude/stdio.h
main.o: /usr/ucbinclude/sys/dirent.h
main.o: /usr/ucbinclude/sys/errno.h
main.o: /usr/ucbinclude/sys/filio.h
main.o: /usr/ucbinclude/sys/ioccom.h
main.o: /usr/ucbinclude/sys/ioctl.h
main.o: /usr/ucbinclude/sys/param.h
main.o: /usr/ucbinclude/sys/signal.h
main.o: /usr/ucbinclude/sys/sockio.h
main.o: /usr/ucbinclude/sys/stat.h
main.o: /usr/ucbinclude/sys/stdtypes.h
main.o: /usr/ucbinclude/sys/sysmacros.h
main.o: /usr/ucbinclude/sys/time.h
main.o: /usr/ucbinclude/sys/times.h
main.o: /usr/ucbinclude/sys/ttold.h
main.o: /usr/ucbinclude/sys/ttychars.h
main.o: /usr/ucbinclude/sys/ttycom.h
main.o: /usr/ucbinclude/sys/ttydev.h
main.o: /usr/ucbinclude/sys/types.h
main.o: /usr/ucbinclude/time.h
main.o: /usr/ucbinclude/vm/faultcode.h
main.o: INTERN.h
main.o: arg.h
main.o: array.h
main.o: cmd.h
main.o: config.h
main.o: embed.h
main.o: form.h
main.o: handy.h
main.o: hash.h
main.o: main.c
main.o: perl.h
main.o: regexp.h
main.o: spat.h
main.o: stab.h
main.o: str.h
main.o: unixish.h
main.o: util.h
malloc.o: 
malloc.o: /usr/ucbinclude/ctype.h
malloc.o: /usr/ucbinclude/dirent.h
malloc.o: /usr/ucbinclude/errno.h
malloc.o: /usr/ucbinclude/machine/param.h
malloc.o: /usr/ucbinclude/machine/setjmp.h
malloc.o: /usr/ucbinclude/ndbm.h
malloc.o: /usr/ucbinclude/netinet/in.h
malloc.o: /usr/ucbinclude/setjmp.h
malloc.o: /usr/ucbinclude/stdio.h
malloc.o: /usr/ucbinclude/sys/dirent.h
malloc.o: /usr/ucbinclude/sys/errno.h
malloc.o: /usr/ucbinclude/sys/filio.h
malloc.o: /usr/ucbinclude/sys/ioccom.h
malloc.o: /usr/ucbinclude/sys/ioctl.h
malloc.o: /usr/ucbinclude/sys/param.h
malloc.o: /usr/ucbinclude/sys/signal.h
malloc.o: /usr/ucbinclude/sys/sockio.h
malloc.o: /usr/ucbinclude/sys/stat.h
malloc.o: /usr/ucbinclude/sys/stdtypes.h
malloc.o: /usr/ucbinclude/sys/sysmacros.h
malloc.o: /usr/ucbinclude/sys/time.h
malloc.o: /usr/ucbinclude/sys/times.h
malloc.o: /usr/ucbinclude/sys/ttold.h
malloc.o: /usr/ucbinclude/sys/ttychars.h
malloc.o: /usr/ucbinclude/sys/ttycom.h
malloc.o: /usr/ucbinclude/sys/ttydev.h
malloc.o: /usr/ucbinclude/sys/types.h
malloc.o: /usr/ucbinclude/time.h
malloc.o: /usr/ucbinclude/vm/faultcode.h
malloc.o: EXTERN.h
malloc.o: arg.h
malloc.o: array.h
malloc.o: cmd.h
malloc.o: config.h
malloc.o: embed.h
malloc.o: form.h
malloc.o: handy.h
malloc.o: hash.h
malloc.o: malloc.c
malloc.o: perl.h
malloc.o: regexp.h
malloc.o: spat.h
malloc.o: stab.h
malloc.o: str.h
malloc.o: unixish.h
malloc.o: util.h
perl.o: 
perl.o: /usr/ucbinclude/ctype.h
perl.o: /usr/ucbinclude/dirent.h
perl.o: /usr/ucbinclude/errno.h
perl.o: /usr/ucbinclude/machine/param.h
perl.o: /usr/ucbinclude/machine/setjmp.h
perl.o: /usr/ucbinclude/ndbm.h
perl.o: /usr/ucbinclude/netinet/in.h
perl.o: /usr/ucbinclude/setjmp.h
perl.o: /usr/ucbinclude/stdio.h
perl.o: /usr/ucbinclude/sys/dirent.h
perl.o: /usr/ucbinclude/sys/errno.h
perl.o: /usr/ucbinclude/sys/filio.h
perl.o: /usr/ucbinclude/sys/ioccom.h
perl.o: /usr/ucbinclude/sys/ioctl.h
perl.o: /usr/ucbinclude/sys/param.h
perl.o: /usr/ucbinclude/sys/signal.h
perl.o: /usr/ucbinclude/sys/sockio.h
perl.o: /usr/ucbinclude/sys/stat.h
perl.o: /usr/ucbinclude/sys/stdtypes.h
perl.o: /usr/ucbinclude/sys/sysmacros.h
perl.o: /usr/ucbinclude/sys/time.h
perl.o: /usr/ucbinclude/sys/times.h
perl.o: /usr/ucbinclude/sys/ttold.h
perl.o: /usr/ucbinclude/sys/ttychars.h
perl.o: /usr/ucbinclude/sys/ttycom.h
perl.o: /usr/ucbinclude/sys/ttydev.h
perl.o: /usr/ucbinclude/sys/types.h
perl.o: /usr/ucbinclude/time.h
perl.o: /usr/ucbinclude/vm/faultcode.h
perl.o: EXTERN.h
perl.o: arg.h
perl.o: array.h
perl.o: cmd.h
perl.o: config.h
perl.o: embed.h
perl.o: form.h
perl.o: handy.h
perl.o: hash.h
perl.o: patchlevel.h
perl.o: perl.c
perl.o: perl.h
perl.o: perly.h
perl.o: regexp.h
perl.o: spat.h
perl.o: stab.h
perl.o: str.h
perl.o: unixish.h
perl.o: util.h
pp.o: EXTERN.h
pp.o: arg.h
pp.o: array.h
pp.o: cmd.h
pp.o: config.h
pp.o: embed.h
pp.o: pp.c
pp.o: pp.h
pp.o: form.h
pp.o: handy.h
pp.o: hash.h
pp.o: perl.h
pp.o: regexp.h
pp.o: spat.h
pp.o: stab.h
pp.o: str.h
pp.o: unixish.h
pp.o: util.h
regcomp.o: 
regcomp.o: /usr/ucbinclude/ctype.h
regcomp.o: /usr/ucbinclude/dirent.h
regcomp.o: /usr/ucbinclude/errno.h
regcomp.o: /usr/ucbinclude/machine/param.h
regcomp.o: /usr/ucbinclude/machine/setjmp.h
regcomp.o: /usr/ucbinclude/ndbm.h
regcomp.o: /usr/ucbinclude/netinet/in.h
regcomp.o: /usr/ucbinclude/setjmp.h
regcomp.o: /usr/ucbinclude/stdio.h
regcomp.o: /usr/ucbinclude/sys/dirent.h
regcomp.o: /usr/ucbinclude/sys/errno.h
regcomp.o: /usr/ucbinclude/sys/filio.h
regcomp.o: /usr/ucbinclude/sys/ioccom.h
regcomp.o: /usr/ucbinclude/sys/ioctl.h
regcomp.o: /usr/ucbinclude/sys/param.h
regcomp.o: /usr/ucbinclude/sys/signal.h
regcomp.o: /usr/ucbinclude/sys/sockio.h
regcomp.o: /usr/ucbinclude/sys/stat.h
regcomp.o: /usr/ucbinclude/sys/stdtypes.h
regcomp.o: /usr/ucbinclude/sys/sysmacros.h
regcomp.o: /usr/ucbinclude/sys/time.h
regcomp.o: /usr/ucbinclude/sys/times.h
regcomp.o: /usr/ucbinclude/sys/ttold.h
regcomp.o: /usr/ucbinclude/sys/ttychars.h
regcomp.o: /usr/ucbinclude/sys/ttycom.h
regcomp.o: /usr/ucbinclude/sys/ttydev.h
regcomp.o: /usr/ucbinclude/sys/types.h
regcomp.o: /usr/ucbinclude/time.h
regcomp.o: /usr/ucbinclude/vm/faultcode.h
regcomp.o: EXTERN.h
regcomp.o: INTERN.h
regcomp.o: arg.h
regcomp.o: array.h
regcomp.o: cmd.h
regcomp.o: config.h
regcomp.o: embed.h
regcomp.o: form.h
regcomp.o: handy.h
regcomp.o: hash.h
regcomp.o: perl.h
regcomp.o: regcomp.c
regcomp.o: regcomp.h
regcomp.o: regexp.h
regcomp.o: spat.h
regcomp.o: stab.h
regcomp.o: str.h
regcomp.o: unixish.h
regcomp.o: util.h
regexec.o: 
regexec.o: /usr/ucbinclude/ctype.h
regexec.o: /usr/ucbinclude/dirent.h
regexec.o: /usr/ucbinclude/errno.h
regexec.o: /usr/ucbinclude/machine/param.h
regexec.o: /usr/ucbinclude/machine/setjmp.h
regexec.o: /usr/ucbinclude/ndbm.h
regexec.o: /usr/ucbinclude/netinet/in.h
regexec.o: /usr/ucbinclude/setjmp.h
regexec.o: /usr/ucbinclude/stdio.h
regexec.o: /usr/ucbinclude/sys/dirent.h
regexec.o: /usr/ucbinclude/sys/errno.h
regexec.o: /usr/ucbinclude/sys/filio.h
regexec.o: /usr/ucbinclude/sys/ioccom.h
regexec.o: /usr/ucbinclude/sys/ioctl.h
regexec.o: /usr/ucbinclude/sys/param.h
regexec.o: /usr/ucbinclude/sys/signal.h
regexec.o: /usr/ucbinclude/sys/sockio.h
regexec.o: /usr/ucbinclude/sys/stat.h
regexec.o: /usr/ucbinclude/sys/stdtypes.h
regexec.o: /usr/ucbinclude/sys/sysmacros.h
regexec.o: /usr/ucbinclude/sys/time.h
regexec.o: /usr/ucbinclude/sys/times.h
regexec.o: /usr/ucbinclude/sys/ttold.h
regexec.o: /usr/ucbinclude/sys/ttychars.h
regexec.o: /usr/ucbinclude/sys/ttycom.h
regexec.o: /usr/ucbinclude/sys/ttydev.h
regexec.o: /usr/ucbinclude/sys/types.h
regexec.o: /usr/ucbinclude/time.h
regexec.o: /usr/ucbinclude/vm/faultcode.h
regexec.o: EXTERN.h
regexec.o: arg.h
regexec.o: array.h
regexec.o: cmd.h
regexec.o: config.h
regexec.o: embed.h
regexec.o: form.h
regexec.o: handy.h
regexec.o: hash.h
regexec.o: perl.h
regexec.o: regcomp.h
regexec.o: regexec.c
regexec.o: regexp.h
regexec.o: spat.h
regexec.o: stab.h
regexec.o: str.h
regexec.o: unixish.h
regexec.o: util.h
stab.o: 
stab.o: /usr/ucbinclude/ctype.h
stab.o: /usr/ucbinclude/dirent.h
stab.o: /usr/ucbinclude/errno.h
stab.o: /usr/ucbinclude/machine/param.h
stab.o: /usr/ucbinclude/machine/setjmp.h
stab.o: /usr/ucbinclude/ndbm.h
stab.o: /usr/ucbinclude/netinet/in.h
stab.o: /usr/ucbinclude/setjmp.h
stab.o: /usr/ucbinclude/stdio.h
stab.o: /usr/ucbinclude/sys/dirent.h
stab.o: /usr/ucbinclude/sys/errno.h
stab.o: /usr/ucbinclude/sys/filio.h
stab.o: /usr/ucbinclude/sys/ioccom.h
stab.o: /usr/ucbinclude/sys/ioctl.h
stab.o: /usr/ucbinclude/sys/param.h
stab.o: /usr/ucbinclude/sys/signal.h
stab.o: /usr/ucbinclude/sys/sockio.h
stab.o: /usr/ucbinclude/sys/stat.h
stab.o: /usr/ucbinclude/sys/stdtypes.h
stab.o: /usr/ucbinclude/sys/sysmacros.h
stab.o: /usr/ucbinclude/sys/time.h
stab.o: /usr/ucbinclude/sys/times.h
stab.o: /usr/ucbinclude/sys/ttold.h
stab.o: /usr/ucbinclude/sys/ttychars.h
stab.o: /usr/ucbinclude/sys/ttycom.h
stab.o: /usr/ucbinclude/sys/ttydev.h
stab.o: /usr/ucbinclude/sys/types.h
stab.o: /usr/ucbinclude/time.h
stab.o: /usr/ucbinclude/vm/faultcode.h
stab.o: EXTERN.h
stab.o: arg.h
stab.o: array.h
stab.o: cmd.h
stab.o: config.h
stab.o: embed.h
stab.o: form.h
stab.o: handy.h
stab.o: hash.h
stab.o: perl.h
stab.o: regexp.h
stab.o: spat.h
stab.o: stab.c
stab.o: stab.h
stab.o: str.h
stab.o: unixish.h
stab.o: util.h
str.o: 
str.o: /usr/ucbinclude/ctype.h
str.o: /usr/ucbinclude/dirent.h
str.o: /usr/ucbinclude/errno.h
str.o: /usr/ucbinclude/machine/param.h
str.o: /usr/ucbinclude/machine/setjmp.h
str.o: /usr/ucbinclude/ndbm.h
str.o: /usr/ucbinclude/netinet/in.h
str.o: /usr/ucbinclude/setjmp.h
str.o: /usr/ucbinclude/stdio.h
str.o: /usr/ucbinclude/sys/dirent.h
str.o: /usr/ucbinclude/sys/errno.h
str.o: /usr/ucbinclude/sys/filio.h
str.o: /usr/ucbinclude/sys/ioccom.h
str.o: /usr/ucbinclude/sys/ioctl.h
str.o: /usr/ucbinclude/sys/param.h
str.o: /usr/ucbinclude/sys/signal.h
str.o: /usr/ucbinclude/sys/sockio.h
str.o: /usr/ucbinclude/sys/stat.h
str.o: /usr/ucbinclude/sys/stdtypes.h
str.o: /usr/ucbinclude/sys/sysmacros.h
str.o: /usr/ucbinclude/sys/time.h
str.o: /usr/ucbinclude/sys/times.h
str.o: /usr/ucbinclude/sys/ttold.h
str.o: /usr/ucbinclude/sys/ttychars.h
str.o: /usr/ucbinclude/sys/ttycom.h
str.o: /usr/ucbinclude/sys/ttydev.h
str.o: /usr/ucbinclude/sys/types.h
str.o: /usr/ucbinclude/time.h
str.o: /usr/ucbinclude/vm/faultcode.h
str.o: EXTERN.h
str.o: arg.h
str.o: array.h
str.o: cmd.h
str.o: config.h
str.o: embed.h
str.o: form.h
str.o: handy.h
str.o: hash.h
str.o: perl.h
str.o: perly.h
str.o: regexp.h
str.o: spat.h
str.o: stab.h
str.o: str.c
str.o: str.h
str.o: unixish.h
str.o: util.h
toke.o: 
toke.o: /usr/ucbinclude/ctype.h
toke.o: /usr/ucbinclude/dirent.h
toke.o: /usr/ucbinclude/errno.h
toke.o: /usr/ucbinclude/machine/param.h
toke.o: /usr/ucbinclude/machine/setjmp.h
toke.o: /usr/ucbinclude/ndbm.h
toke.o: /usr/ucbinclude/netinet/in.h
toke.o: /usr/ucbinclude/setjmp.h
toke.o: /usr/ucbinclude/stdio.h
toke.o: /usr/ucbinclude/sys/dirent.h
toke.o: /usr/ucbinclude/sys/errno.h
toke.o: /usr/ucbinclude/sys/fcntlcom.h
toke.o: /usr/ucbinclude/sys/file.h
toke.o: /usr/ucbinclude/sys/filio.h
toke.o: /usr/ucbinclude/sys/ioccom.h
toke.o: /usr/ucbinclude/sys/ioctl.h
toke.o: /usr/ucbinclude/sys/param.h
toke.o: /usr/ucbinclude/sys/signal.h
toke.o: /usr/ucbinclude/sys/sockio.h
toke.o: /usr/ucbinclude/sys/stat.h
toke.o: /usr/ucbinclude/sys/stdtypes.h
toke.o: /usr/ucbinclude/sys/sysmacros.h
toke.o: /usr/ucbinclude/sys/time.h
toke.o: /usr/ucbinclude/sys/times.h
toke.o: /usr/ucbinclude/sys/ttold.h
toke.o: /usr/ucbinclude/sys/ttychars.h
toke.o: /usr/ucbinclude/sys/ttycom.h
toke.o: /usr/ucbinclude/sys/ttydev.h
toke.o: /usr/ucbinclude/sys/types.h
toke.o: /usr/ucbinclude/time.h
toke.o: /usr/ucbinclude/vm/faultcode.h
toke.o: EXTERN.h
toke.o: arg.h
toke.o: array.h
toke.o: cmd.h
toke.o: config.h
toke.o: embed.h
toke.o: form.h
toke.o: handy.h
toke.o: hash.h
toke.o: keywords.h
toke.o: perl.h
toke.o: perly.h
toke.o: regexp.h
toke.o: spat.h
toke.o: stab.h
toke.o: str.h
toke.o: toke.c
toke.o: unixish.h
toke.o: util.h
util.o: 
util.o: /usr/ucbinclude/ctype.h
util.o: /usr/ucbinclude/dirent.h
util.o: /usr/ucbinclude/errno.h
util.o: /usr/ucbinclude/machine/param.h
util.o: /usr/ucbinclude/machine/setjmp.h
util.o: /usr/ucbinclude/ndbm.h
util.o: /usr/ucbinclude/netinet/in.h
util.o: /usr/ucbinclude/setjmp.h
util.o: /usr/ucbinclude/stdio.h
util.o: /usr/ucbinclude/sys/dirent.h
util.o: /usr/ucbinclude/sys/errno.h
util.o: /usr/ucbinclude/sys/fcntlcom.h
util.o: /usr/ucbinclude/sys/file.h
util.o: /usr/ucbinclude/sys/filio.h
util.o: /usr/ucbinclude/sys/ioccom.h
util.o: /usr/ucbinclude/sys/ioctl.h
util.o: /usr/ucbinclude/sys/param.h
util.o: /usr/ucbinclude/sys/signal.h
util.o: /usr/ucbinclude/sys/sockio.h
util.o: /usr/ucbinclude/sys/stat.h
util.o: /usr/ucbinclude/sys/stdtypes.h
util.o: /usr/ucbinclude/sys/sysmacros.h
util.o: /usr/ucbinclude/sys/time.h
util.o: /usr/ucbinclude/sys/times.h
util.o: /usr/ucbinclude/sys/ttold.h
util.o: /usr/ucbinclude/sys/ttychars.h
util.o: /usr/ucbinclude/sys/ttycom.h
util.o: /usr/ucbinclude/sys/ttydev.h
util.o: /usr/ucbinclude/sys/types.h
util.o: /usr/ucbinclude/time.h
util.o: /usr/ucbinclude/varargs.h
util.o: /usr/ucbinclude/vfork.h
util.o: /usr/ucbinclude/vm/faultcode.h
util.o: EXTERN.h
util.o: arg.h
util.o: array.h
util.o: cmd.h
util.o: config.h
util.o: embed.h
util.o: form.h
util.o: handy.h
util.o: hash.h
util.o: perl.h
util.o: regexp.h
util.o: spat.h
util.o: stab.h
util.o: str.h
util.o: unixish.h
util.o: util.c
util.o: util.h
usersub.o: 
usersub.o: /usr/ucbinclude/ctype.h
usersub.o: /usr/ucbinclude/dirent.h
usersub.o: /usr/ucbinclude/errno.h
usersub.o: /usr/ucbinclude/machine/param.h
usersub.o: /usr/ucbinclude/machine/setjmp.h
usersub.o: /usr/ucbinclude/ndbm.h
usersub.o: /usr/ucbinclude/netinet/in.h
usersub.o: /usr/ucbinclude/setjmp.h
usersub.o: /usr/ucbinclude/stdio.h
usersub.o: /usr/ucbinclude/sys/dirent.h
usersub.o: /usr/ucbinclude/sys/errno.h
usersub.o: /usr/ucbinclude/sys/filio.h
usersub.o: /usr/ucbinclude/sys/ioccom.h
usersub.o: /usr/ucbinclude/sys/ioctl.h
usersub.o: /usr/ucbinclude/sys/param.h
usersub.o: /usr/ucbinclude/sys/signal.h
usersub.o: /usr/ucbinclude/sys/sockio.h
usersub.o: /usr/ucbinclude/sys/stat.h
usersub.o: /usr/ucbinclude/sys/stdtypes.h
usersub.o: /usr/ucbinclude/sys/sysmacros.h
usersub.o: /usr/ucbinclude/sys/time.h
usersub.o: /usr/ucbinclude/sys/times.h
usersub.o: /usr/ucbinclude/sys/ttold.h
usersub.o: /usr/ucbinclude/sys/ttychars.h
usersub.o: /usr/ucbinclude/sys/ttycom.h
usersub.o: /usr/ucbinclude/sys/ttydev.h
usersub.o: /usr/ucbinclude/sys/types.h
usersub.o: /usr/ucbinclude/time.h
usersub.o: /usr/ucbinclude/vm/faultcode.h
usersub.o: EXTERN.h
usersub.o: arg.h
usersub.o: array.h
usersub.o: cmd.h
usersub.o: config.h
usersub.o: embed.h
usersub.o: form.h
usersub.o: handy.h
usersub.o: hash.h
usersub.o: perl.h
usersub.o: regexp.h
usersub.o: spat.h
usersub.o: stab.h
usersub.o: str.h
usersub.o: unixish.h
usersub.o: usersub.c
usersub.o: util.h
Makefile: Makefile.SH config.sh ; /bin/sh Makefile.SH
makedepend: makedepend.SH config.sh ; /bin/sh makedepend.SH
h2ph: h2ph.SH config.sh ; /bin/sh h2ph.SH
# WARNING: Put nothing here or make depend will gobble it up!
