name: perl
version: 5.011000
abstract: Practical Extraction and Report Language
author: perl5-porters@perl.org
license: perl
resources:
  homepage: http://www.perl.org/
  bugtracker: http://rt.perl.org/perlbug/
  license: http://dev.perl.org/licenses/
distribution_type: core
generated_by: Porting/makemeta
no_index:
  directory:
    - cpan/Archive-Extract
    - cpan/Archive-Tar
    - cpan/autodie
    - cpan/AutoLoader
    - cpan/B-Debug
    - cpan/B-Lint
    - cpan/bignum
    - cpan/CGI
    - cpan/Class-ISA
    - cpan/Compress-Raw-Bzip2
    - cpan/Compress-Raw-Zlib
    - cpan/CPAN
    - cpan/CPANPLUS
    - cpan/CPANPLUS-Dist-Build
    - cpan/Cwd
    - cpan/DB_File
    - cpan/Devel-PPPort
    - cpan/Digest
    - cpan/Digest-MD5
    - cpan/Digest-SHA
    - cpan/Encode
    - cpan/encoding-warnings
    - cpan/ExtUtils-CBuilder
    - cpan/ExtUtils-Command
    - cpan/ExtUtils-MakeMaker
    - cpan/ExtUtils-Manifest
    - cpan/ExtUtils-ParseXS
    - cpan/File-Fetch
    - cpan/File-Path
    - cpan/File-Temp
    - cpan/Filter-Util-Call
    - cpan/Getopt-Long
    - cpan/IPC-Cmd
    - cpan/IPC-SysV
    - cpan/Log-Message
    - cpan/Log-Message-Simple
    - cpan/Math-Complex
    - cpan/Module-Build
    - cpan/Module-Load
    - cpan/Module-Load-Conditional
    - cpan/Module-Loaded
    - cpan/NEXT
    - cpan/Object-Accessor
    - cpan/Package-Constants
    - cpan/Params-Check
    - cpan/Parse-CPAN-Meta
    - cpan/podlators
    - cpan/Sys-Syslog
    - cpan/Term-ANSIColor
    - cpan/Term-UI
    - cpan/Test
    - cpan/Text-Tabs
    - cpan/Tie-RefHash
    - cpan/Unicode-Collate
    - cpan/Unicode-Normalize
    - dist/Attribute-Handlers
    - dist/base
    - dist/constant
    - dist/Data-Dumper
    - dist/ExtUtils-Install
    - dist/Filter-Simple
    - dist/IO/
    - dist/lib/
    - dist/Locale-Maketext
    - dist/Locale-Maketext-Simple
    - dist/Module-CoreList
    - dist/Net-Ping
    - dist/Pod-Perldoc
    - dist/Pod-Plainer
    - dist/Safe
    - dist/Switch
    - dist/Thread-Queue
    - dist/Thread-Semaphore
    - dist/threads
    - dist/threads-shared
    - dist/XSLoader
    - ext/ExtUtils-Constant
    - ext/if
    - ext/IO-Compress
    - ext/IO-Zlib
    - ext/libnet
    - ext/List-Util
    - ext/Locale-Codes
    - ext/Math-BigInt
    - ext/Math-BigInt-FastCalc
    - ext/Math-BigRat
    - ext/Memoize
    - ext/MIME-Base64
    - ext/Module-Pluggable
    - ext/parent
    - ext/PerlIO-via-QuotedPrint
    - ext/Pod-Escapes
    - ext/Pod-LaTeX
    - ext/Pod-Parser
    - ext/Pod-Simple
    - ext/Shell
    - ext/Storable
    - ext/Term-Cap
    - ext/Test-Harness
    - ext/Test-Simple
    - ext/Text-Balanced
    - ext/Text-ParseWords
    - ext/Text-Soundex
    - ext/Tie-File
    - ext/Time-HiRes
    - ext/Time-Local
    - ext/Time-Piece
    - ext/Win32
    - ext/Win32API-File
    - lib/version

  file:
    - dist/IO/ChangeLog
    - dist/IO/hints/sco.pl
    - dist/IO/IO.pm
    - dist/IO/IO.xs
    - dist/IO/lib/IO/Dir.pm
    - dist/IO/lib/IO/File.pm
    - dist/IO/lib/IO/Handle.pm
    - dist/IO/lib/IO/Pipe.pm
    - dist/IO/lib/IO/Poll.pm
    - dist/IO/lib/IO/Seekable.pm
    - dist/IO/lib/IO/Select.pm
    - dist/IO/lib/IO/Socket.pm
    - dist/IO/lib/IO/Socket/INET.pm
    - dist/IO/lib/IO/Socket/UNIX.pm
    - dist/IO/Makefile.PL
    - dist/IO/poll.c
    - dist/IO/poll.h
    - dist/IO/README
    - dist/IO/t/IO.t
    - dist/IO/t/io_const.t
    - dist/IO/t/io_dir.t
    - dist/IO/t/io_dup.t
    - dist/IO/t/io_file.t
    - dist/IO/t/io_linenum.t
    - dist/IO/t/io_multihomed.t
    - dist/IO/t/io_pipe.t
    - dist/IO/t/io_poll.t
    - dist/IO/t/io_sel.t
    - dist/IO/t/io_sock.t
    - dist/IO/t/io_taint.t
    - dist/IO/t/io_tell.t
    - dist/IO/t/io_udp.t
    - dist/IO/t/io_unix.t
    - dist/IO/t/io_utf8.t
    - dist/IO/t/io_xs.t
    - dist/lib/lib_pm.PL
    - dist/lib/Makefile.PL
    - dist/lib/t/01lib.t
    - lib/Exporter.pm
    - lib/Exporter.t
    - lib/Exporter/Heavy.pm
    - lib/newgetopt.pl
    - lib/version.pm
    - lib/version.pod
    - lib/version.t
    - pod/perldoc.pod
    - pod/perlfilter.pod
    - pod/pod2latex.PL
    - pod/pod2man.PL
    - pod/pod2text.PL
    - pod/pod2usage.PL
    - pod/podchecker.PL
    - pod/podselect.PL

