#!./perl

package OBJ;

@ISA = BASEOBJ;

$main'object = bless {FOO => foo, BAR => bar};

package main;

$object->mymethod("BAR");

mymethod $object "FOO";

#&mymethod($object, "BAR");

sub BASEOBJ'mymethod {
    local $ref = shift;
    print ref $ref, "\n";
    print $ref->{shift}, "\n";
}
