/*  -*- buffer-read-only: t -*-
 *
 *    regcharclass.h
 *
 *    Copyright (C) 2007, by Larry Wall and others
 *
 *    You may distribute under the terms of either the GNU General Public
 *    License or the Artistic License, as specified in the README file.
 *
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by Porting/regcharclass.pl.
 * (Generated at: Mon Apr 23 15:30:51 2007 GMT)
 * Any changes made here will be lost!
 */

/*
	LNBREAK: Line Break: \R

	"\x0D\x0A"      # CRLF - Network (Windows) line ending
	0x0A            # LF  | LINE FEED
	0x0B            # VT  | VERTICAL TAB
	0x0C            # FF  | FORM FEED
	0x0D            # CR  | CARRIAGE RETURN
	0x85            # NEL | NEXT LINE
	0x2028          # LINE SEPARATOR
	0x2029          # PARAGRAPH SEPARATOR
*/
/*** GENERATED CODE ***/
#define is_LNBREAK(s,is_utf8)                                               \
( ( ((U8*)s)[0] == 0x0D ) ?                                                 \
    ( ( ((U8*)s)[1] == 0x0A ) ? 2 : 1 ) :                                   \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0C) ? 1 :                      \
( (is_utf8) ?                                                               \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  (((( ((U8*)s)[0] == 0xE2 ) && ( ((U8*)s)[1] == 0x80 )) && ( ((U8*)s)[2] == 0xA8 || ((U8*)s)[2] == 0xA9 )) ? 3 : 0) ) :\
  ( ((U8*)s)[0] == 0x85 ) ) ) )

/*** GENERATED CODE ***/
#define is_LNBREAK_safe(s,e,is_utf8)                                        \
( ( (e) - (s) > 2 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0x0D ) ?                                               \
    ( ( ((U8*)s)[1] == 0x0A ) ? 2 : 1 ) :                                   \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0C) ? 1 :                      \
( (is_utf8) ?                                                               \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  (((( ((U8*)s)[0] == 0xE2 ) && ( ((U8*)s)[1] == 0x80 )) && ( ((U8*)s)[2] == 0xA8 || ((U8*)s)[2] == 0xA9 )) ? 3 : 0) ) :\
  ( ((U8*)s)[0] == 0x85 ) ) ) ) :                                           \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0x0D ) ?                                               \
    ( ( ((U8*)s)[1] == 0x0A ) ? 2 : 1 ) :                                   \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0C) ? 1 :                      \
( (is_utf8) ?                                                               \
  ((( ((U8*)s)[0] == 0xC2 ) && ( ((U8*)s)[1] == 0x85 )) ? 2 : 0) :          \
  ( ((U8*)s)[0] == 0x85 ) ) ) ) :                                           \
( ( (e) - (s) > 0 ) ?                                                       \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) ? 1 :                      \
( (!is_utf8) ?                                                              \
  ( ((U8*)s)[0] == 0x85 ) : 0 ) ) : 0 ) ) )

/*** GENERATED CODE ***/
#define is_LNBREAK_utf8(s)                                                  \
( ( ((U8*)s)[0] == 0xC2 ) ?                                                 \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0xE2 ) ?                                               \
    ((( ((U8*)s)[1] == 0x80 ) && ( ((U8*)s)[2] == 0xA8 || ((U8*)s)[2] == 0xA9 )) ? 3 : 0) :\
  ( ( ((U8*)s)[0] == 0x0D ) ?                                               \
    ( ( ((U8*)s)[1] == 0x0A ) ? 2 : 1 ) :                                   \
  (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0C) ) ) )

/*** GENERATED CODE ***/
#define is_LNBREAK_utf8_safe(s,e)                                           \
( ( (e) - (s) > 2 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0xE2 ) ?                                               \
    ((( ((U8*)s)[1] == 0x80 ) && ( ((U8*)s)[2] == 0xA8 || ((U8*)s)[2] == 0xA9 )) ? 3 : 0) :\
  ( ( ((U8*)s)[0] == 0x0D ) ?                                               \
    ( ( ((U8*)s)[1] == 0x0A ) ? 2 : 1 ) :                                   \
  (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0C) ) ) ) :                      \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0x0D ) ?                                               \
    ( ( ((U8*)s)[1] == 0x0A ) ? 2 : 1 ) :                                   \
  (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0C) ) ) :                        \
( ( (e) - (s) > 0 ) ?                                                       \
  (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) : 0 ) ) )

/*** GENERATED CODE ***/
#define is_LNBREAK_latin1(s)                                                \
( ( ((U8*)s)[0] == 0x0D ) ?                                                 \
    ( ( ((U8*)s)[1] == 0x0A ) ? 2 : 1 ) :                                   \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0C) || ((U8*)s)[0] == 0x85 ) )

/*** GENERATED CODE ***/
#define is_LNBREAK_latin1_safe(s,e)                                         \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0x0D ) ?                                               \
    ( ( ((U8*)s)[1] == 0x0A ) ? 2 : 1 ) :                                   \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0C) || ((U8*)s)[0] == 0x85 ) ) :\
( ( (e) - (s) > 0 ) ?                                                       \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) || ((U8*)s)[0] == 0x85 ) : 0 ) )

/*** GENERATED CODE ***/
#define is_LNBREAK_cp(cp)                                                   \
( (0x0A <= cp && cp <= 0x0D) || ( cp > 13 &&                                \
( cp == 0x85 || ( cp > 133 &&                                               \
( cp == 0x2028 || ( cp > 8232 &&                                            \
cp == 0x2029 ) ) ) ) ) )

/*
	HORIZWS: Horizontal Whitespace: \h \H

	0x09            # HT
	0x20            # SPACE
	0xa0            # NBSP
	0x1680          # OGHAM SPACE MARK
	0x180e          # MONGOLIAN VOWEL SEPARATOR
	0x2000          # EN QUAD
	0x2001          # EM QUAD
	0x2002          # EN SPACE
	0x2003          # EM SPACE
	0x2004          # THREE-PER-EM SPACE
	0x2005          # FOUR-PER-EM SPACE
	0x2006          # SIX-PER-EM SPACE
	0x2007          # FIGURE SPACE
	0x2008          # PUNCTUATION SPACE
	0x2009          # THIN SPACE
	0x200A          # HAIR SPACE
	0x202f          # NARROW NO-BREAK SPACE
	0x205f          # MEDIUM MATHEMATICAL SPACE
	0x3000          # IDEOGRAPHIC SPACE
*/
/*** GENERATED CODE ***/
#define is_HORIZWS(s,is_utf8)                                               \
( ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 ) ? 1 :                      \
( (is_utf8) ?                                                               \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0xA0 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0xE1 ) ?                                               \
    ( ( ((U8*)s)[1] == 0xA0 ) ?                                             \
      ( ( ((U8*)s)[2] == 0x8E ) ? 3 : 0 ) :                                 \
    ((( ((U8*)s)[1] == 0x9A ) && ( ((U8*)s)[2] == 0x80 )) ? 3 : 0) ) :      \
  ( ( ((U8*)s)[0] == 0xE2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x81 ) ?                                             \
      ( ( ((U8*)s)[2] == 0x9F ) ? 3 : 0 ) :                                 \
    ((( ((U8*)s)[1] == 0x80 ) && ( (0x80 <= ((U8*)s)[2] && ((U8*)s)[2] <= 0x8A) || ((U8*)s)[2] == 0xAF )) ? 3 : 0) ) :\
  (((( ((U8*)s)[0] == 0xE3 ) && ( ((U8*)s)[1] == 0x80 )) && ( ((U8*)s)[2] == 0x80 )) ? 3 : 0) ) ) ) :\
  ( ((U8*)s)[0] == 0xA0 ) ) )

/*** GENERATED CODE ***/
#define is_HORIZWS_safe(s,e,is_utf8)                                        \
( ( (e) - (s) > 2 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 ) ? 1 :                    \
( (is_utf8) ?                                                               \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0xA0 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0xE1 ) ?                                               \
    ( ( ((U8*)s)[1] == 0xA0 ) ?                                             \
      ( ( ((U8*)s)[2] == 0x8E ) ? 3 : 0 ) :                                 \
    ((( ((U8*)s)[1] == 0x9A ) && ( ((U8*)s)[2] == 0x80 )) ? 3 : 0) ) :      \
  ( ( ((U8*)s)[0] == 0xE2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x81 ) ?                                             \
      ( ( ((U8*)s)[2] == 0x9F ) ? 3 : 0 ) :                                 \
    ((( ((U8*)s)[1] == 0x80 ) && ( (0x80 <= ((U8*)s)[2] && ((U8*)s)[2] <= 0x8A) || ((U8*)s)[2] == 0xAF )) ? 3 : 0) ) :\
  (((( ((U8*)s)[0] == 0xE3 ) && ( ((U8*)s)[1] == 0x80 )) && ( ((U8*)s)[2] == 0x80 )) ? 3 : 0) ) ) ) :\
  ( ((U8*)s)[0] == 0xA0 ) ) ) :                                             \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 ) ? 1 :                    \
( (is_utf8) ?                                                               \
  ((( ((U8*)s)[0] == 0xC2 ) && ( ((U8*)s)[1] == 0xA0 )) ? 2 : 0) :          \
  ( ((U8*)s)[0] == 0xA0 ) ) ) :                                             \
( ( (e) - (s) > 0 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 ) ? 1 :                    \
( (!is_utf8) ?                                                              \
  ( ((U8*)s)[0] == 0xA0 ) : 0 ) ) : 0 ) ) )

/*** GENERATED CODE ***/
#define is_HORIZWS_utf8(s)                                                  \
( ( ((U8*)s)[0] == 0xC2 ) ?                                                 \
    ( ( ((U8*)s)[1] == 0xA0 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0xE1 ) ?                                               \
    ( ( ((U8*)s)[1] == 0xA0 ) ?                                             \
      ( ( ((U8*)s)[2] == 0x8E ) ? 3 : 0 ) :                                 \
    ((( ((U8*)s)[1] == 0x9A ) && ( ((U8*)s)[2] == 0x80 )) ? 3 : 0) ) :      \
  ( ( ((U8*)s)[0] == 0xE2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x81 ) ?                                             \
      ( ( ((U8*)s)[2] == 0x9F ) ? 3 : 0 ) :                                 \
    ((( ((U8*)s)[1] == 0x80 ) && ( (0x80 <= ((U8*)s)[2] && ((U8*)s)[2] <= 0x8A) || ((U8*)s)[2] == 0xAF )) ? 3 : 0) ) :\
  ( ( ((U8*)s)[0] == 0xE3 ) ?                                               \
    ((( ((U8*)s)[1] == 0x80 ) && ( ((U8*)s)[2] == 0x80 )) ? 3 : 0) :        \
  ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 ) ) ) ) )

/*** GENERATED CODE ***/
#define is_HORIZWS_utf8_safe(s,e)                                           \
( ( (e) - (s) > 2 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0xA0 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0xE1 ) ?                                               \
    ( ( ((U8*)s)[1] == 0xA0 ) ?                                             \
      ( ( ((U8*)s)[2] == 0x8E ) ? 3 : 0 ) :                                 \
    ((( ((U8*)s)[1] == 0x9A ) && ( ((U8*)s)[2] == 0x80 )) ? 3 : 0) ) :      \
  ( ( ((U8*)s)[0] == 0xE2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x81 ) ?                                             \
      ( ( ((U8*)s)[2] == 0x9F ) ? 3 : 0 ) :                                 \
    ((( ((U8*)s)[1] == 0x80 ) && ( (0x80 <= ((U8*)s)[2] && ((U8*)s)[2] <= 0x8A) || ((U8*)s)[2] == 0xAF )) ? 3 : 0) ) :\
  ( ( ((U8*)s)[0] == 0xE3 ) ?                                               \
    ((( ((U8*)s)[1] == 0x80 ) && ( ((U8*)s)[2] == 0x80 )) ? 3 : 0) :        \
  ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 ) ) ) ) ) :                  \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0xA0 ) ? 2 : 0 ) :                                   \
  ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 ) ) :                        \
( ( (e) - (s) > 0 ) ?                                                       \
  ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 ) : 0 ) ) )

/*** GENERATED CODE ***/
#define is_HORIZWS_latin1(s)                                                \
( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 || ((U8*)s)[0] == 0xA0 )

/*** GENERATED CODE ***/
#define is_HORIZWS_latin1_safe(s,e)                                         \
( ( (e) - (s) > 0 ) ?                                                       \
  ( ((U8*)s)[0] == 0x09 || ((U8*)s)[0] == 0x20 || ((U8*)s)[0] == 0xA0 ) : 0 )

/*** GENERATED CODE ***/
#define is_HORIZWS_cp(cp)                                                   \
( cp == 0x09 || ( cp > 9 &&                                                 \
( cp == 0x20 || ( cp > 32 &&                                                \
( cp == 0xA0 || ( cp > 160 &&                                               \
( cp == 0x1680 || ( cp > 5760 &&                                            \
( cp == 0x180E || ( cp > 6158 &&                                            \
( (0x2000 <= cp && cp <= 0x200A) || ( cp > 8202 &&                          \
( cp == 0x202F || ( cp > 8239 &&                                            \
( cp == 0x205F || ( cp > 8287 &&                                            \
cp == 0x3000 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )

/*
	VERTWS: Vertical Whitespace: \v \V

	0x0A            # LF
	0x0B            # VT
	0x0C            # FF
	0x0D            # CR
	0x85            # NEL
	0x2028          # LINE SEPARATOR
	0x2029          # PARAGRAPH SEPARATOR
*/
/*** GENERATED CODE ***/
#define is_VERTWS(s,is_utf8)                                                \
( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) ? 1 :                        \
( (is_utf8) ?                                                               \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  (((( ((U8*)s)[0] == 0xE2 ) && ( ((U8*)s)[1] == 0x80 )) && ( ((U8*)s)[2] == 0xA8 || ((U8*)s)[2] == 0xA9 )) ? 3 : 0) ) :\
  ( ((U8*)s)[0] == 0x85 ) ) )

/*** GENERATED CODE ***/
#define is_VERTWS_safe(s,e,is_utf8)                                         \
( ( (e) - (s) > 2 ) ?                                                       \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) ? 1 :                      \
( (is_utf8) ?                                                               \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  (((( ((U8*)s)[0] == 0xE2 ) && ( ((U8*)s)[1] == 0x80 )) && ( ((U8*)s)[2] == 0xA8 || ((U8*)s)[2] == 0xA9 )) ? 3 : 0) ) :\
  ( ((U8*)s)[0] == 0x85 ) ) ) :                                             \
( ( (e) - (s) > 1 ) ?                                                       \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) ? 1 :                      \
( (is_utf8) ?                                                               \
  ((( ((U8*)s)[0] == 0xC2 ) && ( ((U8*)s)[1] == 0x85 )) ? 2 : 0) :          \
  ( ((U8*)s)[0] == 0x85 ) ) ) :                                             \
( ( (e) - (s) > 0 ) ?                                                       \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) ? 1 :                      \
( (!is_utf8) ?                                                              \
  ( ((U8*)s)[0] == 0x85 ) : 0 ) ) : 0 ) ) )

/*** GENERATED CODE ***/
#define is_VERTWS_utf8(s)                                                   \
( ( ((U8*)s)[0] == 0xC2 ) ?                                                 \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0xE2 ) ?                                               \
    ((( ((U8*)s)[1] == 0x80 ) && ( ((U8*)s)[2] == 0xA8 || ((U8*)s)[2] == 0xA9 )) ? 3 : 0) :\
  (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) ) )

/*** GENERATED CODE ***/
#define is_VERTWS_utf8_safe(s,e)                                            \
( ( (e) - (s) > 2 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  ( ( ((U8*)s)[0] == 0xE2 ) ?                                               \
    ((( ((U8*)s)[1] == 0x80 ) && ( ((U8*)s)[2] == 0xA8 || ((U8*)s)[2] == 0xA9 )) ? 3 : 0) :\
  (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) ) ) :                        \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0] == 0xC2 ) ?                                               \
    ( ( ((U8*)s)[1] == 0x85 ) ? 2 : 0 ) :                                   \
  (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) ) :                          \
( ( (e) - (s) > 0 ) ?                                                       \
  (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) : 0 ) ) )

/*** GENERATED CODE ***/
#define is_VERTWS_latin1(s)                                                 \
( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) || ((U8*)s)[0] == 0x85 )

/*** GENERATED CODE ***/
#define is_VERTWS_latin1_safe(s,e)                                          \
( ( (e) - (s) > 0 ) ?                                                       \
  ( (0x0A <= ((U8*)s)[0] && ((U8*)s)[0] <= 0x0D) || ((U8*)s)[0] == 0x85 ) : 0 )

/*** GENERATED CODE ***/
#define is_VERTWS_cp(cp)                                                    \
( (0x0A <= cp && cp <= 0x0D) || ( cp > 13 &&                                \
( cp == 0x85 || ( cp > 133 &&                                               \
( cp == 0x2028 || ( cp > 8232 &&                                            \
cp == 0x2029 ) ) ) ) ) )

/* ex: set ro: */
