/* -*- mode: C; buffer-read-only: t -*-
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by regen/mk_invlists.pl from Unicode::UCD.
 * Any changes made here will be lost!
 */

/* This gives the number of code points that can be in the bitmap of an ANYOF
 * node.  The shift number must currently be one of: 8..12.  It can't be less
 * than 8 (256) because some code relies on it being at least that.  Above 12
 * (4096), and you start running into warnings that some data structure widths
 * have been exceeded, though the test suite as of this writing still passes
 * for up through 16, which is as high as anyone would ever want to go,
 * encompassing all of the Unicode BMP, and thus including all the economically
 * important world scripts.  At 12 most of them are: including Arabic,
 * Cyrillic, Greek, Hebrew, Indian subcontinent, Latin, and Thai; but not Han,
 * Japanese, nor Korean.  The regnode sizing data structure in regnodes.h currently
 * uses a U8 for its node sizing data above this point.)  Be sure to benchmark
 * before changing, as larger sizes
 * do significantly slow down the test suite. */

#define NUM_ANYOF_CODE_POINTS   (1 << 8)


/* More than one code point may have the same code point as their fold.  This
 * gives the maximum number in the current Unicode release.  (The folded-to
 * code point is not included in this count.)  For example, both 'S' and
 * \x{17F} fold to 's', so the number for that fold is 2.  Another way to
 * look at it is the maximum length of all the IVCF_AUX_TABLE's */
#define MAX_FOLD_FROMS 3

/* Generated from:
 * 198105a1b3637a4bc7240628bae2f65f6d0c31df2cee4f0242c2561421ea2e75 lib/Unicode/UCD.pm
 * 8ccde4ebd070500a68e8bcb9d5514522fb0bebe57b9ebad3ff925b8e1e669f83 lib/unicore/ArabicShaping.txt
 * 4b3b62e4a14b84ee752808c810c602534921c09a4a1bf78cfbee566d66c125b3 lib/unicore/BidiBrackets.txt
 * cd54810ebf52f0e61a730c8b9cb25975de6c85f6d788a559b416afd548923fd6 lib/unicore/BidiMirroring.txt
 * a58f8d322f3c5e254f9f97b1cbf76a454a7e02de6ac35619a5e4f27aaabfd553 lib/unicore/Blocks.txt
 * a004797658a457bec4dc11683e39f69249ea3b595b752dbea6721c4c9f587b0d lib/unicore/CaseFolding.txt
 * c759b100e9ae8960ae6b50fc5765950a7581fd9f30d4ef95f68f25a6d97e818e lib/unicore/CompositionExclusions.txt
 * 58b04334e3a31f9612694bbc3f6bff4a302b7d424565bca9c47e30aa74f8dbac lib/unicore/DAge.txt
 * 09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9 lib/unicore/DCoreProperties.txt
 * 98ac7f67d985fe781e317f6182e885e94cabb0c314769e6dd73e48b226931ccd lib/unicore/DNormalizationProps.txt
 * a0cf29eacd00cfcaec4381c6b7c281685f18dbb4e7ff82b4076ccb342ca839aa lib/unicore/EastAsianWidth.txt
 * c86c80f6a0d1d47c9a5aadfbf1c26f1a732d662d9ccb0ed2d397919ecc47bf72 lib/unicore/EquivalentUnifiedIdeograph.txt
 * 0468ce5e735a6e3f0e9d12ec006410e86cedc515c34706704c756808a6cf740e lib/unicore/HangulSyllableType.txt
 * 5863c7d99ca18f213c41c7318aa5528bebfb6d32ec0f1d5944e37192c119aebd lib/unicore/IdStatus.txt
 * fa24851acc669e58670e354e7b98a4ec8f52a809ec4f80524b6a60efdb868831 lib/unicore/IdType.txt
 * c9ad44d267c317ee0e1ec66cbd4d15033c2964f905d11fc8905915f9a5a9ae52 lib/unicore/IndicPositionalCategory.txt
 * a2b3aacf6b3e7bad4ca351ef985d9543825e20280ff280c25f646d9bc4ce304c lib/unicore/IndicSyllabicCategory.txt
 * 2216bd39fbfeb8fc44825909e61bed4d866c5e155ed359fbf8d308e307b15c57 lib/unicore/Jamo.txt
 * e4135d2776ff18232dfe2d59b71ac0775f74f8704f141527079b9b8d6832cdaf lib/unicore/JurchenSources.txt
 * ae8cf1970c73f3f1a12d77852df96c4b2b1723ca8b388e36bb5739250c6849de lib/unicore/LineBreak.txt
 * 3d5cf5e468901b080cd99adf2230061b748083705fe633db43ac8b73ec7a13da lib/unicore/NameAliases.txt
 * 4666003f450ece06fb3f5d868c5d486622dc5275ff626a730ff0c94cbb303df0 lib/unicore/NamedSequences.txt
 * 25a50d816764b04abfb4a646d3eb2b2a803284c3873d9a06757b94fe4513dde3 lib/unicore/NormTest.txt
 * b8fbcccce66163fc4808894a18e120bb04490013e0e027c1ae9335faabc22138 lib/unicore/NushuSources.txt
 * f438f532e8737bb8a2702126cdf9c4af5e357c58c7acf9d9eb2fc7c1a1d955d6 lib/unicore/PropList.txt
 * 06c4c8eaf7b0bf34abe73b113da1215bd784ac254d4c223600b90267caa4bbbd lib/unicore/PropValueAliases.txt
 * 83b8df695f9da543dba02b0be2b8bd72f0b52836ad264be113c6d285021ef025 lib/unicore/PropertyAliases.txt
 * 5c9d34a922f687726f2a8bcf57d49f905987e51f1b21b58c95a00fbe255cec23 lib/unicore/ScriptExtensions.txt
 * 0071fd81b6aeae25f6e8bce8efec3066a6476a91b49bdb2f52dc76e817862a6a lib/unicore/Scripts.txt
 * 05ba2c220c4f34a0f1ef54676e7d2033963a9baed1acafd079f00f13da11aa90 lib/unicore/SealSources.txt
 * 8538dea57c184f1ef3783885ea79677b10f6efa06423717157e63712f14d1ad2 lib/unicore/SpecialCasing.txt
 * ae440bd9bba89b2610cfe6b498ac462d2763dd32bfead8ac30d32988b5b67a27 lib/unicore/TangutSources.txt
 * 0736451de439ae7baf1425136617da495e09ee5afbe6e394374db7009ea08950 lib/unicore/UnicodeData.txt
 * a6c03de18f40f54df5bf3ea6c3152f23075ba8647520e98ea80e8e0352d65a33 lib/unicore/Unikemet.txt
 * 0803e09669d7aa7137de678e55b848bd418c6632694fa1b05f0b40941103c748 lib/unicore/VerticalOrientation.txt
 * b0cf047ee94485bbdc846de2b902f5f8a815f6b674f9d04223cddadd91c9df31 lib/unicore/auxiliary/GCBTest.txt
 * 0839dcb79e4ac639ecd538b1abf7c9d22e3f9dd265b7e182d33627aa4d75b45a lib/unicore/auxiliary/GraphemeBreakProperty.txt
 * fd9ff9eca411080085b41471bba79ae19d9db2e16924f9770b8509f1affd3f95 lib/unicore/auxiliary/LBTest.txt
 * 84ca7516e7bd1203ab7e8d888ae77f0a0af0a254d10e09a2847000588848885c lib/unicore/auxiliary/SBTest.txt
 * 0ac10c9d6dca3b33ac695ff0968f26356465a51626950c463b3dce8fa07e61cc lib/unicore/auxiliary/SentenceBreakProperty.txt
 * 3dd70c071781276067c680d87303f60434adce7b067bd063194af374edad86a5 lib/unicore/auxiliary/WBTest.txt
 * 8dbfa17063e11084201f33c3e76d485d3b9166930c71db8e39ed1c9234171aec lib/unicore/auxiliary/WordBreakProperty.txt
 * 80d00f8e616a0ef27fd6b8de3b758c06383b5d917e2977709578e68baf733bf1 lib/unicore/emoji/emoji.txt
 * d9e23222522551348ea1ccfbb4f62efbf98982afb95840f8959c08ed992c5607 lib/unicore/extracted/DBidiClass.txt
 * f4336d325727d94c31f06b660488f5213a5b6f6cf8bb55b090f87bac704805a5 lib/unicore/extracted/DBinaryProperties.txt
 * ef6b2611cfb660dba3f6b458b9eb4b05f44ed2417302ee7749d7f0f348793121 lib/unicore/extracted/DCombiningClass.txt
 * 0941d968cf73472500ab3eb807c02d85e6d7510832a2be7e5d21bd6c08e96e92 lib/unicore/extracted/DDecompositionType.txt
 * f4c7bc4537a71e12452f6347ecbbc71c31cba21b5190c92be1ae296b0ef32b09 lib/unicore/extracted/DEastAsianWidth.txt
 * d6b151d2d40ee9b1876d26f417980f45ffae47b6055ccf7203cb31f07a030f94 lib/unicore/extracted/DGeneralCategory.txt
 * 325be8cd3a32a9cc2b80a1fe67e5c7ade3b58d8280fa9d49134edabed82832a1 lib/unicore/extracted/DJoinGroup.txt
 * e2408ff2c92b175b0f7bf62c989bbb54c7b077528fe31f8d69b96fa09e7d61ed lib/unicore/extracted/DJoinType.txt
 * e015a6d4bde8dd0f8b72bf15ac9a4f588146ce6bc0bf8980e9dae8302cdbdc28 lib/unicore/extracted/DLineBreak.txt
 * 3dade4d96bd00d71b10022bf70b370090f3ca947f977ad4dc2854e06c4d074f6 lib/unicore/extracted/DNumType.txt
 * c84f084f83ec6852e1db6e7ef15f340a3af2df8cf0c386ac0d076c2cebd189e6 lib/unicore/extracted/DNumValues.txt
 * cf7662c98636458c9e4c8897b32b32e5b6dfdedd6a0eb41b1c4fcde41101d7ad lib/unicore/mktables
 * a0079d7556b20c2de1fdc3d492797a91b8ec8a06006f94460006185cb6380962 lib/unicore/version
 * 0a6b5ab33bb1026531f816efe81aea1a8ffcd34a27cbea37dd6a70a63d73c844 regen/charset_translations.pl
 * 6bbb462516a4ea79e28d58cf387f0b4b63ba83c7d381cd61bdda0b188e148082 regen/mk_PL_charclass.pl
 * 2fe950c6526e41c25308da86647024cfe2a1a05108bb8b6a095ce8ab88f43eee regen/mk_invlists.pl
 * ex: set ro ft=c: */
