#!/bin/sh
cwd=`pwd`
if [ -f bperl ]; then
    perl=./bperl
else
    perl="perl -Mblib"
fi
if [ "X$PERL_SRC" != "X" ]; then
    testdir=$PERL_SRC/t
else
    testdir=t
fi
for pl in ${1+"$@"}
do
    echo "*****	$pl *****"
    $perl -MO=CC,-obtest.tc $pl			\
	&& mv btest.tc btest.c			\
	&& $perl cc_harness -O2 -o btest btest.c\
	&& (cd $testdir; $cwd/btest)
done
