/* -*- buffer-read-only: t -*-
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by regen/utf8_strings.pl from Unicode data.
 * Any changes made here will be lost!
 */

/* This file contains #defines for various Unicode code points.  The values
 * for the macros are all or portions of the UTF-8 encoding for the code
 * point.  Note that the names all have the suffix "_UTF8".
 *
 * The suffix "_FIRST_BYTE" may be appended to the name if the value is just
 * the first byte of the UTF-8 representation; the value will be a numeric
 * constant.
 *
 * The suffix "_TAIL" is appened if instead it represents all but the first
 * byte.  This, and with no suffix are both string constants */

#define COMBINING_GRAVE_ACCENT_UTF8 "\xCC\x80"    /* U+0300 */
#define COMBINING_ACUTE_ACCENT_UTF8 "\xCC\x81"    /* U+0301 */
#define COMBINING_DIAERESIS_UTF8 "\xCC\x88"    /* U+0308 */
#define GREEK_SMALL_LETTER_IOTA_UTF8_TAIL "\xB9"    /* U+03B9 */
#define GREEK_SMALL_LETTER_UPSILON_UTF8_TAIL "\x85"    /* U+03C5 */
#define GREEK_SMALL_LETTER_IOTA_UTF8_FIRST_BYTE 0xCE    /* U+03B9 */
#define GREEK_SMALL_LETTER_UPSILON_UTF8_FIRST_BYTE 0xCF    /* U+03C5 */
#define HANGUL_CHOSEONG_KIYEOK_UTF8 "\xE1\x84\x80"    /* U+1100 */
#define HANGUL_JUNGSEONG_FILLER_UTF8 "\xE1\x85\xA0"    /* U+1160 */
#define HANGUL_JONGSEONG_KIYEOK_UTF8 "\xE1\x86\xA8"    /* U+11A8 */
#define HYPHEN_UTF8 "\xE2\x80\x90"    /* U+2010 */

/* ex: set ro: */
