#!/bin/sh
: This script takes the plain miniperlmain.c and writes out perlmain.c
: which includes all the extensions.
: The command line arguments name extensions to be used.
:  E.g.:  sh writemain SDBM_File POSIX > perlmain.c
:
args="$*"
if test X"$args" = "X" ; then
    cat miniperlmain.c
else
    sed '/Do not delete this line--writemain depends on it/q' miniperlmain.c
    cat << 'EOP'

#ifdef USE_DYNAMIC_LOADING
    boot_DynamicLoader();
#endif

EOP
    for ext in $args; do
	echo "    newXSUB(\"${ext}::bootstrap\", 0, boot_${ext}, file);"
    done
    echo '}'
fi

