# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables.PL from e.g. Unicode.txt.
# Any changes made here will be lost!
return <<END;
0028	
0029	
002a	
002b	
002d	
002f	
003c	003e
005b	
005c	
005d	
005e	
007b	
007c	
007d	
007e	
00ac	
00b1	
00d7	
00f7	
2016	
2032	2034
2044	
207a	207c
207d	
207e	
208a	208c
208d	
208e	
20d0	20dc
20e1	
2102	
210a	2113
2115	
2119	211d
2124	
2128	
212c	212d
212f	2131
2133	2134
2135	2138
2190	2194
219a	219b
21a0	
21a3	
21a6	
21ae	
21ce	21cf
21d2	
21d4	
2200	22f1
2308	230b
2320	2321
2329	
232a	
25b7	
25c1	
266f	
300a	
300b	
301a	
301b	
fb29	
fe35	
fe36	
fe37	
fe38	
fe59	
fe5a	
fe5b	
fe5c	
fe61	
fe62	
fe63	
fe64	fe66
fe68	
ff08	
ff09	
ff0a	
ff0b	
ff0d	
ff0f	
ff1c	ff1e
ff3b	
ff3c	
ff3d	
ff3e	
ff5b	
ff5c	
ff5d	
ff5e	
ffe2	
ffe9	ffec
1d400	1d454
1d456	1d49c
1d49e	1d49f
1d4a2	
1d4a5	1d4a6
1d4a9	1d4ac
1d4ae	1d4b9
1d4bb	
1d4bd	1d4c0
1d4c2	1d4c3
1d4c5	1d505
1d507	1d50a
1d50d	1d514
1d516	1d51c
1d51e	1d539
1d53b	1d53e
1d540	1d544
1d546	
1d54a	1d550
1d552	1d6a3
1d6a8	1d6c0
1d6c1	
1d6c2	1d6da
1d6db	
1d6dc	1d6fa
1d6fb	
1d6fc	1d714
1d715	
1d716	1d734
1d735	
1d736	1d74e
1d74f	
1d750	1d76e
1d76f	
1d770	1d788
1d789	
1d78a	1d7a8
1d7a9	
1d7aa	1d7c2
1d7c3	
1d7c4	1d7c9
1d7ce	1d7ff
END
