# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Any} (and fuzzy permutations)
# 	\p{All} (and fuzzy permutations)
# 
# Meaning: [\x{0000}-\x{10FFFF}]
#
return <<'END';
0000	10FFFF	
END
