# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. Unicode.txt.
# Any changes made here will be lost!
# Built Mon Jan 14 15:52:42 2002.

return <<'END';
000A		
000D		
001C	001E	
0085		
2029		
END
