# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

return <<'END';
000C		
0020		
1680		
2000	200A	
2028		
202F		
3000		
END
