# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables.PL from e.g. Unicode.txt.
# Any changes made here will be lost!
return <<'END';
0000	001f
007f	009f
070f	
180b	180e
200c	200f
202a	202e
206a	206f
d800	db7f
db80	dbff
dc00	dfff
e000	f8ff
feff	
fff9	fffb
1d173	1d17a
e0001	
e0020	e007f
f0000	ffffd
100000	10fffd
END
