# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

return <<'END';
070F		
180B	180E	
200C	200F	
202A	202E	
206A	206F	
FEFF		
FFF9	FFFB	
1D173	1D17A	
E0001		
E0020	E007F	
END
