# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Cs}
# 	\p{Surrogate} (and fuzzy permutations)
# 
# Meaning: General Category 'Cs'
#
return <<'END';
D800	DFFF	
END
