# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

return <<'END';
0400	0481	CYRILLIC
0483	0486	CYRILLIC
048C	04C4	CYRILLIC
04C7	04C8	CYRILLIC
04CB	04CC	CYRILLIC
04D0	04F5	CYRILLIC
04F8	04F9	CYRILLIC
END
