# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. Unicode.txt.
# Any changes made here will be lost!
# Built Mon Jan 14 15:52:42 2002.

return <<'END';
FE50	FE52	
FE54	FE66	
FE68	FE6B	
END
