# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. Unicode.txt.
# Any changes made here will be lost!
# Built Mon Jan 14 15:52:42 2002.

return <<'END';
00AA		
00B2	00B3	
00B9	00BA	
02B0	02B8	
02E0	02E4	
2070		
2074	207F	
2120		
2122		
3192	319F	
END
