# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. Unicode.txt.
# Any changes made here will be lost!
# Built Mon Jan 14 15:52:42 2002.

return <<'END';
10A0	10C5	GEORGIAN
10D0	10F6	GEORGIAN
END
