# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{LbrkBB}
# 
# Meaning: Linebreak category 'BB'
#
return <<'END';
00B4		
02C8		
02CC		
1806		
END
