# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{LbrkBA}
# 
# Meaning: Linebreak category 'BA'
#
return <<'END';
0009		
007C		
00AD		
058A		
0F0B		
1361		
1680		
17D5		
2000	2006	
2008	200A	
2010		
2012	2013	
2027		
END
