# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{LbrkBK}
# 
# Meaning: Linebreak category 'BK'
#
return <<'END';
000C		
2028	2029	
END
