# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{LbrkSY}
# 
# Meaning: Linebreak category 'SY'
#
return <<'END';
002F		
END
