# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

return <<'END';
005F		
203F	2040	
30FB		
FE33	FE34	
FE4D	FE4F	
FF3F		
FF65		
END
