# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Zl}
# 	\p{LineSeparator} (and fuzzy permutations)
# 
# Meaning: General Category 'Zl'
#
return <<'END';
2028		
END
