#!./perl

#!/usr/bin/perl
$month = (split(' ',`date`))[1];

while (<DATA>) {
    next if 1 .. ?^$month\b?o;
    next unless /deposit/;
    ($day) = /(\d+)/;
    local(*where) = m:([^/]+)$:;
    # with the local, you get bad free's.  with it, you get a core dump
    $where{$day}++;
}

@days = sort { $a <=> $b } keys %personal;

foreach $place ('tivoli', 'lists', 'personal') {
    *where = $place;
    foreach $day (@days) {
        printf "Aug %02d: %3d in %s\n", $day, $where{$day}, $place;
    }
}

__END__
Aug 27 10:40:20 New mail from hess
Aug 27 10:40:20 deposit into /home/wraeththu/tchrist/Mail/in.coming/tivoli
Aug 27 10:42:27 New mail from jcarson
Aug 27 10:42:27 deposit into /home/wraeththu/tchrist/Mail/in.coming/tivoli
Aug 27 10:48:18 New mail from dean
Aug 27 10:48:18 deposit into /home/wraeththu/tchrist/Mail/in.coming/tivoli
Aug 27 11:05:56 New mail from hess
Aug 27 11:05:56 deposit into personal
Aug 27 11:13:28 New mail from hess
Aug 27 11:13:28 deposit into personal
