# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# Linebreak category 'Break_After'
#
return <<'END';
0009		
007C		
00AD		
058A		
0F0B		
1361		
1680		
17D5		
2000	2006	
2008	200A	
2010		
2012	2013	
2027		
205F		
10100	10102	
1039F		
END
