/* -*- buffer-read-only: t -*-
 *
 *      Copyright (c) 1996-1999 Malcolm Beattie
 *
 *      You may distribute under the terms of either the GNU General Public
 *      License or the Artistic License, as specified in the README file.
 *
 */
/*
 * This file is autogenerated from bytecode.pl. Changes made here will be lost.
 */
struct byteloader_fdata {
    SV	*datasv;
    int next_out;
    int	idx;
};

struct byteloader_pv_state {
    char			*pvx;
    XPV				xpv;
};

struct byteloader_state {
    struct byteloader_fdata	*bs_fdata;
    SV				*bs_sv;
    void			**bs_obj_list;
    int				bs_obj_list_fill;
    int				bs_ix;
    struct byteloader_pv_state	bs_pv;
    int				bs_iv_overflows;
};

int bl_getc(struct byteloader_fdata *);
int bl_read(struct byteloader_fdata *, char *, size_t, size_t);
extern int byterun(pTHX_ struct byteloader_state *);

enum {
    INSN_RET,			/* 0 */
    INSN_LDSV,			/* 1 */
    INSN_LDOP,			/* 2 */
    INSN_STSV,			/* 3 */
    INSN_STOP,			/* 4 */
    INSN_STPV,			/* 5 */
    INSN_LDSPECSV,			/* 6 */
    INSN_LDSPECSVX,			/* 7 */
    INSN_NEWSV,			/* 8 */
    INSN_NEWSVX,			/* 9 */
    INSN_NOP,			/* 10 */
    INSN_NEWOP,			/* 11 */
    INSN_NEWOPX,			/* 12 */
    INSN_NEWOPN,			/* 13 */
    INSN_NEWPV,			/* 14 */
    INSN_PV_CUR,			/* 15 */
    INSN_PV_FREE,			/* 16 */
    INSN_SV_UPGRADE,			/* 17 */
    INSN_SV_REFCNT,			/* 18 */
    INSN_SV_REFCNT_ADD,			/* 19 */
    INSN_SV_FLAGS,			/* 20 */
    INSN_XRV,			/* 21 */
    INSN_XPV,			/* 22 */
    INSN_XPV_CUR,			/* 23 */
    INSN_XPV_LEN,			/* 24 */
    INSN_XIV,			/* 25 */
    INSN_XNV,			/* 26 */
    INSN_XLV_TARGOFF,			/* 27 */
    INSN_XLV_TARGLEN,			/* 28 */
    INSN_XLV_TARG,			/* 29 */
    INSN_XLV_TYPE,			/* 30 */
    INSN_XBM_USEFUL,			/* 31 */
    INSN_XBM_PREVIOUS,			/* 32 */
    INSN_XBM_RARE,			/* 33 */
    INSN_XFM_LINES,			/* 34 */
    INSN_COMMENT,			/* 35 */
    INSN_XIO_LINES,			/* 36 */
    INSN_XIO_PAGE,			/* 37 */
    INSN_XIO_PAGE_LEN,			/* 38 */
    INSN_XIO_LINES_LEFT,			/* 39 */
    INSN_XIO_TOP_NAME,			/* 40 */
    INSN_XIO_TOP_GV,			/* 41 */
    INSN_XIO_FMT_NAME,			/* 42 */
    INSN_XIO_FMT_GV,			/* 43 */
    INSN_XIO_BOTTOM_NAME,			/* 44 */
    INSN_XIO_BOTTOM_GV,			/* 45 */
    INSN_XIO_SUBPROCESS,			/* 46 */
    INSN_XIO_TYPE,			/* 47 */
    INSN_XIO_FLAGS,			/* 48 */
    INSN_XCV_XSUBANY,			/* 49 */
    INSN_XCV_STASH,			/* 50 */
    INSN_XCV_START,			/* 51 */
    INSN_XCV_ROOT,			/* 52 */
    INSN_XCV_GV,			/* 53 */
    INSN_XCV_FILE,			/* 54 */
    INSN_XCV_DEPTH,			/* 55 */
    INSN_XCV_PADLIST,			/* 56 */
    INSN_XCV_OUTSIDE,			/* 57 */
    INSN_XCV_OUTSIDE_SEQ,			/* 58 */
    INSN_XCV_FLAGS,			/* 59 */
    INSN_AV_EXTEND,			/* 60 */
    INSN_AV_PUSHX,			/* 61 */
    INSN_AV_PUSH,			/* 62 */
    INSN_XAV_FILL,			/* 63 */
    INSN_XAV_MAX,			/* 64 */
    INSN_XHV_RITER,			/* 65 */
    INSN_XHV_NAME,			/* 66 */
    INSN_HV_STORE,			/* 67 */
    INSN_SV_MAGIC,			/* 68 */
    INSN_MG_OBJ,			/* 69 */
    INSN_MG_PRIVATE,			/* 70 */
    INSN_MG_FLAGS,			/* 71 */
    INSN_MG_NAME,			/* 72 */
    INSN_MG_NAMEX,			/* 73 */
    INSN_XMG_STASH,			/* 74 */
    INSN_GV_FETCHPV,			/* 75 */
    INSN_GV_FETCHPVX,			/* 76 */
    INSN_GV_STASHPV,			/* 77 */
    INSN_GV_STASHPVX,			/* 78 */
    INSN_GP_SV,			/* 79 */
    INSN_GP_REFCNT,			/* 80 */
    INSN_GP_REFCNT_ADD,			/* 81 */
    INSN_GP_AV,			/* 82 */
    INSN_GP_HV,			/* 83 */
    INSN_GP_CV,			/* 84 */
    INSN_GP_FILE,			/* 85 */
    INSN_GP_IO,			/* 86 */
    INSN_GP_FORM,			/* 87 */
    INSN_GP_CVGEN,			/* 88 */
    INSN_GP_LINE,			/* 89 */
    INSN_GP_SHARE,			/* 90 */
    INSN_XGV_FLAGS,			/* 91 */
    INSN_OP_NEXT,			/* 92 */
    INSN_OP_SIBLING,			/* 93 */
    INSN_OP_PPADDR,			/* 94 */
    INSN_OP_TARG,			/* 95 */
    INSN_OP_TYPE,			/* 96 */
    INSN_OP_OPT,			/* 97 */
    INSN_OP_STATIC,			/* 98 */
    INSN_OP_FLAGS,			/* 99 */
    INSN_OP_PRIVATE,			/* 100 */
    INSN_OP_FIRST,			/* 101 */
    INSN_OP_LAST,			/* 102 */
    INSN_OP_OTHER,			/* 103 */
    INSN_OP_PMREPLROOT,			/* 104 */
    INSN_OP_PMREPLSTART,			/* 105 */
    INSN_OP_PMNEXT,			/* 106 */
    INSN_OP_PMSTASHPV,			/* 107 */
    INSN_OP_PMREPLROOTPO,			/* 108 */
    INSN_OP_PMSTASH,			/* 109 */
    INSN_OP_PMREPLROOTGV,			/* 110 */
    INSN_PREGCOMP,			/* 111 */
    INSN_OP_PMFLAGS,			/* 112 */
    INSN_OP_PMPERMFLAGS,			/* 113 */
    INSN_OP_PMDYNFLAGS,			/* 114 */
    INSN_OP_SV,			/* 115 */
    INSN_OP_PADIX,			/* 116 */
    INSN_OP_PV,			/* 117 */
    INSN_OP_PV_TR,			/* 118 */
    INSN_OP_REDOOP,			/* 119 */
    INSN_OP_NEXTOP,			/* 120 */
    INSN_OP_LASTOP,			/* 121 */
    INSN_COP_LABEL,			/* 122 */
    INSN_COP_STASHPV,			/* 123 */
    INSN_COP_FILE,			/* 124 */
    INSN_COP_STASH,			/* 125 */
    INSN_COP_FILEGV,			/* 126 */
    INSN_COP_SEQ,			/* 127 */
    INSN_COP_ARYBASE,			/* 128 */
    INSN_COP_LINE,			/* 129 */
    INSN_COP_WARNINGS,			/* 130 */
    INSN_MAIN_START,			/* 131 */
    INSN_MAIN_ROOT,			/* 132 */
    INSN_MAIN_CV,			/* 133 */
    INSN_CURPAD,			/* 134 */
    INSN_PUSH_BEGIN,			/* 135 */
    INSN_PUSH_INIT,			/* 136 */
    INSN_PUSH_END,			/* 137 */
    INSN_CURSTASH,			/* 138 */
    INSN_DEFSTASH,			/* 139 */
    INSN_DATA,			/* 140 */
    INSN_INCAV,			/* 141 */
    INSN_LOAD_GLOB,			/* 142 */
    INSN_REGEX_PADAV,			/* 143 */
    INSN_DOWARN,			/* 144 */
    INSN_COMPPAD_NAME,			/* 145 */
    INSN_XGV_STASH,			/* 146 */
    INSN_SIGNAL,			/* 147 */
    INSN_FORMFEED,			/* 148 */
    MAX_INSN = 148
};

enum {
    OPt_OP,		/* 0 */
    OPt_UNOP,		/* 1 */
    OPt_BINOP,		/* 2 */
    OPt_LOGOP,		/* 3 */
    OPt_LISTOP,		/* 4 */
    OPt_PMOP,		/* 5 */
    OPt_SVOP,		/* 6 */
    OPt_PADOP,		/* 7 */
    OPt_PVOP,		/* 8 */
    OPt_LOOP,		/* 9 */
    OPt_COP		/* 10 */
};

/* ex: set ro: */
