#!/usr/bin/perl -Tw

BEGIN {
    if ( $ENV{PERL_CORE} ) {
        unshift @INC, '../lib';
    }
    else {
        unshift @INC, 't/lib';
    }
}

use Test::More tests => 1;

ok( grep( /examples/, @INC ) );

