# -*- buffer-read-only: t -*-
# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is built by regen/pX.pl.
# Any changes made here will be lost!


package p5;

# This helps hint to perl 7+ what level of compatibility this code has with future versions of perl.
# use p5 should be the first thing in your code. Especially before use strict, warnings, v5.XXX, or feature.


our $VERSION = '0.00001';


sub _warn_once {
    local $^W;
    local ${^WARNING_BITS};
    BEGIN {
        $^W = 0;
        ${^WARNING_BITS} = 0;
    }

    *_warn_once = sub{};

    #warn("# This code is being run using Perl $]. It should be updated or may break in Perl 8. See YYY for more information.");
}

BEGIN {
    $] <= 8 or die("This code is incompatible with Perl 8. Please see XXX for more information.");
    _warn_once() if $] > 6;
}

sub import {
    # no warnings;
    ${^WARNING_BITS} = 0;
    $^W = 0;

    # perl  -e'my $h; BEGIN {  $h = $^H } printf("\$^H = 0x%08X\n", $h); '
    $^H = 0x0; # FIXME only reset the features...
    %^H = ();

    return;
}

sub unimport {
    # maybe restore? p7 warnings... and co... 
    # we want to restore p7 behavior..
    require p7;
    p7->import;

    return;
}

1;

__END__

=head1 NAME

p7

=head1 SYNOPSIS

use p5;

=head1 DESCRIPTION

Description for p5.

=head1 AUTHOR

atoomic

=cut


# ex: set ro:
