#!perl

	## shasum: filter for computing SHA digests (ref. sha1sum/md5sum)
	##
	## Copyright (C) 2003-2023 Mark Shelor, All Rights Reserved
	##
	## Version: 6.04
	## Sat Feb 25 12:00:50 PM MST 2023
	##
	## shasum SYNOPSIS adapted from GNU Coreutils sha1sum. Add
	## "-a" option for algorithm selection,
	## "-U" option for Universal Newlines support,
	## "-0" option for reading bit strings, and
	## "--progress" for optional progress reporting during checksum
	## calculation.
	##
	## The --progress option reports hashing progress to STDERR while
	## preserving the normal checksum output on STDOUT. This keeps the
	## feature safe for scripts and pipelines that parse checksum output.
	##
	## For regular files, progress includes bytes processed, total bytes,
	## percentage complete, throughput, and ETA. For STDIN or other inputs
	## with unknown total size, progress includes bytes processed and
	## throughput only.

BEGIN { pop @INC if $INC[-1] eq '.' }

use strict;
use warnings;
use Fcntl;
use Getopt::Long;
use Digest::SHA qw($errmsg);
use Time::HiRes qw(time);

my $POD = <<'END_OF_POD';

=head1 NAME

shasum - Print or Check SHA Checksums

=head1 SYNOPSIS

 Usage: shasum [OPTION]... [FILE]...
 Print or check SHA checksums.
 With no FILE, or when FILE is -, read standard input.

   -a, --algorithm   1 (default), 224, 256, 384, 512, 512224, 512256
   -b, --binary      read in binary mode
   -c, --check       read SHA sums from the FILEs and check them
       --tag         create a BSD-style checksum
   -t, --text        read in text mode (default)
   -U, --UNIVERSAL   read in Universal Newlines mode
                         produces same digest on Windows/Unix/Mac
   -0, --01          read in BITS mode
                         ASCII '0' interpreted as 0-bit,
                         ASCII '1' interpreted as 1-bit,
                         all other characters ignored
       --progress    report hashing progress to STDERR during
                         checksum calculation

 The following five options are useful only when verifying checksums:
       --ignore-missing  don't fail or report status for missing files
   -q, --quiet           don't print OK for each successfully verified file
   -s, --status          don't output anything, status code shows success
       --strict          exit non-zero for improperly formatted checksum lines
   -w, --warn            warn about improperly formatted checksum lines

   -h, --help        display this help and exit
   -v, --version     output version information and exit

 When verifying SHA-512/224 or SHA-512/256 checksums, indicate the
 algorithm explicitly using the -a option, e.g.

   shasum -a 512224 -c checksumfile

 The sums are computed as described in FIPS PUB 180-4.  When checking,
 the input should be a former output of this program.  The default
 mode is to print a line with checksum, a character indicating type
 (`*' for binary, ` ' for text, `U' for UNIVERSAL, `^' for BITS),
 and name for each FILE.  The line starts with a `\' character if the
 FILE name contains either newlines or backslashes, which are then
 replaced by the two-character sequences `\n' and `\\' respectively.

 When the optional --progress flag is used during checksum calculation,
 progress information is written to STDERR and the final checksum output
 remains on STDOUT.  This preserves compatibility with scripts and
 pipelines that consume checksum output.

 For regular files, progress output includes bytes processed, total size,
 percentage complete, throughput, and estimated time remaining.  For
 standard input or other inputs whose total size is not known in advance,
 progress output includes bytes processed and throughput only.

 The --progress option currently supports normal checksum calculation on
 regular files or standard input, and does not support Universal
 Newlines mode or BITS mode.

Report shasum bugs to mshelor@cpan.org

=head1 DESCRIPTION

Running I<shasum> is often the quickest way to compute SHA message
digests.  The user simply feeds data to the script through files or
standard input, and then collects the results from standard output.

The following command shows how to compute digests for typical inputs
such as the NIST test vector "abc":

	perl -e "print qq(abc)" | shasum

To display optional progress information while hashing a regular file,
use the I<--progress> option:

	shasum --progress -a 256 large-media-file.mp4

Since progress is written to standard error, the checksum result remains
safe to redirect or capture from standard output:

	shasum --progress -a 256 large-media-file.mp4 > checksum.txt

Progress also works when reading from standard input. In that case, the
total size is not known in advance, so only bytes processed and
throughput are displayed:

	cat large-media-file.mp4 | shasum --progress -a 256

Or, if you want to use SHA-256 instead of the default SHA-1, simply say:

	perl -e "print qq(abc)" | shasum -a 256

Since I<shasum> mimics the behavior of the combined GNU I<sha1sum>,
I<sha224sum>, I<sha256sum>, I<sha384sum>, and I<sha512sum> programs,
you can install this script as a convenient drop-in replacement.

Unlike the GNU programs, I<shasum> encompasses the full SHA standard by
allowing partial-byte inputs.  This is accomplished through the BITS
option (I<-0>).  The following example computes the SHA-224 digest of
the 7-bit message I<0001100>:

	perl -e "print qq(0001100)" | shasum -0 -a 224

=head1 AUTHOR

Copyright (C) 2003-2023 Mark Shelor <mshelor@cpan.org>.

=head1 SEE ALSO

I<shasum> is implemented using the Perl module L<Digest::SHA>.

=cut

END_OF_POD

my $VERSION = "6.04";

	## usage: print help or an error message, then exit

sub usage {
	my($err, $msg) = @_;

	$msg = "" unless defined $msg;
	if ($err) {
		warn($msg . "Type shasum -h for help\n");
		exit($err);
	}
	my($USAGE) = $POD =~ /SYNOPSIS(.+?)^=/sm;
	$USAGE =~ s/^\s*//;
	$USAGE =~ s/\s*$//;
	$USAGE =~ s/^ //gm;
	print $USAGE, "\n";
	exit($err);
}


	## Sync stdout and stderr by forcing a flush after every write

select((select(STDOUT), $| = 1)[0]);
select((select(STDERR), $| = 1)[0]);


	## Collect options from command line

my ($alg, $binary, $check, $text, $status, $quiet, $warn, $help);
my ($version, $BITS, $UNIVERSAL, $tag, $strict, $ignore_missing, $progress);

eval { Getopt::Long::Configure ("bundling") };
GetOptions(
	'b|binary' => \$binary, 'c|check' => \$check,
	't|text' => \$text, 'a|algorithm=i' => \$alg,
	's|status' => \$status, 'w|warn' => \$warn,
	'q|quiet' => \$quiet,
	'h|help' => \$help, 'v|version' => \$version,
	'0|01' => \$BITS,
	'U|UNIVERSAL' => \$UNIVERSAL,
	'tag' => \$tag,
	'strict' => \$strict,
	'progress' => \$progress,
	'ignore-missing' => \$ignore_missing,
) or usage(1, "");


	## Deal with help requests and incorrect uses

usage(0)
	if $help;
usage(1, "shasum: Ambiguous file mode\n")
	if scalar(grep {defined $_}
		($binary, $text, $BITS, $UNIVERSAL)) > 1;
usage(1, "shasum: --warn option used only when verifying checksums\n")
	if $warn && !$check;
usage(1, "shasum: --status option used only when verifying checksums\n")
	if $status && !$check;
usage(1, "shasum: --quiet option used only when verifying checksums\n")
	if $quiet && !$check;
usage(1, "shasum: --ignore-missing option used only when verifying checksums\n")
	if $ignore_missing && !$check;
usage(1, "shasum: --strict option used only when verifying checksums\n")
	if $strict && !$check;
usage(1, "shasum: --tag does not support --text mode\n")
	if $tag && $text;
usage(1, "shasum: --tag does not support Universal Newlines mode\n")
	if $tag && $UNIVERSAL;
usage(1, "shasum: --tag does not support BITS mode\n")
	if $tag && $BITS;
usage(1, "shasum: --progress option used only when calculating checksums\n")
	if $progress && $check;
usage(1, "shasum: --progress does not support Universal Newlines mode\n")
	if $progress && $UNIVERSAL;
usage(1, "shasum: --progress does not support BITS mode\n")
	if $progress && $BITS;

	## Default to SHA-1 unless overridden by command line option

my %isAlg = map { $_ => 1 } (1, 224, 256, 384, 512, 512224, 512256);
$alg = 1 unless defined $alg;
usage(1, "shasum: Unrecognized algorithm\n") unless $isAlg{$alg};

my %Tag = map { $_ => "SHA$_" } (1, 224, 256, 384, 512);
$Tag{512224} = "SHA512/224";
$Tag{512256} = "SHA512/256";


	## Display version information if requested

if ($version) {
	print "$VERSION\n";
	exit(0);
}


	## Try to figure out if the OS is DOS-like.  If it is,
	## default to binary mode when reading files, unless
	## explicitly overridden by command line "--text" or
	## "--UNIVERSAL" options.

my $isDOSish = ($^O =~ /^(MSWin\d\d|os2|dos|mint|cygwin)$/);
if ($isDOSish) { $binary = 1 unless $text || $UNIVERSAL }

my $modesym = $binary ? '*' : ($UNIVERSAL ? 'U' : ($BITS ? '^' : ' '));

my $PROGRESS_CHUNK_BYTES = 1024 * 1024;
my $PROGRESS_MIN_SECS    = 0.25;

	## Read from STDIN (-) if no files listed on command line

@ARGV = ("-") unless @ARGV;


	## sumfile($file): computes SHA digest of $file

sub sumfile {
	my $file = shift;

	my $mode = $binary ? 'b' : ($UNIVERSAL ? 'U' : ($BITS ? '0' : ''));

	# Normal fast path: preserve existing behavior exactly
	if (!$progress) {
		my $digest = eval { Digest::SHA->new($alg)->addfile($file, $mode) };
		if ($@) { warn "shasum: $file: $errmsg\n"; return }
		return $digest->hexdigest;
	}

	# Progress-enabled path
	local *FH;
	my $label = ($file eq '-') ? 'stdin' : $file;

	if ($file eq '-') {
		open(FH, '< -') or do { warn "shasum: $file: $!\n"; return };
	}
	else {
		sysopen(FH, $file, O_RDONLY) or do { warn "shasum: $file: $!\n"; return };
	}

	# Preserve binary-mode behavior when requested.
	binmode(FH) if $binary;

	my $sha   = Digest::SHA->new($alg);
	my $total = (-f FH) ? -s FH : undef;
	my $done  = 0;
	my $t0    = time();
	my $last  = 0;
	my $buf   = '';

	while (1) {
		my $n = read(FH, $buf, $PROGRESS_CHUNK_BYTES);
		if (!defined $n) {
			warn "shasum: $file: $!\n";
			return;
		}
		last if $n == 0;

		$sha->add($buf);
		$done += $n;

		my $now = time();
		if (($now - $last) >= $PROGRESS_MIN_SECS) {
			_progress_emit(
				label => $label,
				done  => $done,
				total => $total,
				t0    => $t0,
			);
			$last = $now;
		}
	}

	_progress_emit(
		label => $label,
		done  => $done,
		total => $total,
		t0    => $t0,
	);
	print STDERR "\n";

	return $sha->hexdigest;
}

	## %len2alg: maps hex digest length to SHA algorithm

my %len2alg = (40 => 1, 56 => 224, 64 => 256, 96 => 384, 128 => 512);
$len2alg{56} = 512224 if $alg == 512224;
$len2alg{64} = 512256 if $alg == 512256;


	## unescape: convert backslashed filename to plain filename

sub unescape {
	$_ = shift;
	s/\\\\/\0/g;
	s/\\n/\n/g;
	s/\0/\\/g;
	return $_;
}


	## verify: confirm the digest values in a checksum file

sub verify {
	my $checkfile = shift;
	my ($err, $fmt_errs, $read_errs, $match_errs) = (0, 0, 0, 0);
	my ($num_fmt_OK, $num_OK) = (0, 0);
	my ($bslash, $sum, $fname, $rsp, $digest, $isOK);

	local *FH;
	$checkfile eq '-' and open(FH, '< -')
		and $checkfile = 'standard input'
	or sysopen(FH, $checkfile, O_RDONLY)
		or die "shasum: $checkfile: $!\n";
	while (<FH>) {
		next if /^#/;
		if (/^[ \t]*\\?SHA/) {
			$modesym = '*';
			($bslash, $alg, $fname, $sum) =
			/^[ \t]*(\\?)SHA(\S+) \((.+)\) = ([\da-fA-F]+)/;
			$alg =~ tr{/}{}d if defined $alg;
		}
		else {
			($bslash, $sum, $modesym, $fname) =
			/^[ \t]*(\\?)([\da-fA-F]+)[ \t]([ *^U])(.+)/;
			$alg = defined $sum ? $len2alg{length($sum)} : undef;
		}
		if (grep { ! defined $_ } ($alg, $sum, $modesym, $fname) or
			! $isAlg{$alg}) {
			warn("shasum: $checkfile: $.: improperly " .
				"formatted SHA checksum line\n") if $warn;
			$fmt_errs++;
			$err = 1 if $strict;
			next;
		}
		$num_fmt_OK++;
		$fname = unescape($fname) if $bslash;
		next if $ignore_missing && ! -e $fname;
		$rsp = "$fname: ";
		($binary, $text, $UNIVERSAL, $BITS) =
			map { $_ eq $modesym } ('*', ' ', 'U', '^');
		$isOK = 0;
		unless ($digest = sumfile($fname)) {
			$rsp .= "FAILED open or read\n";
			$err = 1; $read_errs++;
		}
		elsif (lc($sum) eq $digest) {
			$rsp .= "OK\n";
			$isOK = 1;
			$num_OK++;
		}
		else { $rsp .= "FAILED\n"; $err = 1; $match_errs++ }
		print $rsp unless ($status || ($quiet && $isOK));
	}
	close(FH);
	if (! $num_fmt_OK) {
		warn("shasum: $checkfile: no properly formatted " .
			"SHA checksum lines found\n");
		$err = 1;
	}
	elsif (! $status) {
		warn("shasum: WARNING: $fmt_errs line" . ($fmt_errs>1?
		's are':' is') . " improperly formatted\n") if $fmt_errs;
		warn("shasum: WARNING: $read_errs listed file" .
		($read_errs>1?'s':'') . " could not be read\n") if $read_errs;
		warn("shasum: WARNING: $match_errs computed checksum" .
		($match_errs>1?'s':'') . " did NOT match\n") if $match_errs;
	}
	if ($ignore_missing && ! $num_OK && $num_fmt_OK) {
		warn("shasum: $checkfile: no file was verified\n")
			unless $status;
		$err = 1;
	}
	return($err == 0);
}

	## _human_size: format a byte count using human-readable units

sub _human_size {
	my ($n) = @_;
	$n = 0 unless defined $n && $n =~ /^\d+(?:\.\d+)?$/;
	return sprintf("%.1fG", $n / (1024**3)) if $n >= 1024**3;
	return sprintf("%.1fM", $n / (1024**2)) if $n >= 1024**2;
	return sprintf("%.1fK", $n / 1024)			if $n >= 1024;
	return "${n}B";
}

	## _fmt_eta: format a remaining time in seconds as HH:MM:SS or MM:SS

sub _fmt_eta {
	my ($secs) = @_;
	$secs = 0 if !defined($secs) || $secs < 0;
	my $h = int($secs / 3600);
	my $m = int(($secs % 3600) / 60);
	my $s = int($secs % 60);
	return $h ? sprintf("%d:%02d:%02d", $h, $m, $s)
						: sprintf("%02d:%02d", $m, $s);
}

	## _progress_emit: write one progress update line to STDERR

sub _progress_emit {
	my (%args) = @_;
	my $label	 = $args{label};
	my $done	 = $args{done};
	my $total	 = $args{total};
	my $t0		 = $args{t0};

	my $elapsed = time() - $t0;
	$elapsed = 0.001 if $elapsed <= 0;
	my $rate = $done / $elapsed;

	if (defined $total && $total > 0) {
			my $pct = int(($done * 100) / $total);
			$pct = 100 if $pct > 100;
			my $remain = $total - $done;
			$remain = 0 if $remain < 0;
			my $eta = $rate > 0 ? _fmt_eta($remain / $rate) : "--:--";
			printf STDERR "\r%-24s %7s/%-7s %3d%% %7s/s ETA %s",
				$label,
				_human_size($done),
				_human_size($total),
				$pct,
				_human_size($rate),
				$eta;
	} else {
			printf STDERR "\r%-24s %7s %7s/s",
				$label,
				_human_size($done),
				_human_size($rate);
	}
}

	## Verify or compute SHA checksums of requested files

my($file, $digest);
my $STATUS = 0;
for $file (@ARGV) {
	if ($check) { $STATUS = 1 unless verify($file) }
	elsif ($digest = sumfile($file)) {
		if ($file =~ /[\n\\]/) {
			$file =~ s/\\/\\\\/g; $file =~ s/\n/\\n/g;
			print "\\";
		}
		unless ($tag) { print "$digest $modesym$file\n" }
		else          { print "$Tag{$alg} ($file) = $digest\n" }
	}
	else { $STATUS = 1 }
}
exit($STATUS);
