# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables.PL from e.g. Unicode.txt.
# Any changes made here will be lost!
return <<'END';
0000	007F	Basic Latin	# BasicLatin In/40.pl
0080	00FF	Latin-1 Supplement	# Latin1Supplement In/41.pl
0100	017F	Latin Extended-A	# LatinExtendedA In/42.pl
0180	024F	Latin Extended-B	# LatinExtendedB In/43.pl
0250	02AF	IPA Extensions	# IPAExtensions In/44.pl
02B0	02FF	Spacing Modifier Letters	# SpacingModifierLetters In/45.pl
0300	036F	Combining Diacritical Marks	# CombiningDiacriticalMarks In/46.pl
0370	03FF	Greek	# GreekBlock In/47.pl
0400	04FF	Cyrillic	# CyrillicBlock In/48.pl
0530	058F	Armenian	# ArmenianBlock In/49.pl
0590	05FF	Hebrew	# HebrewBlock In/50.pl
0600	06FF	Arabic	# ArabicBlock In/51.pl
0700	074F	Syriac  	# SyriacBlock In/52.pl
0780	07BF	Thaana	# ThaanaBlock In/53.pl
0900	097F	Devanagari	# DevanagariBlock In/54.pl
0980	09FF	Bengali	# BengaliBlock In/55.pl
0A00	0A7F	Gurmukhi	# GurmukhiBlock In/56.pl
0A80	0AFF	Gujarati	# GujaratiBlock In/57.pl
0B00	0B7F	Oriya	# OriyaBlock In/58.pl
0B80	0BFF	Tamil	# TamilBlock In/59.pl
0C00	0C7F	Telugu	# TeluguBlock In/60.pl
0C80	0CFF	Kannada	# KannadaBlock In/61.pl
0D00	0D7F	Malayalam	# MalayalamBlock In/62.pl
0D80	0DFF	Sinhala	# SinhalaBlock In/63.pl
0E00	0E7F	Thai	# ThaiBlock In/64.pl
0E80	0EFF	Lao	# LaoBlock In/65.pl
0F00	0FFF	Tibetan	# TibetanBlock In/66.pl
1000	109F	Myanmar 	# MyanmarBlock In/67.pl
10A0	10FF	Georgian	# GeorgianBlock In/68.pl
1100	11FF	Hangul Jamo	# HangulJamo In/69.pl
1200	137F	Ethiopic	# EthiopicBlock In/70.pl
13A0	13FF	Cherokee	# CherokeeBlock In/71.pl
1400	167F	Unified Canadian Aboriginal Syllabics	# UnifiedCanadianAboriginalSyllabics In/72.pl
1680	169F	Ogham	# OghamBlock In/73.pl
16A0	16FF	Runic	# RunicBlock In/74.pl
1780	17FF	Khmer	# KhmerBlock In/75.pl
1800	18AF	Mongolian	# MongolianBlock In/76.pl
1E00	1EFF	Latin Extended Additional	# LatinExtendedAdditional In/77.pl
1F00	1FFF	Greek Extended	# GreekExtended In/78.pl
2000	206F	General Punctuation	# GeneralPunctuation In/79.pl
2070	209F	Superscripts and Subscripts	# SuperscriptsandSubscripts In/80.pl
20A0	20CF	Currency Symbols	# CurrencySymbols In/81.pl
20D0	20FF	Combining Marks for Symbols	# CombiningMarksforSymbols In/82.pl
2100	214F	Letterlike Symbols	# LetterlikeSymbols In/83.pl
2150	218F	Number Forms	# NumberForms In/84.pl
2190	21FF	Arrows	# Arrows In/85.pl
2200	22FF	Mathematical Operators	# MathematicalOperators In/86.pl
2300	23FF	Miscellaneous Technical	# MiscellaneousTechnical In/87.pl
2400	243F	Control Pictures	# ControlPictures In/88.pl
2440	245F	Optical Character Recognition	# OpticalCharacterRecognition In/89.pl
2460	24FF	Enclosed Alphanumerics	# EnclosedAlphanumerics In/90.pl
2500	257F	Box Drawing	# BoxDrawing In/91.pl
2580	259F	Block Elements	# BlockElements In/92.pl
25A0	25FF	Geometric Shapes	# GeometricShapes In/93.pl
2600	26FF	Miscellaneous Symbols	# MiscellaneousSymbols In/94.pl
2700	27BF	Dingbats	# Dingbats In/95.pl
2800	28FF	Braille Patterns	# BraillePatterns In/96.pl
2E80	2EFF	CJK Radicals Supplement	# CJKRadicalsSupplement In/97.pl
2F00	2FDF	Kangxi Radicals	# KangxiRadicals In/98.pl
2FF0	2FFF	Ideographic Description Characters	# IdeographicDescriptionCharacters In/99.pl
3000	303F	CJK Symbols and Punctuation	# CJKSymbolsandPunctuation In/100.pl
3040	309F	Hiragana	# HiraganaBlock In/101.pl
30A0	30FF	Katakana	# KatakanaBlock In/102.pl
3100	312F	Bopomofo	# BopomofoBlock In/103.pl
3130	318F	Hangul Compatibility Jamo	# HangulCompatibilityJamo In/104.pl
3190	319F	Kanbun	# Kanbun In/105.pl
31A0	31BF	Bopomofo Extended	# BopomofoExtended In/106.pl
3200	32FF	Enclosed CJK Letters and Months	# EnclosedCJKLettersandMonths In/107.pl
3300	33FF	CJK Compatibility	# CJKCompatibility In/108.pl
3400	4DB5	CJK Unified Ideographs Extension A	# CJKUnifiedIdeographsExtensionA In/109.pl
4E00	9FFF	CJK Unified Ideographs	# CJKUnifiedIdeographs In/110.pl
A000	A48F	Yi Syllables	# YiSyllables In/111.pl
A490	A4CF	Yi Radicals	# YiRadicals In/112.pl
AC00	D7A3	Hangul Syllables	# HangulSyllables In/113.pl
D800	DB7F	High Surrogates	# HighSurrogates In/114.pl
DB80	DBFF	High Private Use Surrogates	# HighPrivateUseSurrogates In/115.pl
DC00	DFFF	Low Surrogates	# LowSurrogates In/116.pl
E000	F8FF	Private Use	# PrivateUse In/117.pl
F900	FAFF	CJK Compatibility Ideographs	# CJKCompatibilityIdeographs In/118.pl
FB00	FB4F	Alphabetic Presentation Forms	# AlphabeticPresentationForms In/119.pl
FB50	FDFF	Arabic Presentation Forms-A	# ArabicPresentationFormsA In/120.pl
FE20	FE2F	Combining Half Marks	# CombiningHalfMarks In/121.pl
FE30	FE4F	CJK Compatibility Forms	# CJKCompatibilityForms In/122.pl
FE50	FE6F	Small Form Variants	# SmallFormVariants In/123.pl
FE70	FEFE	Arabic Presentation Forms-B	# ArabicPresentationFormsB In/124.pl
FEFF	FEFF	Specials	# Specials In/125.pl
FF00	FFEF	Halfwidth and Fullwidth Forms	# HalfwidthandFullwidthForms In/126.pl
FFF0	FFFD	Specials	# Specials In/125.pl
10300	1032F	Old Italic	# OldItalicBlock In/127.pl
10330	1034F	Gothic	# GothicBlock In/128.pl
10400	1044F	Deseret	# DeseretBlock In/129.pl
1D000	1D0FF	Byzantine Musical Symbols	# ByzantineMusicalSymbols In/130.pl
1D100	1D1FF	Musical Symbols	# MusicalSymbols In/131.pl
1D400	1D7FF	Mathematical Alphanumeric Symbols	# MathematicalAlphanumericSymbols In/132.pl
20000	2A6D6	CJK Unified Ideographs Extension B	# CJKUnifiedIdeographsExtensionB In/133.pl
2F800	2FA1F	CJK Compatibility Ideographs Supplement	# CJKCompatibilityIdeographsSupplement In/134.pl
E0000	E007F	Tags	# Tags In/135.pl
F0000	FFFFD	Private Use	# PrivateUse In/117.pl
100000	10FFFD	Private Use	# PrivateUse In/117.pl
END
