#!/usr/bin/perl
#
#
# Regenerate (overwriting only if changed):
#
#    .gitattributes
#
# from files that are otherwise automatically regenerated
#
# Accepts the standard regen_lib -q and -v args.
#
# This script is normally invoked from regen.pl.

BEGIN {
    # Get function prototypes
    require './regen/regen_lib.pl';
}

use strict;

# The file is marked as "generated" to Github, so it won't appear in a diff
# See https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
sub is_generated {
    my( $file ) = @_;
    $file =~ s!\r?\n!!;
    return "$file linguist-generated=true\n";
}

# We use the output of t/porting/regen.t to populate the list, instead of
# reusing the code in t/porting/regen.t to find the automatically generated files

my $out= open_new( '.gitattributes', '>',
    { by => $0 } );
print {$out} read_only_top(lang => 'Perl', # well, actually it's "git", but "Perl" is close enough
                           copyright => '2021',
                           file => '.gitattributes',
                           style => '*',
                           copyright => [2021],
                          );

# A hardcoded line
print {$out} '.git_patch export-subst', "\n";

for (<DATA>) {
    print {$out} is_generated($_);
}

read_only_bottom_close_and_rename($out);

# Generated by metaconfig
# Porting/Glossary

# This list should be asciibetically sorted
__DATA__
.gitattributes
charclass_invlists.h
ebcdic_tables.h
embed.h
embedvar.h
feature.h
keywords.c
keywords.h
l1_char_class_tab.h
lib/B/Op_private.pm
lib/feature.pm
lib/overload/numbers.pm
lib/unicore/uni_keywords.pl
lib/unicore/DNormalizationProps.txt
lib/unicore/DCoreProperties.txt
lib/warnings.pm
mg_names.inc
mg_raw.h
mg_vtable.h
miniperlmain.c
opcode.h
opnames.h
overload.h
overload.inc
packsizetables.inc
perly.act
perly.h
perly.tab
pod/buildtoc
pod/perlapi.pod
pod/perlintern.pod
pod/perlmodlib.pod
pod/perltoc.pod
pod/perluniprops.pod
pp_proto.h
proto.h
reentr.c
reentr.h
regcharclass.h
regnodes.h
uconfig.h
unicode_constants.h
uni_keywords.h
warnings.h

