#!/usr/bin/perl

($op = shift) || die "Usage: rename perlexpr [filenames]\n";
if (!@ARGV) {
    if (-t) {
	@ARGV = <*>;
    }
    else {
	@ARGV = <STDIN>;
	chop(@ARGV);
    }
}
for (@ARGV) {
    $was = $_;
    eval $op;
    die $@ if $@;
    rename($was,$_) unless $was eq $_;
}
