*** t/TEST~	Tue Nov 14 08:22:08 1995
--- t/TEST	Wed Nov 22 02:04:22 1995
***************
*** 31,36 ****
--- 31,37 ----
  	last;
      }
  }
+ $sharpbang = 0 if $ENV{OS2_SHELL};		# OS/2
  $bad = 0;
  $good = 0;
  $total = @ARGV;
