d_setregid='undef'
d_setreuid='undef'
d_setrgid='undef'
d_setruid='undef'
d_setegid='undef'
d_seteuid='undef'
memalignbytes=8
ccflags="$ccflags -D_NO_PROTO"
cppstdin='/lib/cpp -D_AIX -D_IBMR2 -U__STR__'
cppminus=''
