#! /bin/sh
# cygwin32.sh - hintsfile for building perl on Windows NT using the
#     Cygnus Win32 Development Kit.
#
_a='.a'
_exe='.exe'
_o='.o'
archname='cygwin32'
# hmm... why Configure doesn't look for this?
#bash='/usr/bin/bash'
bin='/usr/local/bin'
binexp='/usr/local/bin'
byteorder='1234'
cc='gcc'
cccdlflags=''
# ccflags='-I/usr/local/include -ggdb3 -DCYGWIN32 -DDEBUGGING'
# ok, debugging may be not appropriate for everyone
ccflags='-DCYGWIN32'
clocktype='clock_t'
cryptlib='-lcrypt'
dlext='dll'
dlsrc='dl_cygwin32.xs'
exe_ext='.exe'
# work around case-insensitive file names
firstmakefile='GNUmakefile'
gidtype='gid_t'
installman1dir='/usr/local/man/man1'
installman3dir='/usr/local/man/man3'
installscript='/usr/local/bin'
installsitelib='/usr/local/lib/perl5/site_perl'
installusrbinperl='undef'
ld='ld2'
lddlflags='-DCYGWIN32 --export-dynamic --strip-debug'
ldflags="-L. -L`pwd`"
lib_ext='.a'
libperl='libperl.a'
libpth='/usr/lib /usr/local/lib /cygnus/cygwin-b20/H-i586-cygwin32/lib'
libs='-lcygwin -lm -lc -lkernel32'
man1dir='/usr/local/man/man1'
man1direxp='/usr/local/man/man1'
man1ext='1'
man3dir='/usr/local/man/man3'
man3direxp='/usr/local/man/man3'
man3ext='3'
obj_ext='.o'
optimize='-O'
path_sep=':'
prefix='/usr/local'
prefixexp='/usr/local'
scriptdir='/usr/local/bin'
scriptdirexp='/usr/local/bin'
sitelib='/usr/local/lib/perl5/site_perl'
sitelibexp='/usr/local/lib/perl5/site_perl'
sysman='/usr/local/man/man1'
usenm='false'
useperlio='define'
useshrplib='true'
usevfork='true'
usrinc='/usr/i586-cygwin32/include'
