ccflags='-D_POSIX_SOURCE -DUSE_NEXT_CTYPE'
ldflags='-u libsys_s'
libswanted='dbm gdbm db'
lddlflags='-r'
i_utime='undef'
groupstype='int'
direntrytype='struct direct'
d_strcoll='undef'
# the simple program `for ($i=1;$i<38771;$i++){$t{$i}=123}' fails
# with Larry's malloc on NS 3.2 due to broken sbrk()
usemymalloc='n'
d_uname='define'
d_setpgid='define'
d_setsid='define'
d_tcgetpgrp='define'
d_tcsetpgrp='define'
