archname='s390'
cc='cc'
ccflags='-Xa -XTSTRINGS=1500000'
cccdlflags='-pic'
d_bincompat3='undef'        
d_csh='undef'       
d_lstat='define'    
d_suidsafe='define'                 
dlsrc='dl_dlopen.xs'
ld='ld'             
lddlflags='-G -z text'
libperl='libperl.so'
libpth='/lib /usr/lib /usr/ccs/lib' 
libs='-lsocket -lnsl -ldl -lm'
prefix='psf_prefix'  
static_ext='none'    
useshrplib='define'  
