=head1 NAME

abbrev - create an abbreviation table from a list

=head1 SYNOPSIS

    use Abbrev;
    abbrev *HASH, LIST


=head1 DESCRIPTION

Stores all unambiguous truncations of each element of LIST
as keys key in the associative array indicated by C<*hash>.
The values are the original list elements.

=head1 EXAMPLE

    abbrev(*hash,qw("list edit send abort gripe"));
