=head1 NAME

finddepth - traverse a directory structure depth-first

=head1 SYNOPSIS

    use File::Finddepth;
    finddepth(\&wanted, '/foo','/bar');
    sub wanted { ... }

=head2 DESCRIPTION

This is just like C<File::Find>, except that it does a depth-first
search and uses finddepth() rather than find().
