=head1 NAME

MakeMaker - generate a Makefile for Perl extension

=head1 SYNOPSIS

    use ExtUtils::MakeMaker;

=head1 DESCRIPTION

This utility is designed to write a Makefile for an extension module from
a Makefile.PL.  It splits the task of generating the Makefile into several
subroutines that can be individually overridden.  Each subroutines returns
the text it wishes to have written to the Makefile.

The best way to learn to use this is to look at how some of the
extensions are generated, such as Socket.

=head1 AUTHOR

Andy Dougherty <F<doughera@lafcol.lafayette.edu>>,
Andreas Koenig <F<k@franz.ww.TU-Berlin.DE>>,
and
Tim Bunce <F<Tim.Bunce@ig.co.uk>>.
