#!./perl

# We suppose that perl _mostly_ works at this moment, so may use
# sophisticated testing.

BEGIN {
  unshift @INC, '../lib';	# To get lib.pm
}
use lib '../lib';
use Test::Harness;

$Test::Harness::switches = "";	# Too much noise otherwise
$Test::Harness::verbose = shift if @ARGV && $ARGV[0] eq '-v';

@tests = @ARGV;
@tests = <*/*.t> unless @tests;
Test::Harness::runtests @tests;
