# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. Unicode.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{InPrivateUse} (and fuzzy permutations)
# 
# Meaning: Block 'Private Use'
#
return <<'END';
E000	F8FF	Private Use
F0000	FFFFD	Private Use
100000	10FFFD	Private Use
END
