# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Katakana} (and fuzzy permutations)
# 
# Meaning: Script 'KATAKANA'
#
return <<'END';
30A1	30FA	KATAKANA
30FD	30FE	KATAKANA
FF66	FF6F	KATAKANA
FF71	FF9D	KATAKANA
END
