name: smoke-windows-msvc142-amd64

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: windows-latest
    timeout-minutes: 120

    env:
        PERL_SKIP_TTY_TEST: 1
        CONTINUOUS_INTEGRATION: 1

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
            fetch-depth: 10
      #- name: Install clcache
      #  shell: cmd
      #  run: |
      #    curl -L https://github.com/frerich/clcache/releases/download/v4.2.0/clcache.4.2.0.nupkg --output clcache.4.2.0.nupkg
      #    choco install clcache --source=.
      #- name: find home directory
      #  shell: cmd
      #  run: |
      #    set
      #- name: C compiler cache
      #  id: clcache
      #  uses: actions/cache@v1
      #  with:
      #    path: $HOME\clcache
      #    key: ${{ runner.os }}-x64
      #- name: Set up Perl build environment
      #  # pushd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
      #  # for /f "delims=" %%x in ('.\vswhere.exe -latest -property InstallationPath') do set VSPATH=%%x
      #  # popd
      #  # call "%VSPATH%\VC\Auxiliary\Build\vcvarsall.bat" x64
      #  #run: |
      - name: Build
        shell: cmd
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
            cd win32
            nmake CCTYPE=MSVC142
      - name: Run Tests
        shell: cmd
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
            cd win32
            nmake CCTYPE=MSVC142 test
